### ISSUE TITLE
`request` in exception handler is None

### ISSUE THREAD

**Issue by Luftzig** [sanic-org/sanic#1151]
Hello,

I have the following request handler:
```
        @self._app.exception(Exception)
        def to_json(request, exception):
            if request:
                error_logger.exception(log_message(request, exception))
                return json({"error": str(exception), "request": request.body},
                            status=exception.status_code if hasattr(exception, 'status_code') else 500)
            else:
                error_logger.exception("Error occurred outside request handling %s" % exception)
                return json({"error": str(exception)},
                            status=exception.status_code if hasattr(exception, 'status_code') else 500)
```
For some reason I see errors handled by the `else` branch, specifically this:

    aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found'

I need the context of the incoming request because I include a header with a request ID propagated to all services involved.

Expect Behaviour:

request should not be None when handling errors originated from aiohttp.

**Comment by r0fls** [comment]
Do all 404s hit the `else` branch? 🤔

**Comment by go2sh** [comment]
You hit a very tricky case in python. Your if check does two things:
1) Check for not `None`
2) Check for `__len__()` > 0 (since request is a subclass of dict)
Nearly all of your objects will hit false in the 2. case and you fall through in the else clause. It's better to check for `request is not None`.

**Comment by go2sh** [comment]
Btw see: https://docs.python.org/3.6/library/stdtypes.html#truth-value-testing

**Comment by r0fls** [comment]
Maybe we should override the length method? Or is that a silly idea?

**Comment by sunny94** [comment]
As pointed out by @go2sh in [comment](https://github.com/channelcat/sanic/pull/1156#issuecomment-372136646) we should override __bool__ method instead of __len__.

**Comment by sjsadowski** [comment]
@r0fls should we work on a PR for this one?
