### ISSUE TITLE
Inconsistency in documentation and examples 

### ISSUE THREAD

**Issue by alexandertsema** [sanic-org/sanic#1165]
There is an example of how to [implement request id logging](https://github.com/channelcat/sanic/blob/master/examples/log_request_id.py) The [documentation ](https://sanic.readthedocs.io/en/latest/sanic/deploying.html#asynchronous-support) says that running the Sanic like it is done in this example is highly discouraged.
Is the documentation old and now it's fine to use that approach with multiple workers or the example is misleading?
Cheers.

**Comment by andreymal** [comment]
**@&#8203;stale** nope
