### ISSUE TITLE
Documentation for sanic.log.* is missing

### ISSUE THREAD

**Issue by peterfraedrich** [sanic-org/sanic#1218]
There is a huge lack of documentation around the `sanic.log` module. In the latest version of the docs there is exactly zero API reference for it `sanic.log.*`.

http://sanic.readthedocs.io/en/latest/sanic/api_reference.html#module-sanic.log

Additionally, the `Logging` section of the docs doesn't provide enough information on configuration or available logging methods for Sanic. `Latest` logging docs are a subset of the `0.6.0` logging docs.

**Comment by andreymal** [comment]
**@&#8203;stale** nope

**Comment by ahopkins** [comment]
See https://sanicframework.org/guide/best-practices/logging.html
