### ISSUE TITLE
auto_reload support for Windows

### ISSUE THREAD

**Issue by mungojam** [sanic-org/sanic#1346]
This would be really useful for us. We don't have an option to use Linux for development unfortunately

**Comment by vltr** [comment]
Today our reloader is completely dependant in the way POSIX works ... But I really think that a more generic approach is possible to make this behavior available for POSIX **and** Windows almost transparently, but I'll have to do some hard digging in there to see if my idea really works ...

**Comment by abuckenheimer** [comment]
I took a quick look was surprised to find that the re-loader is only really dependent on posix for killing the existing server process and children and not to detect file changes. My guess is we could probably use something like [psutil](https://psutil.readthedocs.io/en/latest/) to make this more uniformly platform independent but not sure we'd want that as a dependency.

**Comment by yunstanford** [comment]
This functionality could actually be put into a plugin. And current implementation is also a little bit error-prone. It'll certainly require more mature process management.

**Comment by andreymal** [comment]
**@&#8203;stale** nope
