### ISSUE TITLE
Add example code details to Documentation

### ISSUE THREAD

**Issue by harshanarayana** [sanic-org/sanic#1401]
**Describe the bug**
Currently, we have a lot of examples of different use cases in `sanic`. However, it's missing from the Documentation. 

**Code snippet**
NA

**Expected behavior**
It will be good if we can have a reference to each of the example code with some brief description in the Documentation section so that everything can be found under a common roof.

**Environment (please complete the following information):**
NA

**Additional context**
NA

# Documentation - To Do

- [ ] Review and include any missing sections of the changes into Documentation post the current LTS release
- [ ] Examples
- [ ] Tutorials 
- [ ] API Definitions
- [ ] Some enhancement to Contribution guidelines to include PR process and Commit guidelines. (i.e. Commit message format guideline. Would be easy to auto-generate a Change Log eventually.)
- [ ] Some details about Release Versioning and the upcoming release schedules (if available)

**Comment by ahopkins** [comment]
Examples and a "tutorial" was something I have been wanting to add to a beefed up home page and documentation. After this next release I am hoping we can get a few people working together to make a big push on this effort. Care to help?

**Comment by harshanarayana** [comment]
@ahopkins Yes. I'm always game for documentation. I also noticed that some of the APIs are missing documentation that needs to be included.

**Comment by harshanarayana** [comment]
@ahopkins I added a few items under the checkbox to track the things that need to go into Documentation update. Please feel free to update it as applicable.

**Comment by ahopkins** [comment]
Will do. @sjsadowski... want to add this to the project board?

**Comment by LBWright** [comment]
@ahopkins @harshanarayana I've been thinking about building out examples but I'd like a little clarity.

Would it be better to showcase connecting to a low-level db using an async driver, or would it be better to incorporate a few examples that users would likely be using - like asyncpg?

**Comment by harshanarayana** [comment]
@LBWright it's better to keep the examples as exhaustive as possible. Both items you mentioned has its own advantage but caters to two different level of audiences. So, why limit when we add examples? We add both and let the end user decide which one they want to use.

**Comment by LBWright** [comment]
Sounds good! I just wanted to make sure I had permission to start libraries into my examples.

**Comment by vltr** [comment]
@LBWright we sure need any kind of example possible, from the simplest "hello world" to advanced `asyncio` hacks and integrations. If you look at what has been asked in the [issues](https://github.com/huge-success/sanic/issues?utf8=%E2%9C%93&q=is%3Aissue) so far, [gitter](https://gitter.im/sanic-python/Lobby) and in the [community forums](https://community.sanicframework.org/c/questions-and-help), you would be surprised on the variety of topics :wink:

**Comment by snguyenthanh** [comment]
Looking at the recent posts in [community forum](https://community.sanicframework.org), I found some cool examples, and I think it would be nice to have in `Documentation`:

1. [Sanic with `Celery`](https://community.sanicframework.org/t/add-examples-for-celery-with-sanic/341)
2. [Asyncio's queue in Sanic](https://community.sanicframework.org/t/how-to-use-asyncio-queues-in-sanic/166)
3. [Deployment on AWS with Docker](https://community.sanicframework.org/t/aws-deployment-guidelines/221)
    - Extra: [sanic-docker](https://github.com/huge-success/sanic-docker)
4. [Sanic as a proxy with aiohttp](https://community.sanicframework.org/t/how-to-respond-with-the-exact-response-from-an-aiohttp-request/303)
5. [With NginX](https://community.sanicframework.org/t/performance-decline-when-using-nginx-reverse-proxy/203)

**Comment by Tronic** [comment]
The first feeling I get of that list of things that none of them are strongly related to Sanic and will definitely be better documented elsewhere.

One thing that bothered me when coming to Sanic is the mention of deployment with daphne, uvicorn and hypercorn but no tips on which to use, or if this even has any benefits over the built-in server.

**Comment by ahopkins** [comment]
The new [sanic-guide](https://github.com/sanic-org/sanic-guide) repo (that houses the [Sanic frontpage](https://sanicframework.org/)) has a section for this. Over the next few months, I hope to fill that out.

**Comment by ahopkins** [comment]
Anything that is missing and should still be added to the docs should be discussed in the sanic-guide repo.
