### ISSUE TITLE
Fix auto_reloader in less naive way

### ISSUE THREAD

**Issue by sjsadowski** [sanic-org/sanic#1504]
This is a placeholder for overhauling auto_reload again after the patch to fix it for 19.3

**Comment by chenjr0719** [comment]
Actually, there is a tool named `sanic-admin`(check [here](https://github.com/38elements/sanic-admin)) can do exactly what `auto_reloader` wants to do. I have been using it for a long time and it works pretty well. Maybe consider to leveraging(or integrate) `sanic-admin` to fix the problems of `auto_reloader`?

**Comment by sjsadowski** [comment]
@chenjr0719 thanks for the tip!

**Comment by seemethere** [comment]
Can we link the original patch to `19.3` so that we have some context into what was actually done?

**Comment by ahopkins** [comment]
@seemethere, I believe this: https://github.com/huge-success/sanic/commit/42605286456c4a61bc2c4423a1415c3943e121bc

**Comment by ahopkins** [comment]
Is this still relevant? What is wrong with auto_reload?

**Comment by ChihweiLHBird** [comment]
@sjsadowski @chenjr0719 Are we still having any issue with auto_reload?

**Comment by ahopkins** [comment]
Hmm... Not that I am aware of :thinking: 

I did some work on it with #2167 which will be released soon to allow listening on specific directories (helpful for static file changes, etc). I think this is probably stale. Removing `necessary` label so it can die off in time unless someone sees a better reason to keep it open.
