### ISSUE TITLE
Support mounting application elsewhere than at root path

### ISSUE THREAD

**Issue by Tronic** [sanic-org/sanic#1731]
Sanic app might be exposed publicly in a path other than root at a HTTP server that also serves other things on the same domain.  E.g. `https://company.com/blog/` is proxied to Sanic app at `http://localhost:8000/`.

Currently Sanic offers no support for that, with `url_for` resolving to absolute paths pointing at site root.

It would be good to add support e.g. via `config.SERVER_NAME` that also included the external root path, so that proper URLs would be formed whenever external URLs are requested. The path information is already available but not used if presented on proxy headers `req.forwarded`, whereas I am not exactly sure of `SERVER_NAME` handling.

**Comment by sjsadowski** [comment]
I like this idea.

**Comment by ahopkins** [comment]
This seems like a fairly easy one to add.

**Comment by ahopkins** [comment]
Related discussion: https://community.sanicframework.org/t/sanic-app-on-nginx-subpath/463

**Comment by ahopkins** [comment]
I finally got back to testing this. I ran the following on:

- 19.12LTS
- 20.12LTS
- master
- sanic-routing

On all of these branches, this seemed to work fine.

```python
from sanic import Sanic
from sanic.response import text

app = Sanic("app")
app.config.SERVER_NAME = "example.com/api"


@app.route("/foo")
def handler(request):
    url = app.url_for("handler", _external=True)
    return text(f"URL: {url}")
```

The result:

```
URL: http://example.com/api/foo
```

Am I missing something? Can we close this?

**Comment by ashleysommer** [comment]
Yep, that's right. I deploy sanic using that same pattern at my workplace in several applications.
I agree there could be a slightly more elegant way of doing it, but using `config.SERVER_NAME` is easy and _just works_ (as long as you remember to always pass `_external=True` to `url_for()`)
Maybe it could be documented better?

**Comment by ahopkins** [comment]
Marking as a documentation issue.

**Comment by ahopkins** [comment]
[Documented in this PR](https://github.com/sanic-org/sanic-guide/pull/11)
