### ISSUE TITLE
Why define an exception handler needed async?

### ISSUE THREAD

**Issue by matianjun1** [sanic-org/sanic#1804]
with tests/test_exceptions_handler.py define an exception handler like this:

> @exception_handler_app.exception(NotFound, ServerError)
> def handler_exception(request, exception):
>     return text("OK")

but in docs [https://sanic.readthedocs.io/en/latest/sanic/exceptions.html](https://sanic.readthedocs.io/en/latest/sanic/exceptions.html)

> @app.exception(NotFound)
> async def ignore_404s(request, exception):
>     return text("Yep, I totally found the page: {}".format(request.url))

what is the difference? And is async def needed?

**Comment by Tronic** [comment]
In general all handlers in Sanic can be async or normal functions. You are free to use either even though in documentation `async def` is generally preferred even if the function doesn't need to be async.

In the current version there is a limitation that async error handlers might not work in some contexts (protocol errors), so a normal function is actually a safer choice there. This is due to be fixed in a future version.

**Comment by matianjun1** [comment]
thx~I do meet unexcepted exception with async def in exceptions handler. And it works good with def only.

**Comment by ashleysommer** [comment]
@matianjun1 
Yes, this issue has come up a few times. The documentation needs to be changed.

The confusion comes from the fact Sanic request handler _does_ support async exception handlers, see here: https://github.com/huge-success/sanic/blob/60b4efad67ba3b22dfaf83820c772cd7f5ff137c/sanic/app.py#L1015

But the sanic asyncio server implementation _does not_ support async exception handlers.
https://github.com/huge-success/sanic/blob/60b4efad67ba3b22dfaf83820c772cd7f5ff137c/sanic/server.py#L577

So I think for now we should remove any mention of async exception handlers in the documentation, and look at how we can get async exception handlers working at the asyncio server level.

**Comment by Tronic** [comment]
Agreed, it would be best not to mention async exception handlers in documentation for now. This is one of the problems fixed in #1791 but it will take a few more months until that can ship, and there is no quick and easy way to fix this otherwise.

**Comment by ashleysommer** [comment]
Is is just the docs at https://sanic.readthedocs.io/en/latest/sanic/exceptions.html that show an async error handler? Are there any other mentions anywhere else that need changing?
