### ISSUE TITLE
Hard error on invalid max-age cookie

### ISSUE THREAD

**Issue by jamesstidard** [sanic-org/sanic#1810]
**Describe the bug**
Currently when setting the `max-age` cookie value, it's possible for a valid value to not be set as expected, as well as an invalid value from raising a hard error. In both cases the values are replaced by a `0` `max-age`.

**Code snippet**
```python
response.cookie["my-cookie"]["max-age"] = 10.0  # max-age is set to 0
response.cookie["my-cookie"]["max-age"] = 10.5  # max-age is set to 0
response.cookie["my-cookie"]["max-age"] = "ten"  # max-age is set to 0
response.cookie["my-cookie"]["max-age"] = "10"  # max-age is set to 10
response.cookie["my-cookie"]["max-age"] = 10  # max-age is set to 10
```

**Expected behavior**
Here's what I think the expected behaviour should be (akin to how the `expires` cookie attribute is handled; raising an error if not a `datetime.datetime`).

```python
response.cookie["my-cookie"]["max-age"] = 10.0  # max-age is set to 10
response.cookie["my-cookie"]["max-age"] = 10.5  # raise ValueError
response.cookie["my-cookie"]["max-age"] = "ten"  # raise ValueError
response.cookie["my-cookie"]["max-age"] = "10"  # max-age is set to 10
response.cookie["my-cookie"]["max-age"] = 10  # max-age is set to 10
```

**Environment (please complete the following information):**
 - OS: macOS
 - Version 19.12.2

**Additional context**
I've created a pull request for this here #1809. Here's the issue relating to the original implementation #1452.

Creating this issue so I can have an issue number for the changelog.

**Comment by myuz** [comment]
@ahopkins Should we close the ticket? looks like https://github.com/huge-success/sanic/pull/1457 was fixed the issue.

**Comment by ahopkins** [comment]
Let's investigate. That PR was several years ago. There was a change to cookies not that long ago, maybe it is a regression? Let's confirm this on both sanic server and ASGI. I'm not at the computer now to check if there are tests for this already or not.

**Comment by myuz** [comment]
Looks like for the server we have the tests, but for ASGI don't have.
