### ISSUE TITLE
Sanic cause asyncio.create_subprocess_exec fail

### ISSUE THREAD

**Issue by zillionare** [sanic-org/sanic#1868]
**Describe the bug**

I'm trying to start several child process by asyncio.create_subprocess_exec, whihc is intended to run sanic. Without import sanic, everything runs ok:

**Code snippet**
```python
#from sanic import Sanic
#app = Sanic('app_name')

class FetcherServer:
    @classmethod
    async def create_process(cls, config_dir: str, port:int, workers: int=None,
                             **kwargs):
        code = f'from {cls.__module__} import {cls.__name__}; {cls.__name__}.process_entry()'
        params = kwargs or {}
        params.update({
            'config_dir': config_dir
        })

        opts = " ".join([f"--{k}={v}" for k, v in params.items()])
        return await asyncio.create_subprocess_exec(sys.executable,
                                                    '-c',
                                                    code,
                                                    opts)
    async def init(self):
        print("running init here!")

    @classmethod
    def process_entry(cls):
        # parse opt into params
        params = ...
        fetcher = cls(**params)

        loop = asyncio.get_event_loop()
        loop.create_task(fetcher.init())
        #app.run(host='0.0.0.0', port = ..)  # app is a Sanic object
        loop.run_forever()
```
The caller:
```python
async def test_start():
    proc = await FetcherServer.create_process(...)
```
Everything works fine till now, and the init function is called. but if I uncomment out those comments, thus sanic steps in, and all are broke with two versions: 
1. raise io.UnsupportedOperation error:
```
  File "/workspace/omega/omega/service/quotesfetcher.py", line 90, in create_process
    return await asyncio.create_subprocess_exec(sys.executable,
  File "/home/aaron/miniconda3/envs/omega/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "uvloop/loop.pyx", line 2749, in subprocess_exec
  File "uvloop/loop.pyx", line 2707, in __subprocess_run
  File "uvloop/handles/process.pyx", line 596, in uvloop.loop.UVProcessTransport.new
  File "uvloop/handles/process.pyx", line 60, in uvloop.loop.UVProcess._init
  File "uvloop/handles/process.pyx", line 49, in uvloop.loop.UVProcess._init
  File "uvloop/handles/process.pyx", line 274, in uvloop.loop.UVProcess._init_options
  File "uvloop/handles/process.pyx", line 486, in uvloop.loop.UVProcessTransport._init_files
io.UnsupportedOperation: fileno
```
I realize it's caused by stderr/stdin/stdout arguemnts, then I replaced line 

```python
        return await asyncio.create_subprocess_exec(sys.executable,
                                                    '-c',
                                                    code,
                                                    opts)
```
with
```python
        return await asyncio.create_subprocess_exec(sys.executable,
                                                    '-c',
                                                    code,
                                                    opts,
                                                    stderr=asyncio.subprocess.PIPE,
                                                    stdin=asyncio.subprocess.PIPE,
                                                    stdout=asyncio.subprocess.PIPE) # not sure if this is right value
```
then I got version 2: 
2. no exceptions, but process_entry is not entered.

My question:
why the app behave like this when sanic drop in? Is this a bug of sanic or I uses it in a wrong style?

**Environment (please complete the following information):**
 - OS: WSL
 - Version:
sanic: 20.3.0
python: 3.8

**Comment by Tronic** [comment]
EDIT: Reformatted OP code block tags for readability.

For starters, I can say that what you are doing is definitely not a conventional way to run Sanic. Why that doesn't work and what you should do instead, I cannot look into. Maybe someone else can pick this up?

**Comment by ahopkins** [comment]
I think the first question is why are you trying to run Sanic this way? What is the goal?

**Comment by zillionare** [comment]
Actually what I want is a RPC server, or a micro-service server, not a HTTP server. Just not able to find an ideal one. Since the benchmark shows sanic is fastest, so I decide to have a try.

The reason that I'd like to use sanic this way is, the application should have several groups of servers, which will load different extensions, to fetch data from different sources (different servers and protocols, thus different initial method and configurations). It's hard or should NOT be consolidate into one group, for example, if one server worker is gone, the manager process should restart one in same group only.

That should not be very rare in micro-service world, am I right? Whic is the best practice to launch, manage sanic groups, is there a tool already?

Surely I can still launch several groups of sanic workers, each group have several workers, and managed manually ( a shell script). I'd just like to have python script to manage them.

**Comment by zillionare** [comment]
btw, just an update. I have succussefully launched sanic and make it work in my env, just use subproces.Popen instead of asyncio.create_subprocess_exec. subprocess.Popen allows to create subprocess in non-blocking way, so in my main process, I can continue run other init procedures.

**Comment by mikepurvis** [comment]
Just chiming in here, I had a slightly different problem but also related to trying to call other previously-developed async code which uses `asyncio.subprocess` from Sanic— I described it in more detail in https://github.com/MagicStack/uvloop/issues/317#issuecomment-689920778, but for the purposes of unblocking myself, I just reverted to the default async loop implementation after importing Sanic, and then all was well:

```
import sanic
asyncio.set_event_loop_policy(asyncio.DefaultEventLoopPolicy())
```

For my purposes, this was more straightforward than having to set the envvar at installation time so that the `uvloop` package would be excluded from the environment altogether. Anyhow, just wanted to throw this out there for others who may be having uvloop-related headaches and whose application don't call for the absolute maximum in terms of performance.
