### ISSUE TITLE
Websocket close exception

### ISSUE THREAD

**Issue by rhollencamp** [sanic-org/sanic#1871]
**Describe the bug**
When a websocket is closed a `ConnectionClosed` exception should be raised. This works when using `websockets==7.0` but not `websockets==8.X`, which raises a `CancelledError` instead

**Code snippet**
run below test with websockets 7 and websockets 8 to observe the difference

    from asyncio import sleep
    from asyncio import CancelledError
    import websockets

    from sanic import Sanic
    from sanic.websocket import ConnectionClosed

    app = Sanic("websocket test")

    @app.websocket("/")
    async def test(_, ws):
        try:
            while True:
                await ws.recv()
        except Exception as e:
            print("exception type %s" % e.__class__.__name__)
            raise

    async def run_test():
        await sleep(2)
        async with websockets.connect("ws://localhost:8000/") as websocket:
            await websocket.send("Hello world!")
        await sleep(2)
        app.stop()
    app.add_task(run_test())

    if __name__ == "__main__":
        app.run(host="0.0.0.0", port=8000)

**Expected behavior**
when a websocket is closed it should raise a ConnectionClosed exception (https://websockets.readthedocs.io/en/7.0/api.html#websockets.protocol.WebSocketCommonProtocol.recv)

**Environment (please complete the following information):**
 - OS: linux
 - Version 19.12.2

**Comment by jamesstidard** [comment]
I've also noticed this change. I moved some of my disconnect logic inside a subclass of `WebSocketProtocol.connection_lost` while looking at this.

On running the above on `sanic==20.6.3 websockets==8.1` I actually see no exception raised at all:

```console
[2020-07-23 11:11:37 +0100] [69435] [INFO] Goin' Fast @ http://0.0.0.0:8000
[2020-07-23 11:11:37 +0100] [69435] [INFO] Starting worker [69435]
[2020-07-23 11:11:41 +0100] [69435] [INFO] Stopping worker [69435]
[2020-07-23 11:11:41 +0100] [69435] [INFO] Server Stopped
```

**Comment by jamesstidard** [comment]
I'm not that familiar with the internals of these two libraries, but I think I've tracked this down - to some extent.

In `websockets~=8.0`, `websockets.protocol.WebScoketCommonProtocol.recv` ([here](https://github.com/aaugustin/websockets/blob/139085fe2624192a5a6c72b1e5db211dcec6ced1/src/websockets/protocol.py#L443)) calls in to `websockets.protocol.WebScoketCommonProtocol.ensure_open` ([here](https://github.com/aaugustin/websockets/blob/139085fe2624192a5a6c72b1e5db211dcec6ced1/src/websockets/protocol.py#L784)), which looks to be responsible for raising these exceptions ([here](https://github.com/aaugustin/websockets/blob/139085fe2624192a5a6c72b1e5db211dcec6ced1/src/websockets/protocol.py#L812)). 

The `raise` line is never reached. The `asyncio.shield` doesn't seem to ever return the result of the `self.close_connection_task`. Removing the `asyncio.shield` and just awaiting the task regularly makes things behave as expected and a `webscokets.ConnectionClosedOK` is raised from the example above.

I'm not sure why the `asyncio.shield` is suppressing the result coming back from the task. A shielded Task [should be](https://docs.python.org/3/library/asyncio-task.html#asyncio.shield) able to be awaited like the original task. 

Only when a `CancelledError` is raised should prevent `ensure_open` from completing. I put in a try/except to look for that event, but that never caught anything, so it doesn't appear to be being cancelled either.

That's about as far as I've got. Hopefully this is helpful.

**Comment by ahopkins** [comment]
Super helpful. Thanks for tracking that much down.

**Comment by aaugustin** [comment]
This is a plausible cause: https://github.com/aaugustin/websockets/issues/803#issuecomment-664042889

**Comment by ahopkins** [comment]
See #2000
