### ISSUE TITLE
Stopping an Async Webserver Closes the Event Loop, regardless if other things are running in the loop

### ISSUE THREAD

**Issue by StuartFarmer** [sanic-org/sanic#1874]
**Describe the bug**
When stopping the web server, the library just brute force closes the event loop rather than gracefully closing and cleaning up. This prevents Sanic from being used in any applications where other asynchronous functions need to still run while turning the webserver off.

**Code snippet**
https://github.com/huge-success/sanic/blob/master/sanic/app.py#L1172

**Expected behavior**
The library should take responsibility for stopping itself without interfering with the rest of the program. If Sanic needs to kill the entire event loop, a new event loop should be running that is separate from the main loop.

**Environment (please complete the following information):**
 - OS: Mac OSX
 - Version 10.14.1

**Comment by Tronic** [comment]
You are right, the create server mode should respect the existing loop. Sanic does not recommend the use of that mode because the implementation cannot quite accomplish that. In general, it is a good idea to run all of Sanic in its own process (or set of processes, in case auto_reloader or workers are being used).

Related discussion in PR #1835.

PRs for server startup and shutdown logic are welcome but be warned that those are a few of the darkest corners of Sanic's codebase, and you'll have to be careful not to break it for others.

**Comment by StuartFarmer** [comment]
Why can't Sanic accomplish this in a more straightforward and default fashion? I actually was able to solve this problem without a new process. Sanic is just using the native asyncio server under the hood which simply has a `close()` function on it. You should just call `close()` on the server object instead of killing the current event loop. It's not that big of a change.

When I create the server, I do this:

```python
self.coroutine = asyncio.ensure_future(
                self.app.create_server(
                    host='0.0.0.0',
                    port=self.port,
                    debug=self.debug,
                    access_log=self.access_log,
                    return_asyncio_server=True
                )
            )
```

This gives me a Future object which populates the `result()` property when Sanic is done creating the asyncio server. I can prevent premature 'closing' of the server by waiting for the Future to be done first.

When I want to kill the Sanic server without ending my event loop, I just run:

```python
self.coroutine.result().close()
```

No new threads. No new processes. No new event loops. Asyncio works best when you keep it all together in a single process and only use processes when you need to accomplish a specific piece of work in a ProcessPoolExecutor or something of the like.

**Comment by ahopkins** [comment]
@StuartFarmer Can you put together a PR so we can review it?

**Comment by mikepurvis** [comment]
Hey, just chiming in here with a related concern— in my application, I open some resources on demand as connections require them, and would like to be able to take care of closing them via coroutine cancellation, eg:

```
    async def closer(self):
        try:
            while True:
                await asyncio.sleep(60)
        finally:
            await self._handle.close()
```

And then when I open the connection, I can just:

```
asyncio.create_task(self.closer())
```

This approach works fine in "normal" uvloop with `asyncio.run()`, as all tasks get canceled and a chance to clean up after themselves when the loop exits, but under Sanic it's just a hard cutoff. I know I can move the cleanup to a `finally` outside the loop and there are probably a variety of other ways this could be done, but I was surprised this didn't do the right thing.

**Comment by mikepurvis** [comment]
Just to follow up here, I ended up finding this wasn't too bad. Building off of what @StuartFarmer suggested above, here's a Python 3.8 version which closes cleanly, uses `asyncio.run`, and doesn't reference the loop explicitly:

```
    async def run_server():
        server = await app.create_server(
            host=args.host,
            port=args.port,
            return_asyncio_server=True
        )
        return await server.serve_forever()

    try:
        asyncio.run(run_server())
    except KeyboardInterrupt:
        pass
```

**Comment by StuartFarmer** [comment]
@ahopkins If I have some more time, I can file a PR. It will make Sanic a lot more usable in more complex applications where you need more control over the server and an object. Do you want me to provide a new API such as `stop_coroutine()` or something?

**Comment by StuartFarmer** [comment]
@mikepurvis I'll try to accomplish this in a more elegant way than a try-catch. Any requests for how it should look?

**Comment by ahopkins** [comment]
> @ahopkins If I have some more time, I can file a PR. It will make Sanic a lot more usable in more complex applications where you need more control over the server and an object. Do you want me to provide a new API such as `stop_coroutine()` or something?

That works. Although, I would think something more like `shutdown`, or even `stop` is nicer than `stop_coroutine`.

I think one challenge we will have here is reconciling versions. There are still an unsubstantial number of 3.6 downloads per day, and it will be a Python supported version through Dec 2021. This is partially the reason there is [a seperate doc for 3.7 implementation](https://github.com/huge-success/sanic/blob/master/docs/sanic/asyncio_python37.rst).

**Comment by StuartFarmer** [comment]
@ahopkins are you saying that this is fixed in 3.7?

**Comment by ahopkins** [comment]
> @ahopkins are you saying that this is fixed in 3.7?

I meant to say that the example @mikepurvis shows above [has some 3.7+ only methods](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.Server.serve_forever).

**Comment by mikepurvis** [comment]
All those methods are just sugar to make using asyncio more ergonomic, though. If Sanic needs to support 3.6, they could be easily reimplemented, or even just directly backported/monkey-patched, eg:

https://github.com/python/cpython/blob/d50a0700265536a20bcce3fb108c954746d97625/Lib/asyncio/base_events.py#L355-L374

@StuartFarmer I think the ideal scenario from my point of view would be if the "batteries included" `app.run` method would cleanly exit on `KeyboardInterrupt`, but allow the exception to propagate. Then it's up to the user code to catch and suppress that if desired, add timeouts or loop-killing for anything badly-behaved on their side, whatever. But I think the getting started example should be unchanged; the only difference being that under the hood, if the user creates a task from one of their handlers, it should be properly canceled and have a chance to finish when the server's loop exits. This would be achieved by making the implementation of `app.run` essentially be `asyncio.run(run_server())` as given in my example above.

**Comment by ahopkins** [comment]
> All those methods are just sugar to make using asyncio more ergonomic, though. If Sanic needs to support 3.6, they could be easily reimplemented, or even just directly backported/monkey-patched, eg:

Right.  Just bringing attention to that.

> @StuartFarmer I think the ideal scenario from my point of view would be if the "batteries included" `app.run` method would cleanly exit on `KeyboardInterrupt`, but allow the exception to propagate. Then it's up to the user code to catch and suppress that if desired, add timeouts or loop-killing for anything badly-behaved on their side, whatever. But I think the getting started example should be unchanged; the only difference being that under the hood, if the user creates a task from one of their handlers, it should be properly canceled and have a chance to finish when the server's loop exits. This would be achieved by making the implementation of `app.run` essentially be `asyncio.run(run_server())` as given in my example above.

:+1:

Anyone here want to take a stab at a PR on this? Now that 20.9 is out, I am happy to take it on unless one of you would like it.

**Comment by StuartFarmer** [comment]
I might have some free time to dig into this, but no promises immediately. If I do start a branch, I'll make it known here. Similarly, if anyone makes a branch, let me know and I can lend some free time.

**Comment by ahopkins** [comment]
@StuartFarmer any luck?

**Comment by ahopkins** [comment]
@StuartFarmer Did you ever do any work on this?

**Comment by mikepurvis** [comment]
I still think this is important.

**Comment by ahopkins** [comment]
The latest release added a `shutdown` for tasks that are named. I am thinking that maybe we could add to this functionality and simply add all tasks and that should resolve this ticket.

**Comment by zwn** [comment]
I got here after finding this in my terminal:

```
...
python3.11/site-packages/sanic/server/runners.py", line 283, in _cleanup
    loop.run_until_complete(asyncio.sleep(0.1))
  File "uvloop/loop.pyx", line 1515, in uvloop.loop.Loop.run_until_complete
RuntimeError: Event loop stopped before Future completed.
```

The code here

https://github.com/sanic-org/sanic/blob/acb29c9dc4d6ba3a453a18e30f0664ba6772a9b4/sanic/server/runners.py#L280-L284

is expecting that the loop is running. But the code here

https://github.com/sanic-org/sanic/blob/acb29c9dc4d6ba3a453a18e30f0664ba6772a9b4/sanic/mixins/startup.py#L635

stops it.

From reading the code I get the feeling that the loop should not be stopped and not because of some outside code but because other parts of the codebase expect it to be still running.

**Comment by ahopkins** [comment]
At some point we need to just turn it off. The graceful shutdown can be increased if needed.
