### ISSUE TITLE
Dependency audit

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic#1908]
In light of changes that are coming in October regarding [pip dependency resolution](https://pythoninsider.blogspot.com/2020/07/upgrade-pip-20-2-changes-20-3.html?m=1), we should do some house cleaning on versions that Sanic is requiring to help reduce any pain points there may be with conflicting versions. 

The solution is to reduce dependencies where we can (like httpx), and also loosen restrictions. One that immediately springs to mind is `websockets`.

**Comment by mikepurvis** [comment]
Having `httpx==0.11.1` is definitely not ideal. That release is just from January this year, so it's not like the _worst_, but it's also a relatively fast-moving package, so there are a bunch of fixes that have gone in since then.

**Comment by ashleysommer** [comment]
`httpx` dependency is going away after https://github.com/huge-success/sanic/pull/1850 is merged.

@ahopkins what do you have in mind around the `websockets` dependency?
Could we make it optional, using the setuptools `Extras` mechanism?

**Comment by Tronic** [comment]
I might be interested in doing our own websocket implementation for 21.3, suggesting to keep it in the main project for now. The protocol is simple and our own implementation would avoid not only the dependency but also the unexpected buffering delays of the `websockets` module.

**Comment by ashleysommer** [comment]
Sounds great. I wonder, is there anything else we can do to reduce dependencies further before the 20.9 release?
>  in light of changes that are coming in October regarding [pip dependency resolution](https://pythoninsider.blogspot.com/2020/07/upgrade-pip-20-2-changes-20-3.html?m=1)

**Comment by ahopkins** [comment]
The question is whether we want to blow away `testing.py` before the LTS. I was under the impression that we would leave it (and therefore the `httpx` dependency until then. But, @mikepurvis makes a good point. It has been my own point of frustration because `testing.py` does rely upon a now outdated API (although, it is easy to correct with a couple `try/except` import changes. Regardless, what do people think? Should we remove it sooner rather than later? It **IS** a breaking change, but since the functionality would be available in another package, it is not such a terrible break. It would only be a matter of changing package requirements.

As for `websockets`, that is a great idea @Tronic. Let's take that discussion up in another location.

**Comment by ahopkins** [comment]
I did this already before the LTS, adding to 21.3 milestone to do another sweep before we close this.
