### ISSUE TITLE
SegFault using multi workers in Kubernetes

### ISSUE THREAD

**Issue by ZeJ0hn** [sanic-org/sanic#1912]
**Describe the bug**
We use a sanic in a container on kubernetes. Number of workers = 5
And this segmentation fault append very often :
```
Fatal Python error: Segmentation fault

Thread 0x00007fabd10ed740 (most recent call first):
File "/usr/local/lib/python3.8/site-packages/sanic/server.py", line 907 in serve
File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108 in run
File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315 in _bootstrap
File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 75 in _launch
File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 19 in __init__
File "/usr/local/lib/python3.8/multiprocessing/context.py", line 277 in _Popen
File "/usr/local/lib/python3.8/multiprocessing/process.py", line 121 in start
File "/usr/local/lib/python3.8/site-packages/sanic/server.py", line 1071 in serve_multiple
File "/usr/local/lib/python3.8/site-packages/sanic/app.py", line 1130 in run
File "app.py", line 1038 in <module>
```

**Environment (please complete the following information):**
- Docker image: python:latest
 - Version 20.6.3

**Comment by ahopkins** [comment]
I would not suggest running multiple workers in this case. Let Kubernetes do the horizontal scaling. That is what it is meant for.

**Comment by ahopkins** [comment]
What version of k8s? What are the specs of your nodes?

**Comment by ZeJ0hn** [comment]
Thank you for your answer.
I run my container on GKE with a version `1.15.12-gke.9`
Machine types are `n1-standard-4` for GCP. So it's :
- 4 cores
- 15 Go of memory

And my container has these limits and requests:
> resources:
>             limits:
>               cpu: "2500m"
>               memory: "8000Mi"
>             requests:
>               cpu: "2000m"
>               memory: "7500Mi"

I didn't have this issue with gunicorn and the same number of workers.

Do you think it should be better to use 1 worker and more replicas ? (with less ressources per pods)

**Comment by ahopkins** [comment]
There is a bit of a difference in how gunicorn handles multiprocessing and how Sanic does it. I would not suggest exceeding the number of CPUs you have available.

**Comment by WoodyFleurant** [comment]
I face a similar issue (segfault), even if I define 2 workers on 2 CPUs node

**Comment by ahopkins** [comment]
k8s replicas, or multiple Sanic workers in a single container on a single pod?

Also, what kind of `executor` are you running it in? Once you start doing that you need to be careful more closely with your memory usage.

My recommendation is keep 1 instance to 1 pod, and let k8s handle the scaling.

**Comment by WoodyFleurant** [comment]
> k8s replicas, or multiple Sanic workers in a single container on a single pod?
> 
> Also, what kind of `executor` are you running it in? Once you start doing that you need to be careful more closely with your memory usage.
> 
> My recommendation is keep 1 instance to 1 pod, and let k8s handle the scaling.

Having multiples workers in a single pod that define only one container.
ThreadPoolExecutor triggers the SegFault
