### ISSUE TITLE
Deprecated : sanic/docs/sanic/asyncio_python37.rst

### ISSUE THREAD

**Issue by nitipit** [sanic-org/sanic#1929]
**Describe the bug**
`sanic/docs/sanic/asyncio_python37.rst` is deprecate since there's an example at https://sanic.readthedocs.io/en/latest/sanic/examples.html

**Expected behavior**
Just remove the file : `sanic/docs/sanic/asyncio_python37.rst`

**Comment by ahopkins** [comment]
Willing to submit a PR for this?

**Comment by nitipit** [comment]
nitipit:nitipit-patch-1

**Comment by ahopkins** [comment]
Closing as the legacy docs are going away.
