### ISSUE TITLE
In some cases, I need to get the raw request header

### ISSUE THREAD

**Issue by L018** [sanic-org/sanic#1963]
Hi,

I find that all request's headers had do a casefold transform.  I know that's right. But I think we should keep save raw headers instead of drop it. I haven't find any property or function to get it yet. In web security, I need to find something from the raw request that is not the same as the real human request.

I know we can add a raw_headers property to solve it. But i think you have a better idea.

**Comment by ahopkins** [comment]
This is something I was toying with the idea of adding into the `streaming` branch that will be merged in early 2021. Currently it reads to a buffer and then drains. The thought was to add a raw HTTP request object to store a cache of the bytes received on the request object. There might be some memory concerns here, so I do not think it should be enabled by default. But there are some uses for this.

This would be the entire object. As for just the raw headers? That is also worth consideration. But, again this would likely be an opt-in feature.

**Comment by L018** [comment]
Yes, it is shouldn't be enabled by default. But I think request.body maybe a bit repetitive if we use a raw HTTP request object.

**Comment by ashleysommer** [comment]
I think we could at least cache the raw versions of the HTTP header. It should be small enough to always fit into memory.
