### ISSUE TITLE
20.12.0 causes the parallel unittest fails with 'app ... already in use' 

### ISSUE THREAD

**Issue by atezerjani** [sanic-org/sanic#1989]
After updating to the latest sanic 20.12.0, my pytest tests are failing with following error: 
`sanic.exceptions.SanicException: Sanic app name 'xxxxxx' already in use.`

I reverted back to 20.9.0, and the issue was fixed. What has changed in the recent version that has caused this issue to happen?

**Comment by ahopkins** [comment]
The simplest way to fix this would be to give each of the apps in your test a unique name. Newest build adds a feature where the instance is stored in an internal class registry for later retrieval:

```
Sanic.get_app("my_app")
```

We should probably add a patch that will disable this feature. It should be available both as a config:

```
SANIC_REGISTER=false
```

and on the instance itself

```
Sanic(..., register=False)
```

**Comment by atezerjani** [comment]
Thanks a lot @ahopkins for your prompt response.

**Comment by ahopkins** [comment]
https://github.com/huge-success/sanic/pull/1993/files

**Comment by ahopkins** [comment]
v20.12.1 will have this feature.

**Comment by CheneyZeng** [comment]
Let let us know if this issue fixed! Thanks, team!

**Comment by ahopkins** [comment]
Yes.

In your `conftest.py`:

```python
Sanic.test_mode = True
```

Or, set an env variable in your test suite: `SANIC_REGISTER=False`

I will be releasing [`sanic-test`](https://github.com/sanic-org/sanic-test) incoming days that will handle this automatically.

**Comment by riderx** [comment]
Thanks @ahopkins worked for my issue

**Comment by ashleysommer** [comment]
@ahopkins When do you expect `sanic-test` to be released? I have a project using Sanic 20.12 that I need to write some tests for, and ideally I'd like to use sanic-test to do that.

**Comment by ahopkins** [comment]
I was planning on doing that tonight, but didn't quite get to it. I am shooting for an initial release tomorrow, and getting #1850 ready to merge to `master`.

**Comment by ahopkins** [comment]
released. Changes to come, but it's out there.
