### ISSUE TITLE
App instance attribute with in-flight count

### ISSUE THREAD

**Issue by npodonnell** [sanic-org/sanic#1992]
**Is your feature request related to a problem? Please describe.**

A slow-running request is not allowed time to complete when I call `app.stop()`

**Describe the solution you'd like**

Please keep a counter of in-flight requests and don't stop the app until requests are actually complete, with optional timeout.

e.g.

```
app.stop() # stops accepting new requests but waits until in-flight requests are complete.
app.stop(timeout=30) # same as above but only waits 30 seconds before disconnecting.
app.stop(timeout=0) # don't wait, just close everything - what app.stop() currently does.
```

**Additional context**

This example code demonstrates the issue. The server runs for 30 seconds before stopping. Requests to `/` route take 20 seconds. If the request is made before 10s, it will complete just fine. If it's made after 10s, the TCP session terminates without sending any data.

```
from sanic import Sanic
from sanic.response import json
import asyncio

app = Sanic("my app")


@app.route('/')
async def test(request):
    await asyncio.sleep(20)
    return json({'hello': 'world'})

if __name__ == '__main__':
    server = app.create_server(host="0.0.0.0", port=8000, return_asyncio_server=True)
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    asyncio.ensure_future(server)

    for _ in range(10):
        print("App is running")
        loop.run_until_complete(asyncio.sleep(3))

    print("App stopping...")
    app.stop()
    loop.run_forever()
    print("App stopped")

```

Also nice to have would be an accessor to the number of in-flight requests - something like `app.inflight_count()`

Please let me know if I'm missing something. This is a cool framework.

Many thanks !

**Comment by ahopkins** [comment]
This certainly is an interesting idea. As for the `app.stop()`, that makes sense. But, one concern with the inflight counter on demand is that it would naturally be limited to the single process and not all requests across multiple workers.

**Comment by ahopkins** [comment]
For the record, this is a functionality (graceful shutdown) that already exists in Sanic.

**Comment by npodonnell** [comment]
> For the record, this is a functionality (graceful shutdown) that already exists in Sanic

I managed to fix the problem with an elaborate setup involving middlewares and an atomic integer to count the requests. 

FWIW I think graceful shutdown should be the default. In a production scenario, this is always desirable.

**Comment by ahopkins** [comment]
It is the default. Using `create_server` is **NOT** default, and comes with a DIY requirement.

The best (safest) way to run Sanic is with:

```python
app.run()
```

**Comment by ahopkins** [comment]
On `master`, you can access this:

```python
@app.route("/")
async def handler(request):
    num = len(request.transport.get_protocol().connections)
    return text(f"Number connections: {num}")
```

**Comment by npodonnell** [comment]
Thank you, that's very useful.
