### ISSUE TITLE
request.args and request.form values as is not list data type

### ISSUE THREAD

**Issue by sugizo** [sanic-org/sanic#1997]
# Is your feature request related to a problem? 
**background**
insert or update database from cli must convert first
**e.g.**
```
def dict_values(raw_ori):
    processed_raw = {}
    for i in raw_ori.items():
        if len(i[1] ) > 1:
            processed_raw[i[0] ] = i[1]
        else:
            for j in i[1]:
                processed_raw[i[0] ] = j
    return processed_raw

@app.route('/api/post/<tablename>', methods = ['POST'] )
def post(request, tablename):
    if request.args:
        values = dict_values(request.args)
    elif request.form:
        values = dict_values(request.form)
    row = db[tablename].validate_and_insert(**values)
    db.commit()
    return response.json(row.as_dict() )
```

**request.args**
`curl -X POST -d "name=name4&strings=4" -i http://localhost:8000/api/post/instrument`
**request.form**
`curl -X POST -d '{"name": "name5", "strings": 5}' -i http://localhost:8000/api/post/instrument`

**result without calling dict_values() function, the value data type list, will return an error when insert or update database**
```
request.args = {'name' : ['name3'], 'strings' : ['3'] }
request.form = {'name' : ['name4'], 'strings' : ['4'] }
```

**expected result, solve by calling dict_values() function**
```
request.args = {'name' : 'name3', 'strings' : '3'}
request.form = {'name' : 'name4', 'strings' : '4'}
```

# Describe the solution you'd like
insert or update database from cli as is data (values not list data type) from request.args and request.form
**e.g.**
```
@app.route('/api/post/<tablename>', methods = ['POST'] )
def post(request, tablename):
    if request.args:
        values = request.args
    elif request.form:
        values = request.form
    row = db[tablename].validate_and_insert(**values)
    db.commit()
    return response.json(row.as_dict() )
```

# Additional context
**question**
is it possible to have request.args and request.form values as is not list data type ?
so that can insert or update database without calling dict_values() function

thanks

**Comment by ahopkins** [comment]
Take a look at the notes here about `request.args`, `request.form`, and `request.files`. This is an intentional design decision to be compliant with HTML standards.

https://sanicframework.org/guide/basics/request.html#arguments

**Comment by ahopkins** [comment]
If you need to have it as a dictionary with a single value, here is a simpler snippet. But, I caution you to understand that this might mean you miss out on some if the key is overloaded.

```python
>>> q = {'key1': ['val1', 'val3'], 'key2': ['val2']}
>>> {k: v[0] for k, v in q.items()}
{'key1': 'val1', 'key2': 'val2'}
>>> 
```
