### ISSUE TITLE
RuntimeWarning: coroutine 'Server.wait_closed' was never awaited

### ISSUE THREAD

**Issue by riderx** [sanic-org/sanic#2004]
**Describe the bug**
With python 3.9.1 i got this issue when i run test or exit the server:
```
tests/test_runner.py::test_init
  /usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py:667: RuntimeWarning: coroutine 'Server.wait_closed' was never awaited
    self._ready.clear()
```

**Expected behavior**
The server should close proprely 

you can check the code there : 
https://github.com/jupyter-naas/naas
and the issue on the CI : 
https://github.com/jupyter-naas/naas/runs/1696392246?check_suite_focus=true

**Environment (please complete the following information):**
 - OS: mac osx 11.0.1
 - python 3.9.1
 -sanic : sanic>=20,<21
 - pytest-sanic>=1,<2

**Additional context**

**Comment by ahopkins** [comment]
Server details? Version?

**Comment by riderx** [comment]
Hey @ahopkins thanks for your rapid feedback i updated !
the best way to check it is on our CI ( we are open source )
https://github.com/jupyter-naas/naas/runs/1696392246?check_suite_focus=true

**Comment by sjsadowski** [comment]
@riderx Looks like the test is being run with python 3.8.4 and ubuntu 18.04 LTS - this contradicts the above info; can you just clarify so we're not chasing herrings?

**Comment by ahopkins** [comment]
The error I saw in your tests was this:

```
E           sanic.exceptions.SanicException: Sanic app name "naas.runner.runner" already in use.
```

[See this](https://github.com/sanic-org/sanic/issues/1989#issuecomment-755908371)

**Comment by riderx** [comment]
Guys thanks a lot 
```
Sanic.test_mode = True
```
fixed my issue  ! <3
