### ISSUE TITLE
getlist fails to decode all items with some characters

### ISSUE THREAD

**Issue by ahankinson** [sanic-org/sanic#2019]
**Describe the bug**
When passing in a value with semicolons, getlist will stop decoding the incoming parameters and return only the first item.

**Code snippet**
`app.py`

```python
from sanic import Sanic, request, response

app = Sanic("test-args")

@app.route("/")
def main(req) -> response.HTTPResponse:
    print(req.args.getlist("fq"))
    return response.html("hello world")

if __name__ == "__main__":
    app.run(debug=True, access_log=True)
```

Run the server with `$ python app.py`

Issue a request in a browser:

`http://localhost:8000/?fq="foo; bar; baz"`

**Expected behavior**
In the console, I would expect to see `["foo; bar; baz"]`. Instead I see `['"foo']`. (**NB** the opening quote mark is decoded, but not the closing one!)

**Environment (please complete the following information):**
 - OS: macOS (server & client
 - Version: 20.12.1

**Additional context**
The same behaviour is observed when using `req.args.get("fq")` as well.

**Comment by ahankinson** [comment]
After a bit of digging, I can also report that this is the behaviour of `urllib.parse.parse_qs`:

```
In [1]: import urllib.parse

In [2]: f = "fq='foo; bar; baz'"

In [3]: urllib.parse.parse_qs(f)
Out[3]: {'fq': ["'foo"]}
```

So it's not necessarily a bug within Sanic. However, given that I have received non-urlencoded values from my browser, and that Sanic doesn't seem to have a way to intercept the parsing of these values so that we can ensure they are urlencoded, I'm not sure where the problem (or the solution!) lies.

**Comment by ahopkins** [comment]
Thanks for digging. I will also check this in the new router branch. But as its in urllib, I suspect the same.

**Comment by ahopkins** [comment]
I do not think this is an issue with Sanic. You are passing unencoded characters in the URL and this is expected behavior. 

See [RFC 2.2](https://tools.ietf.org/html/rfc1738#section-2.2)

> Thus, only alphanumerics, the special characters "$-_.+!*'(),", and
   reserved characters used for their reserved purposes may be used
   unencoded within a URL.

When you pass the properly encoded version, it works as expected: 

```
localhost:9999/?fq=%22foo%3B%20bar%3B%20baz%22
```

```
['"foo; bar; baz"']
[2021-02-21 15:18:23 +0200] - (sanic.access)[INFO][127.0.0.1:36544]: GET http://localhost:9999/?fq=%22foo%3B%20bar%3B%20baz%22  200 11
```

**Comment by ahankinson** [comment]
Just to finally follow-up on this. I found what I was looking for here: 

https://sanic.readthedocs.io/en/latest/sanic/request_data.html#changing-the-default-parsing-rules-of-the-queryset

Setting `strict_parsing` to `True` will raise an exception on improperly-encoded values, which means they can be caught and handled gracefully. (Helpful if you're writing an API server where you want to return a `400` error for poorly-encoded requests!)
