### ISSUE TITLE
ServiceUnavailable when using url parameters and load balancer

### ISSUE THREAD

**Issue by HaithamMaya** [sanic-org/sanic#2022]
**Describe the bug**
When I call an endpoint that uses url parameters locally, I get the expected behavior. When I run it behind a load balancer (AWS ALB), I get a 504 Gateway Timeout Error because of sanic giving a `ServiceUnavailable: Response Timeout` error. 

```bash
curl http://loadbalancer/test
OK

curl http://loadbalancer/test/7b49c158-a3da-4d35-96f6-58e1260d849e
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
```
logs
```bash
[INFO]  []: GET http://0.0.0.0:8000/test 200 2 0.04ms
ServiceUnavailable: Response Timeout
```

**Code snippet**
Relevant source code, make sure to remove what is not necessary.
```python
class Test(HTTPMethodView):
    @staticmethod
    async def get(request):
        return text('OK')

class TestWithId(HTTPMethodView):
    @staticmethod
    async def get(request, test_id):
        return text(f'OK {test_id}')

app.add_route(uri='/test', methods=['GET'], handler=Test.as_view())
app.add_route(uri='/test/<test_id:uuid>', methods=['GET'], handler=TestWithId.as_view())
```

**Expected behavior**
```bash
curl http://0.0.0.0:1234/test
OK

curl http://0.0.0.0:1234/test/7b49c158-a3da-4d35-96f6-58e1260d849e
OK 7b49c158-a3da-4d35-96f6-58e1260d849e
```

**Environment (please complete the following information):**
```docker
FROM python:3.9.1-slim
RUN pip install -U pip
RUN pip install sanic==20.12.1
```

**Additional context**
This occurred when I upgraded to python 3.9 and sanic 20.12.

I get the expected behavior when running in the following environment:
```docker
FROM python:3.7.8-slim
RUN pip install -U pip
RUN pip install sanic==19.12.2
```

**Comment by HaithamMaya** [comment]
After further investigation, this only occurs when the type is assigned:
Times out:
```
app.add_route(uri='/test/<test_id:uuid>', methods=['GET'], handler=TestWithId.as_view())
```
Removing `:uuid` and it works as expected

```
app.add_route(uri='/test/<test_id>', methods=['GET'], handler=TestWithId.as_view())
```

**Comment by ahopkins** [comment]
This is indeed quite unusual.

Safe to say that this is your basic app:

```python
from uuid import UUID

from sanic import Sanic
from sanic.response import text
from sanic.views import HTTPMethodView

app = Sanic("app")


class TestWithId(HTTPMethodView):
    def get(self, request, test_id: UUID):
        return text(str(test_id))


app.add_route(TestWithId.as_view(), "/test/<test_id:uuid>")
```

**Comment by artcg** [comment]
Looks like AWS ALB transforms request headers to lower case 

https://stackoverflow.com/questions/39871250/aws-application-load-balancer-transforms-all-headers-to-lower-case

While sanic router checks the request header to see how to route it (from 20.12.1)
```python
request.path, request.method, request.headers.get("Host", "")
```

The newest (unreleased) version of sanic uses the request headers in lower case

```python
        return self._get(
            request.path, request.method, request.headers.get("host")
        )
```

So I would recommend to try the latest version `pip install git+https://github.com/sanic-org/sanic.git`

**Comment by artcg** [comment]
Ah looks like actually sanic Header is case insensitive for .get so it couldn't be that, in that case I am stumped,

but still good to try with the latest version since the router has a lot of significant changes since then...

**Comment by ahopkins** [comment]
@artcg correct, even in v20.12 getting headers is case-insensitive.

---

I was about to ask about perhaps how AWS is sending this along. That you mentioned it is related to the type being present, it sounds like perhaps this might be an issue with the regex matching.

Perhaps AWS is escaping the `-` characters?

I would suggest adding a middleware that logs out `request.path` to see what you are receiving. Also, as mentioned the version that was just released has some big changes to routing. I am curious to know if that happens here too.
