### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic#2023]
Both [sanic-routing](https://github.com/sanic-org/sanic-router) and [sanic-testing](https://github.com/sanic-org/sanic-testing) are now using GitHub Actions for running the test suite and also handling deployments. It has proved itself super simple, convenient, and (most importantly) responsive/speedy.

I suggest we move over the CI from Travis to GH.

**Comment by sjsadowski** [comment]
I'm not a fan of actions, but I see the value in reducing our external tool dependencies.

**Comment by ahopkins** [comment]
Do you have any particular complaints about it? Travis has been incredibly slow since they moved us from `.org` to `.com`.

**Comment by sjsadowski** [comment]
Actually not for a public project; my issues with actions have all been around disabling public actions in private project (which basically when I tried, broke everything) - I'm perfectly fine with moving the build process to be contained in Actions.
