### ISSUE TITLE
Versioning in the Blueprint Group

### ISSUE THREAD

**Issue by SaidBySolo** [sanic-org/sanic#2045]
**Is your feature request related to a problem? Please describe.**
I use sanic to make api, and I am using it.

Currently, the url is managed through a blueprint group, if use single blueprints can be versioned, but blueprints cannot be versioned in the case of a group.

If versioning is possible, maintenance will be much more convenient.

**Describe the solution you'd like**
Can use versioning in the blueprint group.

**Additional context**
```py
Blueprint.group(example_blueprint, example_blueprint_two, url_prefix="api", version="v1")
```

**Comment by ahopkins** [comment]
Great idea. If someone doesn't best me to it, I'll get a PR on this weekend.

**Comment by ahopkins** [comment]
While we are at it, we should probably also carry thru `strict_slashes`.
