### ISSUE TITLE
Sanic is not compatible with an existing event loop

### ISSUE THREAD

**Issue by CaptainDestructo** [sanic-org/sanic#2046]
When started as part of a larger project, Sanic wants to create its own event loop. This fails when there is already an active event loop.

```
on_ready
Starting WebManager...
[2021-03-05 22:17:09 +0000] [2515] [INFO] Goin' Fast @ http://0.0.0.0:80
[2021-03-05 22:17:09 +0000] [2515] [ERROR] Unable to start server
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sanic/server.py", line 891, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1450, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1443, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 484, in uvloop.loop.Loop._run
RuntimeError: Cannot run the event loop while another loop is running
[2021-03-05 22:17:09 +0000] [2515] [INFO] Server Stopped
Starting SQL Manager...
```

As part of good practice, Sanic should first perform a check to determine whether or not an event loop has already been created, and if found, utilize the appropriate commands to use the existing event loop. Look into `nest_asyncio` for nesting loop commands.

**Environment:**
 - OS: Ubuntu + Python 3.8.5
 - Current pip version as of March 5 2021

**Additional context**
I distinctly remember having to fix this problem with another module, but don't remember how I fixed it. Otherwise I would make a PR for the fix.

**Comment by sjsadowski** [comment]
I disagree. It's not sanic's responsibility to be situationally aware.

A good option is to use the create_server() method and attach it to an existing loop, if necessary.

Example, presupposing the event loop is "your_existing_event_loop"
```python
    server = app.create_server(host="0.0.0.0", port=8000, return_asyncio_server=True)
    asyncio.set_event_loop(your_existing_event_loop)
    asyncio.ensure_future(server)
```

@sanic-org/sanic-core-devs please weigh in here.

**Comment by CaptainDestructo** [comment]
@sjsadowski This is essentially what I ended up doing. I suck at reading documentation, so it took me a minute to dig through the code to find the solution.

```
class WebManager:
    def __init__(self, bot):

        self.bot = bot

    @classmethod
    async def start(cls, bot, host="0.0.0.0", port=8080):

        instance = cls(bot)
        instance.app = app
        instance.host = host
        instance.port = port
        await app.create_server(host=host, port=port, return_asyncio_server=True)
```

**Comment by ahopkins** [comment]
I agree. It is not best practice to run Sanic this way. But, for the more savvy developer able to weigh the decisions, `create_server` is exposed. Before the next release, the new docs will have a much more detailed section on making the decision, the consequences, etc.

**Comment by delfick** [comment]
Is there a preview of that documentation?

As far as I can work out it'd be something like this (but with some more polish)

```
server = create_server(.....)

await server.start_serving()
await server.after_start()
loop.create_task(server.serve_forever())

try:
  await stop_condition
except:
  pass

await server.before_stop()
await server.close()
await close_connections()
await server.after_stop()
```

Where I'd have to write close_connections myself and looks like this (semi pseudo code from the serve function sanic provides)

```
def close_connections():
  for connection in connections:
      connection.close_if_idle()
  
  while connections and hasnt_been_grace_seconds_yet():
      await asyncio.sleep(a_bit)
  
  coros = []
  for conn in connections:
      if hasattr(conn, "websocket") and conn.websocket:
          coros.append(conn.websocket.close_connection())
      else:
          conn.close()
  
  await gather(coros)
```
