### ISSUE TITLE
Universal JSON encoder change

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic#2054]
By default, Sanic uses `ujson` for serializing JSON data.

This can be changed by _not_ installing it in your environment. Or, you can change it in the response:

```python
from json import dumps

json({"foo": "bar"}, dumps=dumps)
```

But, this means that you would need to change it everywhere or monkeypatch if you want to change the default encoder, but still have `ujson` available in your environment. :unamused: 

---

Proposal to add:

```python
Sanic(..., dumps=dumps)
```

**Comment by sjsadowski** [comment]
I somehow thought we were already doing this. I'm on board.
