### ISSUE TITLE
RFC: Change default branch to main

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic#2056]
There is a general movement in open source to move away from `master`, and rename it `main`. [GitHub has done this](https://github.com/github/renaming) and is making it the default for new repos. This should not be a problem as any existing links out in the wild [will be redirected by GH](https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/).

[Read about why](https://sfconservancy.org/news/2020/jun/23/gitbranchname/)

@sanic-org/core-devs  and anyone else, thoughts? Comments?

**Comment by seemethere** [comment]
I think it sounds like a good idea, we should create a `main` branch on the main repository that just mirrors the `master` branch to check to see if any of our CI processes break from the transition.

As well, there should probably be some sort of look into projects that might be affected by this transition.

But overall it’s a 👍🏽 from me

**Comment by ahopkins** [comment]
GitHub has some tooling in place to automatically handle and update a lot of this for us.

Closing as complete.
