### ISSUE TITLE
New style streaming route handler improvements

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic#2067]
**Is your feature request related to a problem? Please describe.**
The new streaming API allows streaming responses in the route handler without having to use a callback:

```python
@app.route("/")
async def test(request):
    response = await request.respond(content_type="text/csv")
    await response.send("foo,")
    await response.send("bar")
    await response.send("", True)
    return response
```

**Describe the solution you'd like**
A simpler method to closing the stream before returning in place of `await response.send("", True)`

```python
await response.eof()
```

Under the hood, `eof` should simply just be a convenience call to `send("", True)`.

**Comment by ajay1mg** [comment]
this should work in `sanic -> response -> BaseHTTPResponse`, right?
```
    async def eof(self):
        await self.send("", True)
```

@ahopkins

**Comment by ahopkins** [comment]
Yup. Eventuall, we probably can merge `HTTPResponse` right into `BaseHTTPResponse`. Until we do that, the `eof()`  should be in the same place as `send()` since it would simply be a shortcut.

**Comment by ahopkins** [comment]
@ajay1mg Are you working on a PR for this?

If yes, then add a check for `self.streaming_fn` inside `eof()`. If it exists, that we should raise an exception since `eof` should only ever be called when there is no `streaming_fn`

**Comment by ajay1mg** [comment]
I am working on the PR for this but I am confused with your second comment. `HttpResponse` class doesn't have any attribute  `streaming_fn` nor does `BaseHTTPResponse`

**Comment by ahopkins** [comment]
Sorry for not being clear. This is what I meant:

```python
class StreamingHTTPResponse(BaseHTTPResponse):
    def eof(...):
        raise NotImplementedError
```

**Comment by ajaygupta2790** [comment]
I have added the PR for this from my personal account. didn't realize I was using my org account
https://github.com/sanic-org/sanic/pull/2094

Please let me know if there is anything that need to be added.

**Comment by ahopkins** [comment]
> Please let me know if there is anything that need to be added.

Did you see my message about trying to add some tests?
