### ISSUE TITLE
deprecate CompositionView ? 

### ISSUE THREAD

**Issue by artcg** [sanic-org/sanic#2069]
Currently sanic offers a class called `CompositionView`

I really am struggling to find any utility in this class, since 

```python
from sanic.views import CompositionView

def get_handler(request):
    return text("I am a get method")

view = CompositionView()
view.add(["GET"], get_handler)
view.add(["POST", "PUT"], lambda request: text("I am a post/put method"))

# Use the new view to handle requests to the base URL
app.add_route(view, "/")
```

Seems much more confusing to me than

```python
def get_handler(request):
    return text("I am a get method")

app.route("/", methods=["GET"])(get_handler)
app.route("/", methods=["POST", "PUT"])(lambda request: text("I am a post/put method"))
```

Can anyone offer a compelling use case for CompositionView?

If not, I would suggest to deprecate it 

https://github.com/sanic-org/sanic/blob/master/sanic/views.py

**Comment by artcg** [comment]
For HTTPMethodView I can somehow see the utility since everything is defined within the class so you can have class methods that are common to the request types, but for CompositionView where you don't implement a subclass that value is lost

**Comment by ahopkins** [comment]
Only have time to leave a quick note. I'll respond with some thoughts more fully later this weekend. 

CompositionView is a PITA to support.

**Comment by ashleysommer** [comment]
I think this is another one of those features that's been in Sanic from the start, and its stayed around for a long time, and its only still there because "its always been that way".
I was looking back trough some code history and it looks like CompositionView was implemented initially as a quick and easy way do something like a MethodView class. But real MethodViews were added not long after, and seems like CompositionView should be deprecated.

**Comment by ahopkins** [comment]
Thanks @ashleysommer for taking a look through that. I agree that this is a good example of another feature that Sanic has probably outgrown.

I agree with deprecation notice from 21.6 and removal in 21.12.

**Comment by artcg** [comment]
At the same time as this change, it could be an idea to provide HTTPMethodView with a method like

```python
def attach_routes_to_app(self, app, route_prefix):
    # probably completely wrong syntax I am just making this up 
    for method, handler in self.methods.items():
         app.route(handler, method, route_prefix)
```

And then in the future requiring people to use

`view.attach_routes_to_app(app, "/example")`

instead of 

`app.add_route(view.as_view(), "/example")`

Would take care of the maintenance frustration @ahopkins mentioned, which also carries forward to sanic plugins/ addons like e.g. sanic-openapi

**Comment by ahopkins** [comment]
Not a bad idea. I am generally a fan, however, to use concise method names inside the framework where possible. It helps people from having to refer back to the documentation so much (of course type annotations will help). I would suggest just `attach(...)`.

```python
def attach(self, instance: Union[Sanic, Blueprint], url_prefix: str):
```
