### ISSUE TITLE
Sanic WebSockets not working in ASGI mode with daphne as a server

### ISSUE THREAD

**Issue by sim1234** [sanic-org/sanic#2070]
Sanic WebSockets not working in ASGI mode with daphne as a server

Backend code:
```
from sanic import Sanic

app = Sanic("bug")


@app.websocket("/ws/")
async def handler(request, ws):
    await ws.accept()
    while True:
        data = "Hello"
        print("Sending:", data)
        await ws.send(data)
        data = await ws.recv()
        print("Received: ", data)

```
Ran with `daphne -e tcp:80:interface=0.0.0.0 bug:app`

Frontend code:
```
socket = new WebSocket("ws://localhost:80/ws/", []);

socket.onopen = function(e) {
  console.log("Sending to server");
  socket.send("My name is John");
};

socket.onmessage = function(event) {
  console.log(`[message] Data received from server: ${event.data}`);
};

socket.onclose = function(event) {
  if (event.wasClean) {
    console.log(`[close] Connection closed cleanly, code=${event.code} reason=${event.reason}`);
  } else {
    // e.g. server process killed or network down
    // event.code is usually 1006 in this case
    console.log('[close] Connection died');
  }
};

socket.onerror = function(error) {
  console.log(`[error] ${error.message}`);
};
ƒ (error) {
  console.log(`[error] ${error.message}`);
}
```

Expected behavior is for the sockets to connect and exchange messages.

Observed behavior is that the backend crashes with `AttributeError: 'WebSocketProtocol' object has no attribute 'handshake_deferred'`. 

Removing the `await ws.accept()` line causes backend to crash with `ValueError: Socket has not been accepted, so cannot send over it`.

Switching the order of send and recv prevents the crash, but no messages are received nor sent.

In all cases frontend disconects with message `[close] Connection died`.

OS: Win10
sanic==20.12.2
daphne==3.0.1

**Comment by sim1234** [comment]
I've reported the same bug in daphne since I can't determine whose fault it is. https://github.com/django/daphne/issues/360

**Comment by sjsadowski** [comment]
I set up your test as above, eliminating the await and running directly as a sanic app with app.run()

Sanic App:
```
pipenv run python test.py
[2021-03-21 08:03:44 -0500] [4076543] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2021-03-21 08:03:44 -0500] [4076543] [INFO] Starting worker [4076543]
Sending: Hello
Received:  My name is John
Sending: Hello
```

DevTools:
```
Sending to server
2(index):11 [message] Data received from server: Hello
(index):16 [close] Connection closed cleanly, code=1000 reason=
```

I tested with uvicorn and it looks like this may be a problem with the ASGI response
```
[2021-03-21 08:09:51 -0500] [4086237] [ERROR] Exception occurred while handling uri: 'ws://localhost:8000/ws'
Traceback (most recent call last):
  File "/opt/ssadowski/.local/share/virtualenvs/2070-fKWZDJFT/lib/python3.8/site-packages/sanic/app.py", line 729, in handle_request
    response = request.stream.response  # type: ignore
AttributeError: 'ASGIApp' object has no attribute 'response'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/ssadowski/.local/share/virtualenvs/2070-fKWZDJFT/lib/python3.8/site-packages/sanic/app.py", line 729, in handle_request
    response = request.stream.response  # type: ignore
AttributeError: 'ASGIApp' object has no attribute 'response'
```

**Comment by ahopkins** [comment]
@sjsadowski This might be an issue with 21.3, but the original ticket says 20.12 so we might have two different things going on here.

**Comment by sjsadowski** [comment]
above was 21.3, below is 20.12.3 w/ uvicorn:

sanic:
```
$ pipenv run uvicorn --host 127.0.0.1 --port 8000 test:app
INFO:     Started server process [4132344]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 57078) - "WebSocket /ws" [accepted]
Sending: Hello
Received:  None
Sending: Hello
```
browser:
```
WebSocket connection to 'ws://localhost:8000/ws' failed: 
(anonymous) @ (index):3
(index):25 [error] undefined
(index):20 [close] Connection died
```

**Comment by ZinkLu** [comment]
Hi!

I tested uvicorn, hypercorn and daphne. 

# environments

1. hardware:
	
    MacBook Pro (13-inch, M1, 2020) 

2. Python:
	
    3.9

3. PythonPackage:
	- Sanic==21.3.2
	- sanic-routing==0.4.0
	- uvicorn==0.13.4
	- Hypercorn==0.11.2
	- daphne==3.0.1
	- websockets==8.1
	- wsproto==1.0.0

# before test

1. shut subprotocol down in webockets

	seems in asgi mode, websockets `subprotocol` is not well-supported. So I did a little change before test.

	```python
	# sanic.websocket.WebSocketConnection

	    async def accept(self) -> None:
	        await self._send(
	            {
	                "type": "websocket.accept",
	                # "subprotocol": ",".join(list(self.subprotocols)),
	            }
	        )
	```

	`subprotocol` causes broken in `uvicorn + wsproto` and `hypercorn` and `dephne`.


2. Comment out the following code

    ```python
    # app.py line 726
                if response:
                    response = await request.respond(response)
                # else:
                #     response = request.stream.response  # type: ignore
    ```

    When sending a websocket request. a exception raised: `AttributeError: 'ASGIApp' object has no attribute 'response'`. looks like `request.stream == sanic.asgi.ASGIApp()` in ASGI mode, AGSI object doesn't have response attribute. 

    these code may cause exceptions. 

# conclusion

## uvicorn 

uvicorn uses webcokets and wsproto as it's implements of websocket protocol, So:

1. uvicorn + websockets: Broken, can't establish websocket connection. (didn't find any solution yet, uvicorn can't get along this version of websockets). 
   
2. uvicorn + wsproto: works fine. 

## dephne

1. All routes are broken(both http and ws) 

    traceback shown:

    ```sh
    File ".../python3.9/site-packages/sanic_routing/router.py", line 63, in resolve
        route, param_basket = self.find_route(
    TypeError: 'NoneType' object is not callable
    ```

    Seems `sanic-routeing` `finalize()` is never called. after set a breakpoint in `Sanic.__call__()`, after call `finalize()` manually in pdb, router works.

    should check signals event when using dephne.

## hypercorn

1. works fine.

**Comment by ahopkins** [comment]
@ZinkLu This is awesome work. Thanks you so much.

**Comment by ZinkLu** [comment]
Glad to help. If there is anything I can PR, let me know.

**Comment by ahopkins** [comment]
There were a few things going on here. All fairly minor changes. With this change, I was able to run the example with uvicorn, hypercorn, and daphne.

The one thing to note is that daphne does not seem to respond properly to the lifespan events. Therefore the listeners do not execute. I have a vague recollection of this from a year or two ago. Anyhow, by manually running the router finalizer, it runs in daphne as well:

```python
from sanic import Sanic

app = Sanic("bug")


@app.websocket("/")
async def handler(request, ws):
    while True:
        data = "Hello"
        print("Sending:", data)
        await ws.send(data)
        data = await ws.recv()
        print("Received: ", data)


app.router.finalize()
```
