### ISSUE TITLE
RFC: Temporary config value overrides

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic#2082]
Often times you may need to change a config value for a particular duration, or perhaps for a single route handler. There should be a simple API to manage that.

```python
with app.config.override(RESPONSE_TIMEOUT=99999):
    do_something()

# or

app.route("/", config_override={"RESPONSE_TIMEOUT":99999 })(...)
```

A similar approach [can be found here](https://sanic-jwt.readthedocs.io/en/latest/pages/configuration.html#temporary-override).

**Comment by Tronic** [comment]
One thing to consider is whether the config should stay immutable after the app has started (and if changes later are ignored or work in unexpected ways, not to mention that they only affect the current worker). Even with that consideration, using a `with` block for any overrides is reasonable because it keeps them well scoped.

**Comment by ChihweiLHBird** [comment]
I am interested in implementing this feature, and currently thinking about it. 

What do you guys think about apply config override to class based view? In the class scope or method scope?

https://sanicframework.org/en/guide/advanced/class-based-views.html

**Comment by ChihweiLHBird** [comment]
If class scope, we can consider put the `override_config` in add_route`'s parameters list.

**Comment by ahopkins** [comment]
> If class scope, we can consider put the `override_config` in add_route`'s parameters list.

In my initial example above, putting it in `app.route` would necessarily make it part of `app.add_route`. So, the answer is yes there.


> I am interested in implementing this feature, and currently thinking about it.

Awesome! Go for it :tada: 


> What do you guys think about apply config override to class based view? In the class scope or method scope?

I think it has to be within the method only. Handlers are not necessarily class instance methods. 

Likely the best way to tackle this (IMO) is to cache the config override on the route object. Then, inside `Sanic.handle_request` implement the same context manager approach. The problem of course is how to avoid this operation in the 99% of cases where we do not need to override.

Therefore, IMO I think the best _FIRST_ course of action is to simply create the context manager and worry about adding it to the route definition at a later time.

Let's figure out how to make this work:

```python
with app.config.override(RESPONSE_TIMEOUT=99999):
    do_something()
```

**Comment by ChihweiLHBird** [comment]
> Let's figure out how to make this work:
> 
> ```python
> with app.config.override(RESPONSE_TIMEOUT=99999):
>     do_something()
> ```

Thank you, Adam! In my understanding, `do_something()` can be defining a route, am I correct? Like:

```python
with app.config.override(RESPONSE_TIMEOUT=99999):
    @app.get("/test1")
    async def something_handler(request):
        return text("test1")
```

**Comment by ahopkins** [comment]
@ChihweiLHBird 

Well, really what I meant was the other way around, but I realize now that simply will not work:

```python
@app.get("/test1")
async def something_handler(request):
    with app.config.override(RESPONSE_TIMEOUT=99999):
        return text("test1")
```

**Comment by ahopkins** [comment]
One more thought on this... After the 21.12 release, @Tronic and I have been discussing the need to overhaul all of the timeouts. In which case I am somewhat hesitant to do anything on this just yet. Maybe we should really wait so that we are not making it harder to implement a potential breaking change.

**Comment by ChihweiLHBird** [comment]
> One more thought on this... After the 21.12 release, @Tronic and I have been discussing the need to overhaul all of the timeouts. In which case I am somewhat hesitant to do anything on this just yet. Maybe we should really wait so that we are not making it harder to implement a potential breaking change.

No problem, let's wait util 21.12 released. 

> Are there other config values that make sense to set for a single use case? If not, maybe we need to narrow the scope here.

I couldn't think about some common use cases other than the timeout after checking the docs, https://sanicframework.org/en/guide/deployment/configuration.html#builtin-values
