### ISSUE TITLE
404 returned from endpoint when using regex in routes while registering more than 3 routes in some cases

### ISSUE THREAD

**Issue by damianj** [sanic-org/sanic#2090]
I have some code in which a route used a regular expression to catch any text in the URL after a certain point. After the 21.3 update this stopped working and kept returning a 404 (not found) error. After trying many things I noticed that if I changed the regex to string (i.e., doing `<foo:string>`) the route suddenly worked again (interestingly using `<foo:path>` also doesn't work). Also, if I limit the number of routes I register to 3 or less the route works with the original regex expression. Below is some code that reproduces this.

**Update:**
It seems the issue stems from the route being missing from the routing tree that is generated. I am not sure how the tree is generated, but it seems that something about the route `/foo/bar/<path_param:.*>` causes it to not be added.

```python
from sanic import Sanic
from sanic.response import json

app = Sanic(__name__)

@app.route('/foo/bar/<path_param:.*>', methods=["GET", "POST"])
async def foo_bar(request, path_param: str):
    return json({"path_param": path_param})

@app.route('/foo/lorep/<long_text:string>', methods=["GET", "POST"])
async def foo_lorep(request, long_text: str):
    return json({"path_param": long_text})

@app.route('/another/foo/bar/<path_param:string>', methods=["GET", "POST"])
async def another_foo_bar(request, path_param: str):
    return json({"path_param": path_param})

@app.route('/another/foo/bar/lorep/<path_param:string>', methods=["GET", "POST"])
async def another_foo_bar_lorep(request, path_param: str):
    return json({"path_param": path_param})

@app.route('/some/route1/<some_text:string>', methods=["GET", "POST"])
async def some_route1(request, some_text: str):
    return json({"path_param": some_text})

@app.route('/some/route2/<some_text:string>', methods=["GET", "POST"])
async def some_route2(request, some_text: str):
    return json({"path_param": some_text})

@app.route('/special/foo/bar/<path_param:string>', methods=["GET", "POST"])
async def special_foo_bar(request, path_param: str):
    return json({"path_param": path_param})

@app.get('/long/sub/route/param_a/<param_a:string>/param_b/<param_b:string>')
@app.post('/long/sub/route/')
async def long_sub_route(request, param_a: str, param_b: str):
    return json({"path_param": [param_a, param_b]})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=1234, debug=True)
```

Once the code above is running then navigating to `http://0.0.0.0:1234/foo/bar/123` should result in a `404`, but if you remove 5 routes (leaving only 3) the route will work **with** the regex. Alternatively, in the first route if `<input_text:.*>` is changed to `<input_text:string>` it will also work but this is not the ideal solution as I would like to be able to use regex in the routes.

**Environment:**
 - OS: Arch
 - Version: 
   - Sanic: 21.3.2
   - Sanic-Routing: 0.5.0

**Comment by ahopkins** [comment]
Why should `http://0.0.0.0:1234/foo/bar/123` be a 404?

I just tested these routes against the 0.5.1 branch (https://github.com/sanic-org/sanic-routing/pull/21), and it seems that these routes all work as expected. The only thing is:

```python
@app.get('/long/sub/route/param_a/<param_a:string>/param_b/<param_b:string>')
@app.post('/long/sub/route/')
```

While route overloading is okay and supported, there is an issue that the routes do not produce the same parameters and therefore the function is missing required arguments.

**Comment by damianj** [comment]
Apologies, I didn't mean to say that the expected behavior was a 404, but that the sample code above produced a 404 (when it should not). I am still on sanic-routing 0.5.0, so I'll test this out once 0.5.1 is available on PyPi

**Comment by ahopkins** [comment]
Ahh.... sorry that I misunderstood. I think then that the ordering of regular expressions by their length (according to the number of path parts delimited by `/`) should resolve your problem then. This is one of the main changes of `0.5.1`. The other is that it pre-compiles the regular expressions for faster execution when evaluating.
