### ISSUE TITLE
Flaky Tests

### ISSUE THREAD

**Issue by harshanarayana** [sanic-org/sanic#2092]
**Describe the bug**
There are a series of tests in our code base which seem to be behaving in a bit of a flaky manner on regular basic. This has been one of the main reason we have seen so many random Travis CI failures while running tests. 

Currently, the main one seem to be isolated to `py39-no-ext`

While enabling GitHub Actions for the repo using #2050 I noticed that there are a few more flaky tests and the behavior is a little more prominent and visible when you extend your test matrix to include `macos-latest` or `windows-latest`

It would be nice if we can audit these tests and fix some of them or mark them aptly as `@pytest.mark.xfail` with Proper conditional selector to make sure we don't run into random PR patchest failures on regular basis

**Code snippet**
NA

**Expected behavior**
Lesser Flaky Tests

**Environment (please complete the following information):**
NA

**Additional context**
Check the PR commit history for #2050. You will notice a series of failures of tests and most of those are flaky test failures that work on retires or shows up randomly.

**Comment by ahopkins** [comment]
It seems to always get stuck (if it will get stuck) on this:

```
$ tox -e py39-no-ext -- tests/test_signal_handlers.py
```

But, I cannot recreate this locally.

**Comment by harshanarayana** [comment]
@ahopkins  Yeah. I haven't had any success either. Tried on my Personal mac as well as the Ubuntu machines we use at work. Can't recreate at will but the pipeline seem to get stuck in this loop way more than I would like it to.
