### ISSUE TITLE
ASGI routes with body not extracted from the request

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic#2101]
[See source](https://github.com/sanic-org/sanic/blob/824f41d6e06006076725d7be0140ebb4381440ff/sanic/asgi.py#L169)

This bug only applies to ASGI when sending.

When sending a body to a request on ASGI, the body is not making it through. I have not yet tested if this also applies with streaming requests.

The problem is here:

```python
    async def read(self) -> Optional[bytes]:
        """
        Read and stream the body in chunks from an incoming ASGI message.
        """
        message = await self.transport.receive()
        if not message.get("more_body", False):
            self.request_body = False
            return None         # <<<< we are not returning the body
        return message.get("body", b"")
```

If a small message comes through that has not hit this `read()` more than once (again, I am assuming that a streaming request might actually work), the message will look like this:

```python
message = await self.transport.receive()
# message={'type': 'http.request', 'body': b'{"foo": "bar"}', 'more_body': False}
```

Therefore, we need to return the `body` even if `more_body` is `False` (and also properly set `self.request_body`.

More testing is needed

**Comment by ashleysommer** [comment]
Your analysis makes sense to me.
