### ISSUE TITLE
Config.load_env type should explicitly allow strings

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic#2102]
https://github.com/sanic-org/sanic/blob/main/sanic/config.py#L44

```python
        if load_env:
            prefix = SANIC_PREFIX if load_env is True else load_env
```

`load_env` defaults to `True`, but you can pass a string if you want a different prefix. We should make this type consistent by either explicitly accepting both a `bool` and ` `str`, or (perhaps a more elegant solution) is just to ONLY accept a string and default it to `SANIC_PREFIX` since this is what it is trying to do.

**Comment by jdraymon** [comment]
Ha ... should have glanced at issues before I started. Will add the reference to #2107
