### ISSUE TITLE
Request body is not automatically loaded

### ISSUE THREAD

**Issue by Tronic** [sanic-org/sanic#2103]
I had to manually call `req.receive_body()` to have `req.body` and others filled in, in a *non-streaming* handler. Isn't `streaming=False` still the default? Let me know if I missed something obvious changed in 21.3, otherwise I'll debug more tomorrow.

**Comment by ahopkins** [comment]
ASGI? See #2101

If not, what is the route definition? Which http method?

**Comment by Tronic** [comment]
I've triaged this to `route.ctx.ignore_body` being `True`, causing sanic/app.py:686 to skip body preloading altogether. It's hard to produce a simple test case because the bug disappears whenever taken outside of my live app.

**Comment by Tronic** [comment]
I'm running as module with `app.run()` in `__main__.py`.

**Comment by Tronic** [comment]
The offending handler but as stated, copy&pasting into another app makes the bug disappear. I'm not familiar with router internals so this is probably one for @ahopkins to look at.

```python
@app.put("/")
@app.put("/p/")
@app.put("/p/<paste_id>", name="put_paste")
async def put_paste(req, paste_id=None):
    # here req.body=b'' req.stream.request_body=True req.ctx.ignore_body=True
```

**Comment by Tronic** [comment]
Hah, found it!

```python
@app.put("/")
@app.put("/p/")
@app.put("/p/<paste_id>", name="put_paste")
async def put_paste(req, paste_id=None):
    # here req.body=b'' req.stream.request_body=True req.route.ctx.ignore_body=True

@app.delete("/p/<paste_id>", name="delete")
async def delete_paste(req, paste_id):
    return empty()
```

Here the DELETE route, with same pattern as the PUT route causes `ignore_body=True` to be set on the other route as well. I would expect different methods on the same pattern not to get mixed up but apparently they do.

**Comment by ahopkins** [comment]
> I've triaged this to `route.ctx.ignore_body` being `True`, causing sanic/app.py:686 to skip body preloading altogether. It's hard to produce a simple test case because the bug disappears whenever taken outside of my live app.

So, this was going to be my next question. But, it should never be `True` with a `put`. Then again, maybe something weird is happening with the overloading.

Just curious, if you add `ignore_body=False` manually into the route definition does this go away?

**Comment by ahopkins** [comment]
> Here the DELETE route, with same pattern as the PUT route causes `ignore_body=True` to be set on the other route as well. I would expect different methods on the same pattern not to get mixed up but apparently they do.

Yup. That makes sense...

Hmm.... This needs a bug fix. In the meantime, setting `ignore_body=False` in the `delete` route should fix the problem.

**Comment by ahopkins** [comment]
Will be solved by this: https://github.com/sanic-org/sanic-routing/issues/23

**Comment by ahopkins** [comment]
This issue has been mentioned on **Sanic Community Discussion**. There might be relevant details there:

https://community.sanicframework.org/t/how-to-get-parameter-from-post-request/836/2
