### ISSUE TITLE
Invalid response when closing websocket connection using Socket.IO

### ISSUE THREAD

**Issue by ENT8R** [sanic-org/sanic#2105]
I'm experiencing an issue when using [python-socketio](https://github.com/miguelgrinberg/python-socketio) together with Sanic. Assuming the Socket.IO connection has been upgraded to a pure websocket connection (instead of long polling) and this connection is closed after some time, the underlying request handler returns `None`.
Now, as `None` is obviously no instance of `BaseHTTPResponse` and the handler which was called before is a function without the attribute `handler.is_websocket`, Sanic raises a `ServerError` with `Invalid response type None (need HTTPResponse)`
https://github.com/sanic-org/sanic/blob/ad97cac31393477380ee421281d6356e604353d4/sanic/app.py#L730-L740
I already opened an issue in the library which handles this request: https://github.com/miguelgrinberg/python-engineio/issues/221
but maybe this is something that Sanic should take care of when initializing websocket handlers from other libraries?

**Comment by ahopkins** [comment]
Hmm, I am not sure that we should try and support this. Sanic has websocket support already. The efforts within that function are highly balanced between functionality and performance. This is not a place to be messing around adding additional code.

With that said, I am working on the signals implementation which also has the ability to rebuild certain functionality of the application. It might be possible using this new feature to accomplish this. I realize it does not help you right now. Perhaps if you need it now then you can copy the function and monkeypatch it for your need.

**Comment by ENT8R** [comment]
Understandable, though it is likely easier to monkeypatch the `is_websocket` attribute instead of the whole request handling function. Looking forward to the improvements regarding signals, sounds great!

**Comment by seanmkauffman** [comment]
Please see https://github.com/miguelgrinberg/python-engineio/issues/221#issuecomment-838116903 which explains the problem.  I don't know if the web browser will be likely to reuse the same TCP connection when changing protocols, but the problem is that the socketio protocol expects to be able to access the same resource using either http or ws.
