### ISSUE TITLE
request.args.pop removes parameters inconsistently

### ISSUE THREAD

**Issue by artcg** [sanic-org/sanic#2106]
Environment : 20.12.3, presumably other environments too

Code to reproduce:

send this request to this app
`GET http://localhost:8000/?hello=a&world=4`
```python
from sanic import Sanic


app = Sanic('test')

@app.get('/')
def _(request):
    a = request.args.pop('hello')
    b = request.args.pop('world')
    c = request.args.pop('world')
    d = request.args.pop('world')   << crashes here

app.run()
```

Expected:
crashes at line second call of .pop('world'), or not at all

**Comment by artcg** [comment]
I have no ideas about this since the RequestParameters seems to be a really straightforward wrapper around the `dict`, would be interested if anyone can reproduce it ...

**Comment by artcg** [comment]
Started to look at this a bit more it seems that the problem is not with the implementation of RequestParameters but rather with this somewhere

`    args = property(get_args)`

vs 18.12 where it still works as expected

```
    @property
    def args(self):
        if self.parsed_args is None:
            if self.query_string:
                self.parsed_args = RequestParameters(
                    parse_qs(self.query_string)
                )
            else:
                self.parsed_args = RequestParameters()
        return self.parsed_args
```

**Comment by artcg** [comment]
Ah I worked it out!

Because parsed_args is a defaultdict, once the request.args is exhausted, it will evaluate as False again, and then a fresh parsing of the query will occur.

**Comment by sjsadowski** [comment]
Reopening until merge is complete
