### ISSUE TITLE
Allow an alternate configuration class or object to be passed to application objects

### ISSUE THREAD

**Issue by Varriount** [sanic-org/sanic#2115]
It is currently difficult to extend the `Config` class, and have an `Sanic` instance actually use that configuration class throughout its entire lifecycle. This is because the `Sanic` class's `__init__` method is hard-coded to use `sanic.config.Config`. Anyone wishing to use a different class must do one of:
  - Patch and replace `sanic.config.Config`.
  - Re-implement `Sanic.__init__` in a sub-class, duplicating most of the base implementation.
  - Assign a different value to `Sanic.config`.

The first solution is inelegant, and hard to do correctly, the second involves redundant code duplication, and the third means that users are only able to introduce custom behavior post-init.

A simple fix for this is to modify `Sanic.__init__` to allow passing in a custom configuration class. This is already done for the class used to represent requests, and users can also pass in custom router and error handler instances.

**Comment by ahopkins** [comment]
This was on my list of simple changes to add. Same thing for the context and object.
