### ISSUE TITLE
Route match broken in Sanic v21.3 

### ISSUE THREAD

**Issue by zwjat** [sanic-org/sanic#2123]
When I upgrade sanic from  20.9.0 to v21.3, the following route worked well in  20.9.0 broken in v21.3。

```python
from sanic import Sanic
from sanic.response import text

app = Sanic("app")

@app.get("/")
async def hw(request):
    return text("Hello, world.")

@app.get("/test/<at>.html")
async def at(request, at):
    return text(at)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=9000, debug=True)
```

The route 
```python
"/test/<at>.html"
``` 
not works in v21.3 with 404 http status code. I guess that route match algorithm in v21.3 changes dramatically.

As a result, I uninstall v21.3 and reintsall 20.9.0. Is there any way to solve this problem as this project can't change to adapt v21.3?  Thanks a lot.

@ahopkins

**Comment by zwjat** [comment]
I found the solution [here](https://community.sanicframework.org/t/route-definition-with-extension-that-is-text-after-v-path-var-declaration-fails-in-21-but-works-in-20/829).

Thanks.

**Comment by ahopkins** [comment]
For reference, I think the solution you were looking for is:

```python
app.route("/test/<a:(?P<a>\w+)\.html>")
```
