### ISSUE TITLE
It's impossible to pass headers with `redirect()`

### ISSUE THREAD

**Issue by kunansy** [sanic-org/sanic#2124]
I have this code run:
![](https://sun9-63.userapi.com/impg/6Svm3xAIhqUavzvhYwo0iB1e49CWyZ5AQBoP8g/mHfHkQA1yCc.jpg?size=843x346&quality=96&sign=a4326fe2db9b52147541442caccc66f3&type=album)

Then I send the request:
![](https://sun9-27.userapi.com/impg/0aX9nn25V_BPtBWAvZZEP9OrEAe58ydFM-QY5w/18pRzW9OO8k.jpg?size=1085x213&quality=96&sign=9913497de6cba047177473463c564a77&type=album)

And there are **no headers** I've passed:
![](https://sun9-3.userapi.com/impg/EyeIN_rzpXXiVIR2EZx0vOmtgdTUaYagDkh0Mg/x7-cIgGaydY.jpg?size=1777x168&quality=96&sign=27ddcd3bdadd7a8cfa521c77a3a97ad0&type=album)

**Environment:**
 - OS: Pop!_OS
 - Version 20.10

**Additional context**
I use the last `sanic` version.
![](https://sun1-88.userapi.com/impg/9Eu9qxQcYlo6-S6yw9Dx_9NRCtB3jhPAbNolgA/TgxYllUd8SE.jpg?size=461x172&quality=96&sign=76762e3a60244b08f4987f93fe2d6ff0&type=album)

**Comment by Tronic** [comment]
The client makes another (GET) request after the redirect, and you are reading the headers of that GET, not the ones returned with the redirect itself. Try POSTing with `curl -v` and you'll see that header you are sending.

**Comment by kunansy** [comment]
Do you mean I can't get pass headers with redirect() to GET handler?
I see them in curl results but they do no exist in GET handler.

**Comment by kunansy** [comment]
Oh, I have a mistake. I didn't see the header in curl results
![](https://sun9-14.userapi.com/impg/T3mAfkhV4oTnY_X54okhOpnAz14yMUE-MqSa_Q/H3d8FUOoPhI.jpg?size=559x374&quality=96&sign=af1365c55c9ee09703f4b07e1f299fe6&type=album)

**Comment by Tronic** [comment]
```python
@app.get("/foo")
def foo_get(req):
    return text("OK")

@app.post("/foo")
def foo_post(req):
    return redirect("/foo", headers={"x-Testing": "Redirect response header from Sanic"})
```

```
$ curl -vL http://127.0.0.1:8000/foo -d field=value
*   Trying 127.0.0.1:8000...
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> POST /foo HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.76.0-DEV
> Accept: */*
> Content-Length: 11
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< x-Testing: Redirect response header from Sanic
< Location: /foo
< content-length: 0
< connection: keep-alive
< content-type: text/html; charset=utf-8
< 
* Connection #0 to host 127.0.0.1 left intact
* Issue another request to this URL: 'http://127.0.0.1:8000/foo'
* Switch from POST to GET
* Found bundle for host 127.0.0.1: 0x7fd230422f60 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#0) with host 127.0.0.1
* Connected to 127.0.0.1 (127.0.0.1) port 8000 (#0)
> GET /foo HTTP/1.1
> Host: 127.0.0.1:8000
> User-Agent: curl/7.76.0-DEV
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 2
< connection: keep-alive
< content-type: text/plain; charset=utf-8
< 
* Connection #0 to host 127.0.0.1 left intact
OK
```

**Comment by sjsadowski** [comment]
To clarify what @Tronic is trying to illustrate: Server headers returned to a request are not automatically passed back to the server again by the client when the redirect happens as client headers.

**Comment by kunansy** [comment]
@sjsadowski ok, thanks. But then, how to pass headers with redirect? Is there a way to do it?

I mean, `redirect()` has this param, then it should somehow give them. But it doesn't.

**Comment by Tronic** [comment]
You need to set a cookie, add URL parameters or use some other means to pass this information. The client makes a completely new request and won't pass any data otherwise.

Another alternative is to just call your other function within Sanic, directly responding to the original POST request and avoiding any redirect on client side (no GET request will occur at all).

**Comment by kunansy** [comment]
Thanks

**Comment by ahopkins** [comment]
It sounds like you might want a proxy endpoint and not a redirect. This way, you can control the headers that make it to the next "hop" and then return the response on the original endpoint.
