### ISSUE TITLE
Add routing possibility to handle multiple format through Accept header

### ISSUE THREAD

**Issue by klausmyrseth** [sanic-org/sanic#2126]
**Is your feature request related to a problem? Please describe.**
Today when I try make a well rounded best practice rest api, I miss a feature for multiple formats/languages and charsets for same visible path through the Accept header, Accept-Language and Accept-Charset

**Describe the solution you'd like**
I would like to have a header filter possibility for route definitions like GET where you can list header-filter='Accept:application/json' header-filter='Accept-Language:US' header-filter='Accept-Charset:utf-8' with one or several, this can be extended to other headerbased values.

**Additional context**
Some api versioning use headers through appllication extension mimetype to indicate versions there, so this should be taken into consideration aswell. I for me prefer versions in path, but Sanic should take both methods into account.

**Comment by sjsadowski** [comment]
You can do this with middleware already.

**Comment by ahopkins** [comment]
This is what one of the reasons we rebuilt the router: greater flexibility (and performance) to be able to do routing based upon headers, cookies, etc.

**Comment by klausmyrseth** [comment]
Ok cant see how I can do that with middleware, we have to do it in the handler now where code feels much like old visual basic design. We have 99% of the endpoints always return json of a particular domain format, while 1% needs multi format support. If I had a generic multi format rendrer I could do it in the middleware while now I have to do it in the handler as I see it.

**Comment by sjsadowski** [comment]
Can you provide a code snippet of what's happening now so we can better understand the difficulty?

**Comment by Tronic** [comment]
> You can do this with middleware already.

https://github.com/sanic-org/sanic/issues/1667#issuecomment-527806221

This allows reformatting plain Python dict into JSON. Adapt the middleware to check the `accept` header and return different types as needed.

**Comment by klausmyrseth** [comment]
No its only in 2 endpoints out of 300 we need this, its not a middleware issue, no worries well do it in spagethi python in thadler until we fine a better solution

**Comment by ahopkins** [comment]
Even if you can provide a snippet of pseudo-code we can help give suggestions. 🤷‍♂️
