### ISSUE TITLE
`RouteExists` thrown when registering a directory and a missing file to the same route.

### ISSUE THREAD

**Issue by sunset-developer** [sanic-org/sanic#2132]
**Describe the bug**
When registering a route to a file and a directory, if the file doesn't exist a `sanic_routing.exceptions.RouteExists` error is raised. This may be misleading and unintended.

**Code snippet**

`example.html` does not exist in this example. The directory  `./resources/web` does.

```python
app.static('/', './resources/web')
app.static('/', './resources/web/example.html')
```

**Expected behavior**
Currently, if a non existent file is registered to a route, no error is thrown on startup and any attempt to retrieve registered resource raises a `FileNotFoundError: [Errno 2] No such file or directory` and a `404 Not Found` error is displayed in the browser. Instead of this happening, as mentioned before a `sanic_routing.exceptions.RouteExists` is raised on startup which may be misleading and unintended.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS

**Comment by ahopkins** [comment]
This is not really a bug, and is an intended outcome. Sanic is checking to see if a file like that exists. If not, it thinks you are trying to serve from a directory. Just by looking at the path, there is no way to determine if you intend to serve a file or a directory.

I think this is the correct behavior. If anything, perhaps what you really want is an explicit method to control this:

```python
app.static('/', './resources/web', as="dir")
app.static('/', './resources/web/example.html', as="file")
```

With an explicit kwarg, we would not need to run `path.isfile`. This is not really new behavior. If Sanic 20.12 is not functioning this way, I think that is more a problem on the earlier version than with the current.
