### ISSUE TITLE
TypeError in pytest_sanic.utils.TestClient.start_server

### ISSUE THREAD

**Issue by ergoproxxxy** [sanic-org/sanic#2134]
**Describe the bug**
I have TypeError (serve() got an unexpected keyword argument 'main_start') in pytest_sanic.utils.TestClient.start_server.
I use this versions: pytest-sanic==1.7.0 and sanic==21.3.4.

**Code snippet**
```
../../.local/lib/python3.8/site-packages/pytest_sanic/utils.py:224: in start_server
    await self._server.start_server()
../../.local/lib/python3.8/site-packages/pytest_sanic/utils.py:107: in start_server
    self.server = await serve(**server_settings)
E   TypeError: serve() got an unexpected keyword argument 'main_start'
```
My workaround:
```
@pytest.fixture(scope="session")
def sanic_client_fixup():
    async def serve_mocked(**server_settings):
        server_settings.pop("main_start", None)
        server_settings.pop("main_stop", None)
        return await serve(**server_settings)

    with patch("pytest_sanic.utils.serve", MagicMock(side_effect=serve_mocked)):
        yield
```

**Expected behavior**
pytest_sanic.utils.TestClient.start_server works without Exception and fixture above.

**Environment (please complete the following information):**
 - OS: Debian
 - Version 10.7

**Additional context**
None

**Comment by ahopkins** [comment]
This looks like a problem with the `pytest-sanic` plugin. It looks to me like it is not compatible with recent lifecycle additions in v21.3.

I would suggest raising the ticket there.

Most likely the solution would be a simple inclusion of something like the following before Line 107 of `utils.py`:

```python
server_settings.pop("main_start")
server_settings.pop("main_stop")
```

If it were up to me, and I was building that, I would also execute those lifecycle events. But, that is a decision for the developers of `pytest-sanic`.

Closing this here, as this is not the appropriate channel for this issue.

**Comment by ahopkins** [comment]
PS - that is a nice workaround thanks for sharing. :muscle:
