### ISSUE TITLE
Allow later websockets releases

### ISSUE THREAD

**Issue by fabaff** [sanic-org/sanic#2142]
**Describe the bug**
`websockets` is [pinned](https://github.com/sanic-org/sanic/blob/main/setup.py#L91
). The latest `websockets` is 9.1 and this release is fixing a [authentication vulnerability](https://websockets.readthedocs.io/en/stable/changelog.html) which was introduced with 8.0.

**Expected behavior**
Allow to use `websockets>9`

**Environment (please complete the following information):**
 - OS: probably all
 - Version: current

**Additional context**
n/a

**Comment by ahopkins** [comment]
Working on an implementation in #2000 that would resolve this.

**Comment by aaugustin** [comment]
Sanic isn't affected by the security vulnerability:

https://github.com/sanic-org/sanic/search?q=BasicAuthWebSocketServerProtocol
https://github.com/sanic-org/sanic/search?q=basic_auth_protocol_factory

Only downside of sticking with the old version: you'll get issues like this one.

Let me see if I can offer a PR to bump the dependency.
