### ISSUE TITLE
Auto reload resource files in the a Sanic app

### ISSUE THREAD

**Issue by erickguan** [sanic-org/sanic#2143]
**Is your feature request related to a problem? Please describe.**
When a Sanic app is in production, I use different configs for development, staging, and production. I use 3 YAML files to implement that. However, they are not tracked by auto_reload in the development environment. I would be happy to be able to see Sanic can restart when I change the config.

**Describe the solution you'd like**
It can be a helper API to register resources for auto_reload. importlib provides a semantic method [`importlib.resources.read_text`](https://docs.python.org/3/library/importlib.html#importlib.resources.read_text). It does no more than read(<file>, 'r'). It might be nice to hook with readers from importlib.

**Additional context**
Example app structure:
```
awesomeapp
| - config
   | - development.yaml
   | - staging.yaml
   | - production.yaml
| app.py
| __init__.py
```

Potential API signature:
`sanic.resources.read_text(package, resource, encoding='utf-8', errors='strict')`

**Comment by ahopkins** [comment]
Can you explain to me the thought process on the `read_text`?

It seems like what you are really looking for is a way to tell sanic to reload for anything in `./config`.

**Comment by erickguan** [comment]
You are right about this. Your solution is much simpler!

**Comment by ahopkins** [comment]
@erickguan I am really glad that you suggested this. It is something that I think I have thought in my head many times would be really helpful to have.
