### ISSUE TITLE
get_app() function unable to get app object in blueprint

### ISSUE THREAD

**Issue by jakehu** [sanic-org/sanic#2152]
The files and directories are as follows
`/path/server.py`
```python
from sanic import Sanic
from sanic.response import text
from api.user import user

app = Sanic('jakehu')
app.blueprint(user)

app.run(debug=True,auto_reload=True)
```

`/path/api/user.py`
```python
from sanic import Sanic
from sanic.response import json
from sanic import Blueprint

app = Sanic.get_app('jakehu')

user = Blueprint("user")

@user.route("/user/list")
async def userList(request):
    return json({"user": "blueprint"})
```

I get the following error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sanic/app.py", line 1267, in get_app
    return cls._app_registry[name]
KeyError: 'jakehu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server.py", line 3, in <module>
    from api.user import user
  File "/Users/jakehu/Documents/Web/python-sanic-test/api/user.py", line 5, in <module>
    app = Sanic.get_app('jakehu')
  File "/usr/local/lib/python3.7/site-packages/sanic/app.py", line 1271, in get_app
    raise SanicException(f'Sanic app name "{name}" not found.')
sanic.exceptions.SanicException: Sanic app name "jakehu" not found.
```

**Comment by ZinkLu** [comment]
```python
from sanic import Sanic
from sanic.response import text

app = Sanic('jakehu')

from api.user import user
app.blueprint(user)

if __name__ == "__main__":
    app.run(debug=True, auto_reload=True)
```

This should solve the problems, `get_app()` only works when Sanic instance has been created.

If you don't like imports in the middle of you codes. try https://sanicframework.org/en/guide/how-to/autodiscovery.html should help.

**Comment by ahopkins** [comment]
The problem is that you are importing the Blueprint before there is an app. 

This line:

```python
from api.user import user
```

comes before this line:

```python
app = Sanic.get_app('jakehu')
```

So, you need to try and reverse them somehow. One option is to just push up your app instantiation:

```python
from sanic import Sanic
from sanic.response import text

app = Sanic('jakehu')

from api.user import user

app.blueprint(user)
app.run(debug=True,auto_reload=True)
```

Another might be to use a solution [like this](https://sanicframework.org/en/guide/how-to/autodiscovery.html), where the import is done using the `importlib`.

```python
from sanic import Sanic
from utility import autodiscover

app = Sanic("auto", register=True)
autodiscover(
    app,
    "api.user"
)
```

Personally, I am a fan of doing something like this:

```python
# factory.py
from typing import Optional, Sequence
from sanic import Sanic


from .autodiscovery import autodiscover

DEFAULT_BLUEPRINTS = [
    "path.to.blueprint",
]


def create_app(
    init_blueprints: Optional[Sequence[str]] = None,
) -> Sanic:
    app = Sanic("MyApp")

    if not init_blueprints:
        init_blueprints = DEFAULT_BLUEPRINTS

    autodiscover(app, *init_blueprints)

    return app
```

```python
# server.py
from factory import create_app
from sanic.log import logger

app = create_app()
```

This has the benefit of giving you flexibility for your test suite.

---

Out of curiosity, what are you trying to achieve that you need access to the `app` instance inside your `blueprint`?

**Comment by jakehu** [comment]
> ```python
> from sanic import Sanic
> from sanic.response import text
> 
> app = Sanic('jakehu')
> 
> from api.user import user
> app.blueprint(user)
> 
> if __name__ == "__main__":
>     app.run(debug=True, auto_reload=True)
> ```
> 
> This should solve the problems, `get_app()` only works when Sanic instance has been created.
> 
> If you don't like imports in the middle of you codes. try https://sanicframework.org/en/guide/how-to/autodiscovery.html should help.

It turned out to be because of the order
Does the middleware and the decorator matter?

**Comment by jakehu** [comment]
> The problem is that you are importing the Blueprint before there is an app.
> 
> This line:
> 
> ```python
> from api.user import user
> ```
> 
> comes before this line:
> 
> ```python
> app = Sanic.get_app('jakehu')
> ```
> 
> So, you need to try and reverse them somehow. One option is to just push up your app instantiation:
> 
> ```python
> from sanic import Sanic
> from sanic.response import text
> 
> app = Sanic('jakehu')
> 
> from api.user import user
> 
> app.blueprint(user)
> app.run(debug=True,auto_reload=True)
> ```
> 
> Another might be to use a solution [like this](https://sanicframework.org/en/guide/how-to/autodiscovery.html), where the import is done using the `importlib`.
> 
> ```python
> from sanic import Sanic
> from utility import autodiscover
> 
> app = Sanic("auto", register=True)
> autodiscover(
>     app,
>     "api.user"
> )
> ```
> 
> Personally, I am a fan of doing something like this:
> 
> ```python
> # factory.py
> from typing import Optional, Sequence
> from sanic import Sanic
> 
> 
> from .autodiscovery import autodiscover
> 
> DEFAULT_BLUEPRINTS = [
>     "path.to.blueprint",
> ]
> 
> 
> def create_app(
>     init_blueprints: Optional[Sequence[str]] = None,
> ) -> Sanic:
>     app = Sanic("MyApp")
> 
>     if not init_blueprints:
>         init_blueprints = DEFAULT_BLUEPRINTS
> 
>     autodiscover(app, *init_blueprints)
> 
>     return app
> ```
> 
> ```python
> # server.py
> from factory import create_app
> from sanic.log import logger
> 
> app = create_app()
> ```
> 
> This has the benefit of giving you flexibility for your test suite.
> 
> Out of curiosity, what are you trying to achieve that you need access to the `app` instance inside your `blueprint`?

Need to use the database in the blueprint
`app.ctx.db`
Apart from this method, is there any other way to use `app.ctx` in the blueprint?

**Comment by ahopkins** [comment]
```python
@bp.route(...)
async def handler(request: Request):
    user = await request.app.ctx.db.get_user()
    ...
```

**Comment by jakehu** [comment]
> ```python
> @bp.route(...)
> async def handler(request: Request):
>     user = await request.app.ctx.db.get_user()
>     ...
> ```

Thank you very much, this solved my problem, but the document does not describe how to use the application context

**Comment by jakehu** [comment]
Finally, I can only find the corresponding code in `request.py`

``` app: Sanic,```

```
    def __init__(
        self,
        url_bytes: bytes,
        headers: Header,
        version: str,
        method: str,
        transport: TransportProtocol,
        app: Sanic,
        head: bytes = b"",
    ):
```

**Comment by ZinkLu** [comment]
> > ```python
> > from sanic import Sanic
> > from sanic.response import text
> > 
> > app = Sanic('jakehu')
> > 
> > from api.user import user
> > app.blueprint(user)
> > 
> > if __name__ == "__main__":
> >     app.run(debug=True, auto_reload=True)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This should solve the problems, `get_app()` only works when Sanic instance has been created.
> > If you don't like imports in the middle of you codes. try https://sanicframework.org/en/guide/how-to/autodiscovery.html should help.
> 
> It turned out to be because of the order
> Does the middleware and the decorator matter?

No, as long as the Sanic instance created.

**Comment by ahopkins** [comment]
@jakehu 

> Finally, I can only find the corresponding code in `request.py`

> Thank you very much, this solved my problem, but the document does not describe how to use the application context



Thanks for the feedback. You are :100: correct, we should really have something here: https://sanicframework.org/en/guide/basics/request.html 

and probably also here: 
https://sanicframework.org/en/guide/basics/app.html#application-context

**Comment by ZinkLu** [comment]
> > ```python
> > @bp.route(...)
> > async def handler(request: Request):
> >     user = await request.app.ctx.db.get_user()
> >     ...
> > ```
> 
> Thank you very much, this solved my problem, but the document does not describe how to use the application context

you can also use `request.ctx` to get a db connection, like `request.ctx.db_session.get_user()`. 
cause it seems db transaction is related to request.

(How do I use SQLAlchemy with Sanic?)[https://sanicframework.org/en/guide/how-to/sqlalchemy.html] section should help
