### ISSUE TITLE
Sanic 21.3+ not respecting RESPONSE_TIMEOUT

### ISSUE THREAD

**Issue by mikepurvis** [sanic-org/sanic#2161]
**Describe the bug**

Possibly related to https://github.com/sanic-org/sanic/issues/2078, but I have a non-websocket situation where I do a bunch of async work on the backend to fulfill a request, and so I set the timeouts accordingly:

```
app = sanic.Sanic(__name__)
app.config.KEEP_ALIVE = False
app.config.REQUEST_TIMEOUT = 5
app.config.RESPONSE_TIMEOUT = 300

...

@app.route("/get/expensive/thing")
async def get_thing():
    await expensive()
```

This worked fine on Sanic 20.12, but now it's timing out with a 503 after 60 seconds, as if the config is not even present. It looks like some stuff happened in https://github.com/sanic-org/sanic/pull/2007/commits/a2bff7434701c20f9ba69c664c532d1d16cedd9f, and [the doc page that used to reference how to set the config](https://sanic.readthedocs.io/en/v20.12.0/sanic/config.html) no longer exists.

**Expected behavior**

The timeout should not kick in until 300s have passed.

I can create a MWE for this if needed, but I assumed it's probably a either a bug that will be obvious to whoever introduced it, or an oversight on my part about how to set the config.

**Environment (please complete the following information):**

Ubuntu Focal, Python 3.8

**Comment by ahopkins** [comment]
I am taking a look. This has not come up in tests, and I have not run into this yet.

**Comment by ahopkins** [comment]
@mikepurvis What proxy is in front of Sanic?

**Comment by mikepurvis** [comment]
It's nginx, but the config on that side is unchanged from previously and the logs indicate that it's sanic that's giving up:

```
Jun 14 18:55:11 dev-vm-distro-01 colcon_distro_server[1081540]: [2021-06-14 18:55:11 +0000] - (sanic.access)[INFO][127.0.0.1:32788]: GET http://distro/favicon.ico  404 -1
Jun 14 18:55:11 dev-vm-distro-01 colcon_distro_server[1081540]: [2021-06-14 18:55:11 +0000] - (sanic.access)[INFO][127.0.0.1:60272]: GET http://distro/get/indigo/snapshot/2.20.0/20200903124907.json  503 -1
```

This is just an `app.run()` setup.

**Comment by ahopkins** [comment]
https://github.com/sanic-org/sanic/blob/v21.3.4/sanic/server.py#L242

```python
import asyncio

from sanic import Sanic
from sanic.response import text

app = Sanic("__BASE__")
app.config.RESPONSE_TIMEOUT = 5
app.config.FALLBACK_ERROR_FORMAT = "text"


@app.get("/okay")
async def okay(request):
    await asyncio.sleep(request.app.config.RESPONSE_TIMEOUT - 1)
    return text("Done.")


@app.get("/bad")
async def bad(request):
    await asyncio.sleep(request.app.config.RESPONSE_TIMEOUT + 1)
    return text("Done.")


if __name__ == "__main__":
    app.run(access_log=False, debug=True, port=7777)
```

```bash
╭─adam@_ ~  
╰─$ curl localhost:7777/okay -i                   
HTTP/1.1 200 OK
content-length: 5
connection: keep-alive
content-type: text/plain; charset=utf-8

Done.
╭─adam@_  ~  
╰─$ curl localhost:7777/bad -i 
HTTP/1.1 503 Service Unavailable
content-length: 82
connection: close
content-type: text/plain; charset=utf-8

⚠️ 503 — Service Unavailable
============================
Response Timeout



```

**Comment by ahopkins** [comment]
When is your `.json` timing out?

**Comment by ahopkins** [comment]
> It looks like some stuff happened in [a2bff74](https://github.com/sanic-org/sanic/commit/a2bff7434701c20f9ba69c664c532d1d16cedd9f), 

That commit only consolidates all the config loading methods into one. If you are setting config as shown above, there would not have been an impact.

> and [the doc page that used to reference how to set the config](https://sanic.readthedocs.io/en/v20.12.0/sanic/config.html) no longer exists.

Have you not seen the [user guide](https://sanicframework.org/en/guide/deployment/configuration.html#basics)?

**Comment by mikepurvis** [comment]
Thanks for looking into this promptly. I agree that a naive MWE on my end is not reproducing the issue. I'm digging into it further to understand more about why this is happening— it looks like it might only be happening in an environment with some stale dependencies, eg uvloop 0.14.0 instead of 0.15.2.

> Have you not seen the user guide?

I had not— that looks great! I was just going by the RTD page and what I could find from google. :)

**Comment by mikepurvis** [comment]
So the trivial repro also works fine even in the venv where my application is having an issue, but my application doesn't seem to have its issue in a fresh venv with everything up to date. So.... super weird.

In any case, going to close this for now as I don't think it's actionable on your side. Thanks again the quick support and for an excellent project. I'll reopen if I find something concrete.

**Comment by mikepurvis** [comment]
And your initial instinct was right— it _was_ nginx. This definitely was working previously so I have no idea what it was about the Sanic version bump that seemed to expose the problem, but adding `proxy_read_timeout` to the nginx configuration solves it!

**Comment by jeffdico** [comment]
@ahopkins please im having this same problem now. im using version 23.12.1. on my local ubuntu machine, everything works fine. on ubuntu cloud  server, it starts shoing response timeout error. Please help suggest what is wrong. 

![image](https://github.com/sanic-org/sanic/assets/17049877/5aaa32ea-c024-45b6-93a3-4bcf981c77a1)
