### ISSUE TITLE
Copy blueprints

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic#2163]
It would be really helpful if there was an API to duplicate a blueprint into a new blueprint. Something like this:

```python
v1 = Blueprint("Version1", version=1)

@v1.route("/something")
def something(request):
    ...

v2 = v1.copy(version=2)

app.blueprint(v1)
app.blueprint(v2)
```
```
/v1/something
/v2/something
```

**Comment by ChihweiLHBird** [comment]
Are `/v1` and `/v2` considered as a URL prefix for the blueprint?

**Comment by ahopkins** [comment]
No.

A blueprints uri is:

version_prefix + version + all url_prefix + path

A route has only a single version, but could have multiple url_prefix if it is nested.

What's the question behind your question?

**Comment by ChihweiLHBird** [comment]
@ahopkins Did we consider using `copy.deepcopy` API to copy the blueprint? If yes, why we decided not to use it?

Something like this works fine.
```
from sanic import Sanic, Blueprint, blueprints, response
from copy import deepcopy


bp = Blueprint("test", version=1)

bp2 = deepcopy(bp)
bp2.version = 2
bp2.name = "test2"


@bp.route("/html")
def handle_request(request):
    return response.html("<p>Hello world!</p>")


@bp2.route("/html")
def handle_request(request):
    return response.html("<p>Hello world!</p>")


app = Sanic(__name__)
app.blueprint(bp)
app.blueprint(bp2)

app.run()

```

**Comment by ChihweiLHBird** [comment]
@ahopkins Can we close this issue?
