### ISSUE TITLE
Enforce exception handler uniquness

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic#2166]
1. You should not be able to register the same exception more than once, or at least not on the same App/Blueprint.
2. Handlers should only be fetched in relation to the BP or App context of the matched route. This effectively means that some exceptions (`NotFound` could only be registered app level).

_Originally posted by @ahopkins in https://github.com/sanic-org/sanic/issues/2121#issuecomment-827077284_

**Comment by prryplatypus** [comment]
Hello!

Regarding point 2, there is currently useful usecases to register exceptions like `NotFound` at a BP level. For example, you may have an API blueprint where you want all responses to be returned as JSON; but want them to be returned as HTML everywhere else.

I believe currently it is possible to do this and, if I understand correctly, point 2 would remove the ability to do so.

**Comment by ahopkins** [comment]
I guess it could work if you _manually_ raised `NotFound`. But if the route does not exist, there is no way for Sanic to know which blueprint (and therefore which handler) to apply.

**Comment by prryplatypus** [comment]
What if the blueprint has a URL prefix? I'd expect the blueprint error handler to try handling any errors within that URL prefix, if no child handles them before. 🤔

**Comment by ahopkins** [comment]
That is not likely something we will introduce since it would require adding default routes to blueprint handlers as catch-all. Which would and could have some bizarre unintended (and difficult to debug) consequences.

Since `NotFound` could be raised manually in legit use cases, maybe we need to identify some (like this and `NoMethod`) that should raise a warning on BP registration.
