### ISSUE TITLE
sanic-openapi rest is slower than gevent+flask

### ISSUE THREAD

**Issue by snakecy** [sanic-org/sanic#2176]
**Describe the bug**

my test is for nlp task. after testing, the result is sanic-openapi is slower than gevent+flask.
why?

sanic-openapi rest
![image](https://user-images.githubusercontent.com/12490881/123780343-afa7b680-d905-11eb-9955-bc8f77e8d0c9.png)

the following is gevent+flask rest 
![image](https://user-images.githubusercontent.com/12490881/123780375-b7675b00-d905-11eb-825e-d52642e9f76a.png)

**Code snippet**
Relevant source code, make sure to remove what is not necessary.

**Expected behavior**

**Environment (please complete the following information):**
 - Version [e.g. 0.8.3]

**Additional context**

**Comment by ahopkins** [comment]
`sanic-openapi` issues should be posted to that project not here. Furthermore, I am not sure what this is even meant to show. There is no actionable item, methodology, code, or anything for anyone to even respond to.
