### ISSUE TITLE
Pending tasks on exit

### ISSUE THREAD

**Issue by DirtyHairy** [sanic-org/sanic#2189]
**Describe the bug**
Sanic does not wait for the `connection_task()` tasks to terminate after cleaning up non-idle connections after `GRACEFUL_SHUTDOWN_TIMEOUT`. This can cause dangling tasks on exit:

```
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<HttpProtocol.connection_task() done, defined at /Users/pestix/.virtualenvs/server-25sdMkop/lib/python3.9/site-packages/sanic/server.py:188> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x108263fa0>()]>>
```

**Code snippet**
I can reproduce this reliably by running a simple server with a SSL context and doing the same dance as in #2186 in Chrome. The surplus connection opened by Chrome will be terminated after `GRACEFUL_SHUTDOWN_TIMEOUT` expires, and I get the above warning.

**Expected behavior**
Clean exit.

**Environment (please complete the following information):**
 - OS: MacOS
 - Version: 21.6.0

**Additional context**
A possible workaround on the consumer side is

```
    @app.listener("after_server_stop")
    async def afterServerStop(app, loop):
        await asyncio.gather(*[task for task in asyncio.all_tasks() if task != asyncio.current_task()])
```

However, this exposes #2190 😛

**Comment by ahopkins** [comment]
Resolved in #2231
