### ISSUE TITLE
Websocket handler ignores user exceptions

### ISSUE THREAD

**Issue by aha79** [sanic-org/sanic#2192]
When a websocket handler throws an exception, the websocket is silently closed. Nothing is printed to the log. 

Expected behavior is to print the exception to the log, as it is done for the normal HTTP request handlers. 
Probably there should also be some translation to websocket error codes, if that is possible (I am not an expert here). This is to align with the  translation of user exceptions to ServerError (Status 500) for HTTP handlers.

The different behavior is clearly visible in the code:
- The normal request handler does some processing on exceptions: 
https://github.com/sanic-org/sanic/blob/1dd0332e8bef09c83a2c58056b5d8b40b8d060dc/sanic/app.py#L791
- The websocket handler just silently closes the socket on exceptions:
https://github.com/sanic-org/sanic/blob/1dd0332e8bef09c83a2c58056b5d8b40b8d060dc/sanic/app.py#L822

TEST: Server code
```
from sanic import Sanic
from sanic.response import text

app = Sanic("My Hello, world app")

@app.websocket("/")
async def hello_world(request, ws):
    raise ValueError("Error")
    return text("Hello, world.")

app.run(host='localhost', port=8085)
```

TEST: Client Code (just initiates websocket connection)

```
import asyncio
import websockets

async def hello():
    uri = "ws://localhost:8085"
    async with websockets.connect(uri) as websocket:
        await websocket.send("test")


asyncio.get_event_loop().run_until_complete(hello())
```

TEST: Server Output (--> No hint that a ValueError("Error") was raised )

> [2021-07-11 00:32:38 +0200] [21344] [INFO] Goin' Fast @ http://localhost:8085
> [2021-07-11 00:32:38 +0200] [21344] [INFO] Starting worker [21344]
> [2021-07-11 00:32:43 +0200] [21344] [ERROR] Exception occurred while handling uri: 'ws://localhost:8085/'
> Traceback (most recent call last):
>   File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\lib\site-packages\sanic\http.py", line 129, in http1
>     await self.protocol.request_handler(self.request)
>   File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\lib\site-packages\sanic\app.py", line 770, in handle_request
>     response = await response
>   File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\lib\site-packages\sanic\app.py", line 826, in _websocket_handler
>     await ws.close()
>   File "C:\Users\XXX\AppData\Local\Continuum\anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 629, in close
>     await asyncio.shield(self.close_connection_task)
> concurrent.futures._base.CancelledError
> [2021-07-11 00:32:43 +0200] - (sanic.access)[INFO][127.0.0.1:54343]: GET ws://localhost:8085/  503 666
> [2021-07-11 00:33:09 +0200] [21344] [INFO] Stopping worker [21344]
> [2021-07-11 00:33:09 +0200] [21344] [INFO] Server Stopped

**Comment by ChihweiLHBird** [comment]
The logs now look like:

```
[2021-12-27 22:36:27 -0600] [6501] [INFO] Starting worker [6501]
[2021-12-27 22:36:31 -0600] [6501] [INFO] connection open
[2021-12-27 22:36:31 -0600] [6501] [ERROR] Exception occurred while handling uri: 'ws://localhost:8000/'
Traceback (most recent call last):
  File "/home/chihwei/sanic/sanic/app.py", line 1006, in _websocket_handler
    await fut
  File "/home/chihwei/sanic/test.py", line 8, in hello_world
    raise ValueError("Error")
ValueError: Error
```

I believe this was fixed in the PR mentioned above.
