### ISSUE TITLE
Cannot define a blueprint-specific exception handler

### ISSUE THREAD

**Issue by komar007** [sanic-org/sanic#2202]
**Describe the bug**
The documentation at https://sanicframework.org/en/guide/best-practices/blueprints.html#exceptions says that:

> Just like other exception handling, you can define blueprint specific handlers.

However, exception handlers defined this way don't seem to be blueprint-specific at all. Instead, they handle exceptions in other blueprints as well.

**Code snippet**
```python
#!/usr/bin/env python3

from sanic import Sanic, Blueprint, response

class Error(Exception):
    pass

handled = Blueprint("handled")
@handled.exception(Error)
def handle_error(req, e):
    return response.text("handled {}".format(e))

b = Blueprint("b")
@b.route("/")
def e(request):
    raise Error("error in e")

app = Sanic(__name__)
app.blueprint(handled)
app.blueprint(b)
app.run()
```

**Expected behavior**
A request to http://localhost:8000 should generate 500, because `Error` should not be handled.
Instead, the request generates 200, `Error` is handled, even though the handler is registered in `handled`, while the endpoint is in `b`.

**Environment (please complete the following information):**
 - OS: ubuntu 19.10
 - Version: Sanic 21.6.0; Routing 0.7.0

**Additional context**
The order of blueprint registration does not seem to change anything. Not registering blueprint `handled` obviously fixes the issue.

Is it a bug or am I missing something here?

**Comment by ahopkins** [comment]
Sorry for not responding earlier. I am looking at this. See also #2121

**Comment by komar007** [comment]
@ahopkins, 
sorry for not responding too.

I have tried the latest master, but it seems the test above still fails - the exception is still caught:/
Could I be doing something wrong there?

**Comment by ahopkins** [comment]
@komar007 Well, I think you found an interesting use case that is not accounted for.

In your use case above, the `handled` Blueprint has no routes attached. Therefore, when it goes to assign the exception handler it does it at the global level. If you take your example and add one new endpoint, it works as you would expect.

```python
@handled.route("/ok")
def ok(request):
    raise Error("error in e")
```


```
╭─adam@hopkins ~/Projects/Sanic/sanic ‹main› 
╰─$ curl localhost:9999   
⚠️ 500 — Internal Server Error
==============================
error in e

Error: error in e while handling path /
Traceback of __main__ (most recent call last):

  Error: error in e
    File handle_request, line 81, in handle_request
    

    File /tmp/p.py, line 26, in e
    raise Error("error in e")
status=500  size=309 time=0.003229 content-type="text/plain; charset=utf-8"
╭─adam@hopkins ~/Projects/Sanic/sanic ‹main› 
╰─$ curl localhost:9999/ok
handled error in e
status=200  size=18 time=0.001932 content-type="text/plain; charset=utf-8"
```

---

I am not 100% sure if this is even a legitimate use case: having a blueprint with no routes. The simple answer is to just ignore the assignment if there are no routes.

**Comment by komar007** [comment]
Thanks,

it works as expected.

The code from the OP is indeed not a sensible use case, just the simplest reproduction path.

**Comment by ahopkins** [comment]
See #2246 with a fix to this.
