### ISSUE TITLE
How about setting some global properties, such as: user login successfully, displaying information about the user, hiding the login button

### ISSUE THREAD

**Issue by zhenzi0322** [sanic-org/sanic#2205]
I'm wondering if there is a way to get user information quickly, preferably in an html template that can be accessed directly. request can get some properties, but how does request set its own properties, for example: I want to set request.user = 123456

**Comment by sjsadowski** [comment]
You may want to look into contexts, however as Sanic is api oriented, whatever you're trying to do may be more related to whatever templating engine you're using.

**Comment by ahopkins** [comment]
```python
@app.on_request
async def get_user(request):
    request.ctx.user = await extract_user_from_request(request)

@app.get("/path/to/somewhere")
async def handler(request):
    context = {
        ...,
        "user": request.ctx.user
    }
    ...
```
