### ISSUE TITLE
Sanic not raising ConnectionClosed on Python 3.7

### ISSUE THREAD

**Issue by priyesh-kashyap** [sanic-org/sanic#2220]
Hi,

I've been using Sanic and now I want to gather the information that whether the WebSocket is closing normally or abnormally. The problem that I'm facing currently is that whenever the client is closing a connection abnormally (Network Issue), no Exception is being raised. Although I'm getting logs server - event = connection_lost(None) server - state = CLOSED server x code = 1006, reason = [no reason] server! failing CLOSED WebSocket connection with code 1006 but no Exception.

OS: ubuntu - 16
Sanic version: 20.6.3
WebSockets version: 8.1

**Comment by ahopkins** [comment]
xref https://github.com/aaugustin/websockets/issues/1033

**Comment by priyesh-kashyap** [comment]
Thanks, I'll definitely wait for that release but for the time being, Is there a way possible via which I can at least get the status code like 1000 or 1006 after the WebSocket connection closed?

**Comment by ahopkins** [comment]
Please provide a simplified example of what you are looking at and we can test it against 20.12 and 21.6.

**Comment by priyesh-kashyap** [comment]
Sure, I want to capture how many connections terminated normally and how many of them terminated abnormally maybe because of some network issue or the client explicitly force closed that connection.

**Comment by priyesh-kashyap** [comment]
`##################### Sanic Server ####################
import asyncio
import logging
from sanic import Sanic
from websockets.exceptions import ConnectionClosed, ConnectionClosedError, WebSocketException

logging.basicConfig(level=logging.DEBUG)
log = logging.getLogger(__name__)


app = Sanic("websocket test")
@app.websocket("/")
async def test_sanic(_, ws):
  try:
    while True:
      # Suppose some processing is done and to replicate it added sleep
      await asyncio.sleep(10)
      await ws.send("Respoding back!!!")
  except (ConnectionClosedError, ConnectionClosed, WebSocketException):
    log.info("Websocket - connection closed while sending")
  except asyncio.TimeoutError:
    log.debug("Websocket queue timed out!")
  except asyncio.CancelledError as e:
    log.debug("Websocket - connection closed: {}".format(e))
    raise e
  except:
    log.exception("Websocket - unexpected exception while handling Websocket")


if __name__ == "__main__":
  app.run(host="0.0.0.0", port=8000,debug=True)`

**Comment by ahopkins** [comment]
This is no longer the case after 21.9 release. However, we would like to implement a catchable `WebsocketClosed` exception for the websocket handler.
