### ISSUE TITLE
How to config Sanic to support url in  HTML5 history mode

### ISSUE THREAD

**Issue by chongtwo** [sanic-org/sanic#2221]
HTML5 history mode is used as my vue frontend url mode. I use the following code to create url for static files.
`app.static('/template/hello', './static/index.html')`
It works all fine when I access the 'ip:port/template/hello' first and click elements on the page. But it returns 404 when I refresh the page, the url of which is not 'template/hello/' for example 'template/hello/user/' and which is not a real url for backend.
Vue guide mentions HTML5 history mode needs support of backend web framework. I don't know how to config sanic to support that. 
Looking forward to your help. Thanks!

**Comment by ahopkins** [comment]
I am not a Vue expert and do not know exactly what they mean by that. History manipulation is entirely a browser construct and has nothing to do with Sanic or backend frameworks.

However, I can guess at what they mean. Typically, a frontend framework handles all of its own internal routing. Therefore, if you are (for example) serving your frontend application with Sanic, then you need to also route all of the potential endpoints to that same location.

Something like this:

```python
from sanic.response import file

@app.get("/<path:path>")
def index_handler(request, route):
    return file("/path/to/index.html")
```

This will redirect all pages to your Vue application, which will then be responsible for handling the routing.
