### ISSUE TITLE
SANIC_NO_UVLOOP=true doesn't seem to work

### ISSUE THREAD

**Issue by delfick** [sanic-org/sanic#2223]
**Describe the bug**
Installing sanic with a SANIC_NO_UVLOOP=true in my environment still results in uvloop being installed

**Environment (please complete the following information):**
 - OS: macOS Big Sur
 - Version 11.5.2

**Additional context**
Python 3.9.6

<img width="1494" alt="Screen Shot 2021-08-22 at 9 15 49 am" src="https://user-images.githubusercontent.com/109301/130337105-7599c107-1311-4ae0-8187-46667afe1220.png">

**Comment by ahopkins** [comment]
![image](https://user-images.githubusercontent.com/166269/130352266-d527c0b4-4518-4fbf-bd16-d502b9c416a2.png)

If you look at the unit tests, you can see if definitely works. Perhaps you have pip cache?

**Comment by delfick** [comment]
`--no-cache-dir` doesn't make a difference and also given it's decided in sanic's setup.py based on the environment variable, it wouldn't make sense for it to anyway!

After some checking, I think the reason is because the wheel doesn't have a setup.py and so when you install via a wheel it doesn't ever do this check https://github.com/sanic-org/sanic/blob/main/setup.py#L138

**Comment by ahopkins** [comment]
One of the things that has been a question for a long time on this project is how to gracefully handle this. Obviously, the best scenario would be if pip supported subtractive `install_requires`:

```
$ pip install sanic[no-uvloop]
```

This (to my knowledge) is still not a supported feature. The problem is that we do want `uvloop` to be installed by default. That will not change. The only other solution that would work is if you do this:

```
pip install sanic
pip uninstall uvloop
```

Not ideal, but in CI it is not _terrible_.

If you have some other thoughts or suggestions, please let me know.

**Comment by delfick** [comment]
can we make it so that sanic chooses to use it at runtime? i.e. I can set an environment variable or sanic option that makes it not set uvloop? that way uvloop can be in the environment, but sanic can choose to not use it

**Comment by delfick** [comment]
i.e. move https://github.com/sanic-org/sanic/blob/b1b12e004eff1702d969ac711e5863b46b79e893/sanic/server.py#L51 to when you use the loop or make this not happen based on an environment variable.

**Comment by ahopkins** [comment]
> can we make it so that sanic chooses to use it at runtime rather than forced on us at import time? i.e. I can set an environment variable or sanic option that makes it not set uvloop? that way uvloop can be in the environment, but sanic can choose to not use it

Yeah, that can probably work fine. I did something similar with `uvloop` by allowing for an application override (for `dumps` only, we still need to add it for `loads`).

**Comment by delfick** [comment]
Awesome! Thank you so much :)

**Comment by prryplatypus** [comment]
Hope it works! :)

**Comment by delfick** [comment]
Thanks ❤️
