### ISSUE TITLE
Unnecessary access log when socket disconnects before sending any bytes

### ISSUE THREAD

**Issue by Frankr0** [sanic-org/sanic#2226]
**Describe the bug**
A socket connection request to server will cause following error:
```
[2021-08-30 10:29:31 +0800] - (sanic.access)[INFO][UNKNOWN]: NONE http:///*  503 666
[2021-08-30 10:29:31 +0800] [6386] [ERROR] Connection lost before response written @ ('127.0.0.1', 36214) <Request: NONE *>

```
why and how can i prevent that?

**Code snippet**
server.py

```
from sanic import Sanic
from sanic import text

app = Sanic.get_app("test", force_create=True)

@app.get("/")
async def response(request):
    return text("ok")

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=9000, access_log=True, debug=True)

```
client.py

```
import socket

if __name__ == '__main__':

    server_addr = ('localhost', 9000)

    tcp_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    tcp_socket.connect(server_addr)
    tcp_socket.close()
```

**Expected behavior**
no error msg

**Environment (please complete the following information):**
 - OS: CentOS
 - Version: 21.6.2

**Comment by ahopkins** [comment]
Why is that a bug, and what would you expect to happen differently? What is the use case you are testing for?

**Comment by Frankr0** [comment]
Hi~ @ahopkins , thanks for your replay,  socket connection only establish on tcp layer, no http data packet has been sent. If I understand correctly, sanic is a http server framework, why should there be an error log? The same case is tested on flask without errors.

![image](https://user-images.githubusercontent.com/16506449/131302106-02b1ae3a-6ed0-414f-9a75-aec8e1b9b80b.png)

**Comment by ahopkins** [comment]
Flask is not a server. Sanic is.

Out of the box, Sanic uses HTTP protocol, but it could be used for others. That is not really the point. 

What is more at issue is what a server should do when a connection is opened, and no bytes are sent. I think this is valuable information and should not be ignored. Perhaps something another message is more appropriate? I have not tested, but I would be more curious to know what a server like `nginx` does.

**Comment by Frankr0** [comment]
`nginx` does have a readable log. 
![image](https://user-images.githubusercontent.com/16506449/131334940-4aba8f1b-288c-4454-9f8c-849b969c192a.png)

**Comment by ahopkins** [comment]
I accept that as a solution. We can probably remove the access logger here. I suppose it is still debatable what level the message should be. I am somewhat inclined to leave it because I do not see a strong reason why it should change from ERROR to INFO.

**Comment by Tronic** [comment]
The current error message seems misleading (we were waiting for a request, not trying to send a response). Disconnection at any point where no request has been sent should be quiet IMO. I gather that browsers could be firing multiple parallel connections and then not always use them even for one request. This should not cause error messages in logs.

**Comment by ahopkins** [comment]
I disagree. A connection is opened, it should be logged. The level at which that happens I do not disagree is probably not an ERROR. But it shouldn't be quiet either. If for no other reason, it would be very hard to impossible to track what was happening if you had some rogue agent opening and closing connections in rapid succession.

**Comment by Frankr0** [comment]
There may should be a message here, but the more important problem is that sanic try to process this "NONE" request, I have to add following code at beginning to respond early:
```
@app.middleware("request")
async def handle_none_type_request(request):
    if request.method == 'NONE':
        return text('')
```
Is there any better solution here？



```
from sanic import Sanic
from sanic import text
from sanic.log import logger

app = Sanic.get_app("test", force_create=True)

@app.middleware("request")
async def handle_none_type_request(request):
    logger.info('request -- {}'.format(request))
    if request.method == 'NONE':
        return text('')

@app.get("/")
async def response(request):
    logger.info('response')
    return text("ok")


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=9000, access_log=True, debug=True)
```

Log:
```
[2021-08-31 10:50:53 +0800] [17365] [INFO] Goin' Fast @ http://0.0.0.0:9000
[2021-08-31 10:50:53 +0800] [17365] [DEBUG] Sanic auto-reload: enabled
[2021-08-31 10:50:53 +0800] [17365] [DEBUG] Sanic debug mode: enabled
[2021-08-31 10:50:53 +0800] [17365] [INFO] Starting worker [17365]
[2021-08-31 10:50:57 +0800] [17365] [INFO] request -- <Request: NONE *>
[2021-08-31 10:50:57 +0800] - (sanic.access)[INFO][UNKNOWN]: NONE http:///*  200 0
[2021-08-31 10:50:57 +0800] [17365] [ERROR] Connection lost before response written @ ('127.0.0.1', 58243) <Request: NONE *>
```

**Comment by Tronic** [comment]
I believe the culprit is that http.py starts a new connection in request mode, not in idle mode (mainly to initially use request timeout, not keep-alive timeout, as it would *between* requests).

**Comment by ahopkins** [comment]
I have not looked at the code as it relates to this. Are you thinking to start the loop with a flag to set state?

**Comment by Tronic** [comment]
I guess one alternative would be to start in idle state, and switch to request state as soon as any data is received. This needs changes to current unit tests for request timeout, and consequently it might affect some users as well.

Alternatively, prior to raising that error, there should be a check for the actual state. And I gather that there should also be an access log entry for connections that just disconnect without any requests but no errors.

**Comment by ahopkins** [comment]
Between the two, the second option sounds better.

**Comment by ChihweiLHBird** [comment]
Was this fixed? Couldn't reproduce, or I miss something?
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/43905414/147212724-cb6f49d5-74e5-4108-b448-62d39c53bb46.png">

**Comment by Frankr0** [comment]
> Was this fixed? Couldn't reproduce, or I miss something? <img alt="image" width="1426" src="https://user-images.githubusercontent.com/43905414/147212724-cb6f49d5-74e5-4108-b448-62d39c53bb46.png">

I just tested it on version 21.12 and it seems to be fixed.
