### ISSUE TITLE
[21.6.x on pyinstaller builds crash] ModuleNotFoundError: No module named 'websockets.legacy.protocol'

### ISSUE THREAD

**Issue by gubatron** [sanic-org/sanic#2227]
**Describe the bug**
We build our server into a single macOS executable with pyinstaller.
sanic works perfectly up until version `21.3.4`
After `21.6.0` (including both `21.6.1`, `21.6.2`)

When the app is run and it's going through the `sanic` imports we get the following crash and stacktrace:
```
Traceback (most recent call last):
  File "telluride.py", line 28, in <module>
    import server
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "server.py", line 23, in <module>
    from sanic import Sanic
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sanic/__init__.py", line 2, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sanic/app.py", line 43, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sanic/asgi.py", line 11, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sanic/models/asgi.py", line 6, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "sanic/websocket.py", line 13, in <module>
  File "websockets/imports.py", line 81, in __getattr__
  File "websockets/imports.py", line 26, in import_name
ModuleNotFoundError: No module named 'websockets.legacy.protocol'
[32682] Failed to execute script 'telluride' due to unhandled exception!
```

[sanic/websocket.py:13](https://github.com/sanic-org/sanic/blob/main/sanic/websocket.py#L13)

**Code snippet**
[Our tiny http server code here](https://github.com/frostwire/frostwire/blob/master/telluride/server.py#L23)

**Expected behavior**
Not crash, the same way it works with all previous versions of `sanic` up to `21.3.4`

**Environment (please complete the following information):**
 - OS: macOS (so far, still need to test in windows and linux, will follow up on this thread in a few minutes)
 - Version `21.6.0`, `21.6.1`, `21.6.2`
 - The error comes up with both python `3.7` and `3.9.6`

**Comment by gubatron** [comment]
the problem also occurs in Windows 10, python 3.8.1 when using `sanic 21.6.2`, works fine with `21.3.4`
<img width="1875" alt="Screen Shot 2021-08-30 at 3 54 17 PM" src="https://user-images.githubusercontent.com/163977/131410923-41d7492c-bcbf-4cb5-b075-ad99dbd9e3b7.png">

will most likely not work in Linux, prepping test to confirm

**Comment by ahopkins** [comment]
It is because you do not have the right version of `websockets` installed. You need to have v9.

**Comment by gubatron** [comment]
will try that. Wonder if `sanic` pip requirements can specify the right version of `websockets` that it needs.

**Comment by ahopkins** [comment]
It does:

https://github.com/sanic-org/sanic/blob/current-release/setup.py#L91

---

Maybe you have some sort of pip caching issue in your env. Try installing sanic again with no cache.

**Comment by gubatron** [comment]
For whoever is reading this, @ahopkins is right, had `websockets 8.1`

```$ pip show websockets
Name: websockets
Version: 8.1
Summary: An implementation of the WebSocket Protocol (RFC 6455 & 7692)
Home-page: https://github.com/aaugustin/websockets
Author: Aymeric Augustin
Author-email: aymeric.augustin@m4x.org
License: BSD
Location: /usr/local/lib/python3.9/site-packages
Requires: 
Required-by: sanic
```

However, upgrading to websockets `9.1` isn't cutting it. I've done `pip install --no-cache-dir` to clear the pip cache for both `sanic` and `websockets`

Here's a screenshot with the same stacktrace and `pip show sanic websockets`

<img width="985" alt="Screen Shot 2021-08-30 at 4 13 30 PM" src="https://user-images.githubusercontent.com/163977/131412684-ba279499-835c-4656-9b8f-41871e4ef92a.png">

**Comment by ahopkins** [comment]
That does not make sense to me as `websockets` 9 introduced that `legacy` module to be able to support projects like Sanic as it changed directions. If you did raise and issue there, please ping me so I can join the conversation because something does not sounds right.

**Comment by gubatron** [comment]
Update for whoever gets here.

Only after Python 3.10.1 I was able to update sanic without getting this error.

My server works fine if I run it from source with `python3 myserver.py` (only if I start sanic with 2 workers)

However, my server is packaged with PyInstaller, when I run the executable now I get the following crash:

```
Process ForkProcess-1:1:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 315, in _bootstrap
  File "multiprocessing/process.py", line 108, in run
  File "sanic/server/runners.py", line 129, in serve
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "sanic/app.py", line 1979, in _startup
  File "sanic/touchup/service.py", line 26, in run
  File "sanic/touchup/schemes/base.py", line 20, in __call__
  File "sanic/touchup/schemes/ode.py", line 22, in run
  File "inspect.py", line 1147, in getsource
  File "inspect.py", line 1129, in getsourcelines
  File "inspect.py", line 958, in findsource
OSError: could not get source code
multiprocessing/process.py:331: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
Process ForkProcess-1:2:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 315, in _bootstrap
  File "multiprocessing/process.py", line 108, in run
  File "sanic/server/runners.py", line 129, in serve
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "sanic/app.py", line 1979, in _startup
  File "sanic/touchup/service.py", line 26, in run
  File "sanic/touchup/schemes/base.py", line 20, in __call__
  File "sanic/touchup/schemes/ode.py", line 22, in run
  File "inspect.py", line 1147, in getsource
  File "inspect.py", line 1129, in getsourcelines
  File "inspect.py", line 958, in findsource
OSError: could not get source code
multiprocessing/process.py:331: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
```

Trying to do all sorts of gymnastics with `async`, `await` and with `multiprocessing` and `freeze_support`

Here are some of the failed gymnastics to get sanic to work with a PyInstaller distribution

```
def async_main():
    asyncio.run(main())

if __name__ == '__main__':
    freeze_support()
    Process(target=async_main).start()
 ```
 
 where my `main()` starts the server like this:
 
```
async def main():
    ...
    await(server.start(BUILD, SERVER_PORT, 2))
```

and my `server` module and it's `start` looks like this:
```
async def start(build_number, http_port_number=DEFAULT_HTTP_PORT, workers_number=1):
    '''                                                                                                                                                 
    starts the web server.                                                                                                                              
    Parameters:                                                                                                                                         
    build_number: telluride build number                                                                                                                
    http_port_number                                                                                                                                    
    workers_number                                                                                                                                      
    '''
    app = Sanic(f'TellurideWebServer_{build_number}')

    @app.route('/')
    async def root_handler(request):
        '''                                                                                                                                             
        http handler, rejects connections not coming from localhost|127.0.0.1                                                                           
        url parameters:                                                                                                                                 
        url=<url encoded video page url to obtain json metadata from>                                                                                   
        [shutdown=1] if passed it will shutdown the server                                                                                              
        '''
        #pylint: disable=unused-variable                                                                                                                
        if request.ip not in ('127.0.0.1', 'localhost'):
            return json({'build': build_number, 'message': 'gtfo'})
        query = dict(request.query_args)
	if 'shutdown' in query and (query['shutdown'] == '1' or query['shutdown'].lower() == 'true'):
            sys.exit(0)
            return
        if 'url' in query:
            return query_video(query['url'])
        return json({'build' : build_number, 'message': 'no valid parameters received'})

    app.run(host='127.0.0.1', port=http_port_number, workers=workers_number)
```


nothing works. Thinking of switching to another web framework altogether at this point.

**Comment by ahopkins** [comment]
I am sorry you have been struggling. You never messaged me about this so I would have assumed it was resolved. I wish you would have reached out sooner and I could have helped you through this rather than struggling through your frustrations.

You are running Sanic in a capacity that is not standard. PyInstaller attempts to do a lot of code stripping. Sanic itself tries to do this at startup to optimize your performance. So, what is happening is that PyInstaller is removing parts of Sanic. When the Sanic server starts, it throws an `OSError` because the code that it _thinks_ should be available does not exist.

I just went through and put the following snippet into a fresh venv with Sanic and PyInstaller.

```
$ pip install PyInstaller sanic
...

$ pip freeze                                         
aiofiles==0.8.0
altgraph==0.17.2
httptools==0.3.0
multidict==5.2.0
pyinstaller==4.8
pyinstaller-hooks-contrib==2021.5
sanic==21.12.1
sanic-routing==0.7.2
ujson==5.1.0
uvloop==0.16.0
websockets==10.1
```

Then, I created a simple script that approximates the code you shared:

```python
import asyncio
from multiprocessing import Process, freeze_support

from sanic import Sanic, json

DEFAULT_HTTP_PORT = 9999
BUILD = 123
SERVER_PORT = DEFAULT_HTTP_PORT


class SomeServer:
    @staticmethod
    async def start(
        build_number, http_port_number=DEFAULT_HTTP_PORT, workers_number=1
    ):
        app = Sanic(f"TellurideWebServer_{build_number}")

        @app.route("/")
        async def root_handler(request):
            return json(
                {
                    "build": build_number,
                    "message": "no valid parameters received",
                }
            )

        app.run(
            host="127.0.0.1", port=http_port_number, workers=workers_number
        )


def async_main():
    asyncio.run(main())


async def main():
    server = SomeServer()
    await (server.start(BUILD, SERVER_PORT, 2))


if __name__ == "__main__":
    freeze_support()
    Process(target=async_main).start()
```

I was able to recreate your issue:

```
$ python -m PyInstaller /tmp/issue2227.py
...

$ ./dist/issue2227/issue2227
...
OSError: could not get source code
multiprocessing/process.py:331: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
```

A quick look at the [PyInstaller docs](https://pyinstaller.readthedocs.io/en/stable/usage.html#cmdoption-collect-all) showed me this:

> --collect-all MODULENAME
>
>    Collect all submodules, data files, and binaries from the specified package or module. This option can be used multiple times.

A quick rebuild:

```
$ python -m PyInstaller /tmp/p.py --collect-all=sanic
```

Sure enough, when I run the executable now, it runs as expected and I can ping the endpoint:

```
$ curl localhost:9999
{"build":123,"message":"no valid parameters received"}
```

---

I hope this helps. If there are more people looking to make a PyInstaller executable with Sanic perhaps we can add it to the `How to...` section of the documentation.

**Comment by gubatron** [comment]
Wow, thank you Adam for taking the time to look at this in detail, wish I'd found that `--collect-all` flag for PyInstaller earlier!

Hopefully this will help someone that might have a similar problem in the future.
