### ISSUE TITLE
when HTTPRequestHandler returns empty(like: {}, []), request_exception run first than costom-response-middleware

### ISSUE THREAD

**Issue by iduosi** [sanic-org/sanic#2228]
when HTTPRequestHandler returns empty(like: {}, []), request_exception run first than costom-response-middleware

**Code snippet**
            # No middleware results
            if not response:
                # -------------------------------------------- #
                # Execute Handler
                # -------------------------------------------- #

                if handler is None:
                    raise ServerError(
                        (
                            "'None' was returned while requesting a "
                            "handler from the router"
                        )
                    )

                # Run response handler
                response = handler(request, **kwargs)
                if isawaitable(response):
                    response = await response

            if response:
                response = await request.respond(response)
            elif not hasattr(handler, "is_websocket"):
                response = request.stream.response  # type: ignore

            # Make sure that response is finished / run StreamingHTTP callback
            if isinstance(response, BaseHTTPResponse):
                await response.send(end_stream=True)
            else:
                if not hasattr(handler, "is_websocket"):
                    raise ServerError(
                        f"Invalid response type {response!r} "
                        "(need HTTPResponse)"
                    )

        except CancelledError:
            raise
        except Exception as e:
            # Response Generation Failed
            await self.handle_exception(request, e)

**Comment by iduosi** [comment]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/55998415/131430745-6ce06f84-9abc-42fc-9b97-bb504af5fce3.png">

**Comment by iduosi** [comment]
sanic==21.6.2
sanic-routing==0.7.1

**Comment by ahopkins** [comment]
I don't need Sanic code posted to understand your question, I need your choice. please post a snippet of your handler and what it's returning. Is it not returning an instance of HTTPResponse?

It is not clear if you are returning 

```python 
return empty()
```

or

```
return {}
```

**Comment by iduosi** [comment]
api method handle‘s code：

`
class BUGHandleApi(HTTPMethodView):

    async def get(self, request):
        logger.debug(f"debug BUGHandleApi called-in..")

        return {}
`

middleware’s code，just like this：
`
async def debug_response_middleware(request, response):
    if not isinstance(response, HTTPResponse):
        body = {
            "resultcode": StatusCode.SUCCESS.humanize_code(),
            "msg": "",
            "data": response,
        }
        response = HTTPResponse(json_dumps(body),
                                headers=None,
                                content_type="application/json; charset=utf-8",
                                status=200,)
        return response
`

**Comment by Tronic** [comment]
Agreed, one should be able to use middleware to process such responses into Sanic responses. The first `if response` check marked in red could instead check if there already is a response on the request, and only use the return value if there wasn't. Probably needs some other work too.

Also, I think this used to work, or worked at least for non-empty plain dicts returned from handlers that a middleware could turn into JSON responses.

**Comment by ahopkins** [comment]
It should work for truthy values since I think the check is: `if response`. We could probably change that to a `if response is not None`. It is a one line change.

**Comment by ahopkins** [comment]
It should work for truthy values since I think the check is: `if response`. We could probably change that to a `if response is not None`. It is a one line change.

**Comment by ahopkins** [comment]
@iduosi Would you be willing to add a PR for this?

Change that one line to `if response is not None` and then add simple unit test using your example?

**Comment by ahopkins** [comment]
Just confirmed with that change both this example works and the unit tests pass.

```python
@app.on_response
def display(_, response):
    response["foo"] = "bar"
    return json(response)


@app.get("/")
async def handler(request):
    return {}
```
