### ISSUE TITLE
sanic_routing.exceptions.FinalizationError: Cannot finalize router more than once.

### ISSUE THREAD

**Issue by nickmoop** [sanic-org/sanic#2232]
When i tried to test app (tests works for 20.x version), but i got exception:
```
    @pytest.fixture
    def test_cli_ws(loop, sanic_client):
>       return loop.run_until_complete(
            sanic_client(app, scheme="ws", protocol=WebSocketProtocol))

test_bug.py:10: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
uvloop/loop.pyx:1501: in uvloop.loop.Loop.run_until_complete
    ???
/home/user/venvs/backend/lib/python3.8/site-packages/pytest_sanic/plugin.py:203: in create_client
    await client.start_server()
/home/user/venvs/backend/lib/python3.8/site-packages/pytest_sanic/utils.py:227: in start_server
    await self._server.start_server()
/home/user/venvs/backend/lib/python3.8/site-packages/pytest_sanic/utils.py:104: in start_server
    await trigger_events(self.before_server_start, self.loop)
/home/user/venvs/backend/lib/python3.8/site-packages/pytest_sanic/utils.py:30: in trigger_events
    await result
/home/user/venvs/backend/lib/python3.8/site-packages/sanic/app.py:1347: in finalize
    raise e  # noqa
/home/user/venvs/backend/lib/python3.8/site-packages/sanic/app.py:1342: in finalize
    app.router.finalize()
/home/user/venvs/backend/lib/python3.8/site-packages/sanic/router.py:180: in finalize
    super().finalize(*args, **kwargs)

sanic_routing.exceptions.FinalizationError: Cannot finalize router more than once.
```

tmp_app.py
```
from sanic import Sanic, response

app = Sanic("test_sanic_app")


@app.route("/test_get", methods=["GET"])
async def test_get(request):
    return response.json({"GET": True})


@app.websocket("/test_ws")
async def test_ws(request, ws):
    data = await ws.recv()
    await ws.send(data)
```

test_bug.py
```
import pytest
from sanic.websocket import WebSocketProtocol

from tmp_app import app


@pytest.fixture
def test_cli_ws(loop, sanic_client):
    return loop.run_until_complete(
        sanic_client(app, scheme="ws", protocol=WebSocketProtocol))


@pytest.fixture
def test_cli_http(loop, sanic_client):
    return loop.run_until_complete(sanic_client(app))


async def test_fixture_test_client_get(test_cli_http):
    resp = await test_cli_http.get('/test_get')
    assert resp.status_code == 200
    resp_json = resp.json()
    assert resp_json == {"GET": True}


async def test_fixture_test_client_ws(test_cli_ws):
    ws_conn = await test_cli_ws.ws_connect('/test_ws')
    data = 'hello world!'
    await ws_conn.send(data)
    msg = await ws_conn.recv()
    assert msg == data
    await ws_conn.close()


async def test_fixture_test_client_other_get(test_cli_http):
    resp = await test_cli_http.get('/test_get')
    assert resp.status_code == 200


async def test_fixture_test_client_other_ws(test_cli_ws):
    ws_conn = await test_cli_ws.ws_connect('/test_ws')
    data = 'hello world!'
    await ws_conn.send(data)
    msg = await ws_conn.recv()
    assert msg == data
    await ws_conn.close()
```

I expect all successful test (as in 20.x version). 

Ubuntu 20, python 3.8, sanic 21.6.2, pytest-sanic 1.8.1

exception raises because of finalize added to listeners each time server created (each loop.run_until_complete(sanic_client(app, scheme="ws", protocol=WebSocketProtocol)) call)

Sanic._helper -> 
self.listeners["before_server_start"] = [
    self.finalize
] + self.listeners["before_server_start"]

**Comment by ahopkins** [comment]
What is `sanic_client`?

Basically it looks like you are trying to run the same app multiple times. Which version of sanic-testing are you using? Latest?

**Comment by nickmoop** [comment]
sanic_client is not deprecated test_client fixture of pytest-sanic lib. i use pytest-sanic (latest, 21.6.2) but not sanic-testing. yes i run same app multiple times, because i have few tests, and pytest create client for each test and each client starts its own server (execute _helper and add new finalize call)

**Comment by ahopkins** [comment]
I cannot commnt on pytest sanic since it is not an officially supported plugin and I do not know how it works. I can tell you that the behavior happens when you try running the same app multiple times since the router has already been built. So, likely you have a fixture misconfigured. The sanic-testing package handles this scenario. 

Essentially, when running, the application with call `app.router.finalize()`. This cannot be run multiple times without running `app.router.reset()` in between. Perhaps you need to add that to your fixture.

I am closing this for now as it is not a Sanic related issue. If you need further support or have more questions, please post in the forums or the Discord server.
