### ISSUE TITLE
Sanic prints "auto-reload: enabled" even when auto_reload is False.

### ISSUE THREAD

**Issue by ashleysommer** [sanic-org/sanic#2240]
Kinda related to #2237 

https://github.com/sanic-org/sanic/blob/404c5f9f9eb54f06d1f30250bc2cc840c18a0eab/sanic/app.py#L1340

**Comment by ashleysommer** [comment]
Message introduced in https://github.com/sanic-org/sanic/pull/2136

**Comment by ahopkins** [comment]
Can you provide an example?

**Comment by ashleysommer** [comment]
```
app = Sanic("app")
if __name__ == "__main__"":
    app.run("127.0.0.1", 8080, debug=True, auto_reload=False)
```

Always Prints:
> "Sanic auto-reload: enabled"

Even though auto-reload is actually disabled.
