### ISSUE TITLE
Proposal: Add CORS to Sanic Utilities

### ISSUE THREAD

**Issue by sjsadowski** [sanic-org/sanic#2243]
**Is your feature request related to a problem? Please describe.**
Almost everything requires CORS headers now, and we already provide a 'HOW-TO' in the docs - I propose that we standardize this and internalize it in order to provide an easier path to adoption.

**Describe the solution you'd like**
Add a CORS utility module that can easily be referenced to add CORS headers as part of response middleware, much like the docs show.

**Comment by ahopkins** [comment]
This is not something that belongs in the core repo as it breaks the philosophy of Sanic in being overly opinionated. 

The response to this is the `sanic-ext` project which will be released this month. Official support to add functionality like this for API devs.

**Comment by ahopkins** [comment]
Public announcement and documentation regarding this is coming.
