### ISSUE TITLE
KEEP_ALIVE_TIMEOUT causing the changes in server (mode debug) to be delayed?

### ISSUE THREAD

**Issue by cnicodeme** [sanic-org/sanic#2249]
**Describe the bug**
When running Sanic with the following options:

`app.run(auto_reload=True, debug=True)`

If I make any changes to my code and refresh, the new code is not taken into consideration. I need to wait a few seconds, and I'll see the following message in the console:

> [DEBUG] KeepAlive Timeout. Closing connection.

Reading the [documentation](https://sanicframework.org/en/guide/deployment/configuration.html#keep-alive-timeout), settings KEEP_ALIVE to False in dev mode would solve my issue, but it doesn't change anything. The error still is displayed after about 8 seconds.

What can I do to have my new code refreshed immediately when running Sanic?

**Expected behavior**
New code executed on refresh, not the previous one.

**Environment (please complete the following information):**
 - OS: Fedora 24
 - Version: 21.6.2
 - Python: 3.8.10

**Comment by Tronic** [comment]
I gather it does a graceful restart and does not terminate your existing connection until when they timeout. IIRC, the code is supposed to immediately disconnect *idle* connections, so this should not be an issue. Needs investigation.

**Comment by ahopkins** [comment]
Can you provide a reproducible example? What error are you talking about?

**Comment by cnicodeme** [comment]
I can provide a reproducible example, but probably not until Monday, so don't be surprised if I don't post anything until then :)

**Comment by cnicodeme** [comment]
Ok I got some time!

The following code causes the issue:

```
# -*- coding:utf-8 -*-

from sanic import Sanic
from sanic.response import text

app = Sanic('My_App', strict_slashes=True)

@app.get('/ping')
async def ping(request):
    return text(f'Pong (My_App v154)')

if __name__ == '__main__':
    app.run(host='127.0.0.1', port=5000, auto_reload=True, debug=True)
```

Here's the logs in the console:

> [2021-10-01 14:33:01 +0200] [4126114] [INFO] Goin' Fast @ http://127.0.0.1:5000
> [2021-10-01 14:33:01 +0200] [4126114] [DEBUG] Sanic auto-reload: enabled
> [2021-10-01 14:33:01 +0200] [4126114] [DEBUG] Sanic debug mode: enabled
> [2021-10-01 14:33:01 +0200] [4126114] [INFO] Starting worker [4126114]
> [2021-10-01 14:33:03 +0200] - (sanic.access)[INFO][127.0.0.1:58606]: GET http://127.0.0.1:5000/ping  200 16 <--- Here, I have the right data
> ==> (Now, I change the code in my editor, and hit refresh on the browser. We can see the next request:)
> [2021-10-01 14:33:06 +0200] - (sanic.access)[INFO][127.0.0.1:58606]: GET http://127.0.0.1:5000/ping  200 16
> => (That previous request showed the SAME data, see the "16" indicating the content length, which is the same in both past request, despite my changes)
> [2021-10-01 14:33:06 +0200] [4126114] [INFO] Stopping worker [4126114]
> [2021-10-01 14:33:16 +0200] - (sanic.access)[INFO][127.0.0.1:58608]: GET http://127.0.0.1:5000/ping  200 18
> ==> (HERE! The data has changed! I had to wait for "Stopping worker" to be able to refresh and see the changes!)
> [2021-10-01 14:33:21 +0200] [4126114] [INFO] Server Stopped
> [2021-10-01 14:33:21 +0200] [4126170] [INFO] Goin' Fast @ http://127.0.0.1:5000
> [2021-10-01 14:33:21 +0200] [4126170] [DEBUG] Sanic auto-reload: enabled
> [2021-10-01 14:33:21 +0200] [4126170] [DEBUG] Sanic debug mode: enabled
> [2021-10-01 14:33:21 +0200] [4126170] [INFO] Starting worker [4126170]

My details are:

 * OS: Fedora 32 (I said 24 in my original post but it was a mistake)
 * Version: 21.6.2
 * Python: 3.8.10
 * Chrome: 92.0.4515.159 64bits

If you need any other details, let me know :)

**Comment by cnicodeme** [comment]
If that can help, I also noticed that if I stop the server and then wait, a few seconds later (event though the server is fully stopped with a ctrl+c multiple times), I get the following error:

> [2021-10-01 14:44:06 +0200] [4127596] [ERROR] protocol.connection_task uncaught
> Traceback (most recent call last):
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/http.py", line 130, in http1
>     await self.http1_request_header()
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/http.py", line 203, in http1_request_header
>     await self._receive_more()
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/server.py", line 222, in receive_more
>     await self._data_received.wait()
>   File "/usr/lib64/python3.8/asyncio/locks.py", line 309, in wait
>     await fut
> asyncio.exceptions.CancelledError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/server.py", line 197, in connection_task
>     await self._http.http1()
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/http.py", line 146, in http1
>     await self.error_response(e)
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/http.py", line 420, in error_response
>     await app.handle_exception(self.request, exception)
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/app.py", line 704, in handle_exception
>     await response.send(end_stream=True)
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/response.py", line 122, in send
>     await self.stream.send(data, end_stream=end_stream)
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/http.py", line 348, in http1_response_header
>     self.log_response()
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/http.py", line 457, in log_response
>     extra["request"] = f"{req.method} {req.url}"
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/request.py", line 669, in url
>     (self.scheme, self.host, self.path, None, self.query_string, None)
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/request.py", line 596, in scheme
>     if self.transport.get_extra_info("sslcontext"):
> AttributeError: 'NoneType' object has no attribute 'get_extra_info'
> [2021-10-01 14:44:06 +0200] [4127596] [INFO] Server Stopped
> Task exception was never retrieved
> future: <Task finished name='Task-11' coro=<HttpProtocol.connection_task() done, defined at /home/user/www/api/env/lib64/python3.8/site-packages/sanic/server.py:188> exception=AttributeError("'NoneType' object has no attribute 'get_extra_info'") created at /home/user/www/api/env/lib64/python3.8/site-packages/sanic/server.py:302>
> source_traceback: Object created at (most recent call last):
>   File "server.py", line 11, in <module>
>     app.run(host='127.0.0.1', port=5000, auto_reload=True, debug=True)
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/app.py", line 976, in run
>     serve_single(server_settings)
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/server.py", line 724, in serve_single
>     serve(**server_settings)
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/server.py", line 577, in serve
>     loop.run_forever()
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/server.py", line 302, in connection_made
>     self._task = self.loop.create_task(self.connection_task())
> Traceback (most recent call last):
>   File "/home/user/www/api/env/lib64/python3.8/site-packages/sanic/server.py", line 204, in connection_task
>     ip = self.transport.get_extra_info("peername")
> AttributeError: 'NoneType' object has no attribute 'get_extra_info'

(But I forgot an await at some place, so it might not be related).

**Comment by Tronic** [comment]
I am unable to reproduce this either with Sanic 21.6.2 or with current development version, using Chrome as client and hitting Ctrl-R to reload. Sanic restarts as soon as I hit Ctrl+S in my editor and immediately after that reloading in browser brings the new content.

The backtrace, however, should be useful in triaging this. There clearly is a handler stuck in waiting for request.

Could you try with Python 3.9 just in case that makes a difference? I don't have 3.8 around anymore.

**Comment by cnicodeme** [comment]
I just tested with Python3.9, and it seems even worse. Now, a basic DB loading that was returned in less than 25ms previously, takes a few seconds to complete.

If I refresh a basic "text('ok')" response, then change the response and hit refresh again, the changes are not visible (still shows "ok").

After a few seconds, Sanic restarts, and then I can see the changes.

If I do that again, but before waiting Sanic to restart, I kill it (CTRL+C multiple times, once is not enough), I don't have the above error anymore, but this is displayed in the terminal (a few seconds after the server is stopped):

```
[2021-10-04 10:42:29 +0200] [189799] [DEBUG] KeepAlive Timeout. Closing connection.
[2021-10-04 10:42:29 +0200] [189799] [DEBUG] Triggering server events: server.shutdown.after
[2021-10-04 10:42:29 +0200] [189799] [DEBUG] Dispatching signal: server.shutdown.after
[2021-10-04 10:42:29 +0200] [189799] [WARNING] Could not find signal server.shutdown.after
[2021-10-04 10:42:29 +0200] [189799] [INFO] Server Stopped
```

That tested Python version is 3.9.5

**Comment by cnicodeme** [comment]
Note that as soon as I hit "ctrl+s" on my editor, Sanic server shows the following : 

```
[2021-10-04 10:44:35 +0200] [190018] [INFO] Stopping worker [190018]
[2021-10-04 10:44:35 +0200] [190018] [DEBUG] Triggering server events: server.shutdown.before
[2021-10-04 10:44:35 +0200] [190018] [DEBUG] Dispatching signal: server.shutdown.before
[2021-10-04 10:44:35 +0200] [190018] [WARNING] Could not find signal server.shutdown.before
```

But hitting refresh does not changes anything.

Then, a few seconds later, the server shows the following : 

```
[2021-10-04 10:45:51 +0200] [190051] [DEBUG] KeepAlive Timeout. Closing connection.
[2021-10-04 10:45:51 +0200] [190051] [DEBUG] Triggering server events: server.shutdown.after
[2021-10-04 10:45:51 +0200] [190051] [DEBUG] Dispatching signal: server.shutdown.after
[2021-10-04 10:45:51 +0200] [190051] [WARNING] Could not find signal server.shutdown.after
[2021-10-04 10:45:51 +0200] [190051] [INFO] Server Stopped
[2021-10-04 10:45:51 +0200] [190106] [INFO] Goin' Fast @ http://127.0.0.1:5000
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Sanic auto-reload: enabled
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Sanic debug mode: enabled
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Disabling event: http.lifecycle.read_body
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Disabling event: http.lifecycle.send
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Disabling event: http.lifecycle.handle
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Disabling event: http.routing.before
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Disabling event: http.routing.after
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Disabling event: http.lifecycle.response
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Disabling event: http.lifecycle.exception
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Disabling event: http.middleware.before
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Disabling event: http.middleware.after
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Disabling event: http.middleware.before
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Disabling event: http.middleware.after
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Disabling event: http.lifecycle.read_head
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Disabling event: http.lifecycle.request
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Disabling event: http.lifecycle.begin
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Disabling event: http.lifecycle.complete
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Triggering server events: server.init.before
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Dispatching signal: server.init.before
[2021-10-04 10:45:51 +0200] [190106] [WARNING] Could not find signal server.init.before
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Triggering server events: server.init.after
[2021-10-04 10:45:51 +0200] [190106] [DEBUG] Dispatching signal: server.init.after
[2021-10-04 10:45:51 +0200] [190106] [WARNING] Could not find signal server.init.after
[2021-10-04 10:45:51 +0200] [190106] [INFO] Starting worker [190106]
```

It seems to fully and completely restart, but after that same delay ...

**Comment by cnicodeme** [comment]
Some updates on the issue: I had a hint and tested something:

If I send a request using Python `requests` package, the changes are immediate!

It seems to be something related to Chrome. The current version is **Version 92.0.4515.159 (official build) (64 bits)**

Here are the headers sent to the server:

```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: fr,en-US;q=0.9,en;q=0.8
Cache-Control: max-age=0
Connection: keep-alive
Cookie: _t=607e0d1a-b8bbabca-xxxxxxxx-050bfe4a-xxxxxxxx; install_f52876xxxxxx=xxxxxxxxt0ovnv1mtxxxxxxf2r; PHPSESSID=vu1uv127gaplxxxxxxft1jxxxx; psuid=xxxxxxxx-d9b4-4755-be86-xxxxxxxxxxxx; ps5cac92685afbxxxxxxxxxxxx=true|1632009600000; _via=site; io=PyZyz4AZ6ixxxxxxxxxx
Host: 127.0.0.1:5000
sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"
sec-ch-ua-mobile: ?0
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
```

Adding these in the headers of the Python `requests` doesn't cause the issue: the changes are still immediate.

I hope this helps a bit more.

**Comment by ahopkins** [comment]
How long is the delay?

**Comment by Tronic** [comment]
@cnicodeme Chrome keeps using the same connection for new requests, I think even when you refresh the page it still uses the same HTTP connection (i.e. keep-alive). Sanic is supposed to immediately disconnect all idle connections on server reload, but that does not appear to be working for you.

**Comment by cnicodeme** [comment]
> How long is the delay?

About 8 seconds

**Comment by ahopkins** [comment]
> @cnicodeme Chrome keeps using the same connection for new requests, I think even when you refresh the page it still uses the same HTTP connection (i.e. keep-alive). Sanic is supposed to immediately disconnect all idle connections on server reload, but that does not appear to be working for you.

We raise `KeyboardInterrupt`, which dispatches `SIGTERM` not `SIGKILL`. Not sure why you say it is "supposed to immediately disconnect all idle connections" since that is not what it is designed to do.

**Comment by Tronic** [comment]
Graceful restarts should immediately disconnect idle connections and wait for ongoing requests to finish. Maybe I only implemented this in one of my own branches and it never made to Sanic mainline, but that is how you really want to do graceful restarts to avoid old version staying around for any extended period of time.

Obviously SIGKILL would be a non-graceful way to terminate it, not something that should be used in normal circumstances.

**Comment by Tronic** [comment]
Problem reproduced.

1. Make a TCP connection to the server but do not send anything yet
2. Trigger server reload (touch source code with autoreload)
3. Wait up to request timeout (I think) to make a request, that then gets served by the old Sanic instance
4. The server actually restarts only after serving that first request, or once either REQUEST_TIMEOUT or GRACEFUL_SHUTDOWN_TIMEOUT expires with no request.

If at least one request is done on a connection prior to server restart, and the connection is idling on keep-alive, the server disconnects and restarts immediately.

This must be because when a connection is created, Sanic goes into REQUEST mode rather than in IDLE mode, so the normal graceful disconnect logic cannot kick in. I think it would be much clearer if we actually switched it so that it the connection starts IDLE and only switches once some request bytes (or even the whole header) are received. The problem with this change is that it is potentially breaking, it alters behaviour and breaks our tests for request timeout.

Browsers may create such unused connections opportunistically to improve loading speed when the next request comes, even if they do not immediately need to do any requests. A proxy such as nginx might also affect how keep-alive connections are managed.

@cnicodeme For a quick workaround to ease development, set
```
app.config.GRACEFUL_SHUTDOWN_TIMEOUT=1
```

**Comment by ashleysommer** [comment]
Hi @cnicodeme 
I noticed your original post mentions you're using Sanic 21.6.2.
Can you try it on 21.9.1? Is there any difference between the two?
There was a minor fix in this area in https://github.com/sanic-org/sanic/pull/2231, but may not be related to this issue.

**Comment by ashleysommer** [comment]
@sanic-org/core-devs 
I think it'd a good idea to set `GRACEFUL_SHUTDOWN_TIMEOUT` to `1` by default when using debug-mode or auto-reload, unless specifically set otherwise by the user. Does that sound reasonable?

**Comment by Tronic** [comment]
@ashleysommer I did my tests on the main branch, so it is still affected.

Setting the timeout is only a workaround, the problem needs to be fixed. In normal circumstances this should not be an issue. I have a PR coming, but need to figure out what to do about those failing tests first. The test clients that we have are completely unusable for testing request timeouts, and cannot be easily fixed (yeah, just spent a few hours hacking tests).

I switched the http.py logic so that the we wait for incoming bytes before entering REQUEST mode (the old implementation was to wait only after each request but not before the first one).

**Comment by ahopkins** [comment]
@Tronic I am not sure that all this breaking change is warranted. If my understanding is correct, we are talking about a very narrow scope issue in debug mode. What is the problem with the 1s workaround? Not ideal? Fine. But that is far better than breaking production apps for no good reason.

**Comment by ashleysommer** [comment]
@ahopkins After looking through PR #2268 it seems to me its not really a breaking change.
Yes, it breaks tests inside Sanic, but I don't see how the change would affect user's apps.

**Comment by ashleysommer** [comment]
@Tronic  I'm not sure that what you've reproduced is the same error as what @cnicodeme is seeing.
The error you are seeing only occurs if the client opens a connection, but does not send any data, then Sanic exits. And due to the the logic of the keepalive loop, your error only occurs on the first request, not any subsequent requests (because IDLE state is set correctly on those).

@cnicodeme is testing with Google Chrome, I don't believe its possible to create a HTTP connection without sending any data in Chrome.

**Comment by Tronic** [comment]
It is not hard to imagine that Chrome under some circumstances would immediately make two connections to the same server and then find out that there is only one resource to load, which leaves the other connection initially idle. I could not reproduce it in my Chrome but perhaps it is available on some platform or by tweaking chrome://flags or reproducing it may fail because of random factors (such as Chrome on my tests trying to load /favicon.ico which would then already use the second connection as well). 

Reproducing with a custom HTTP client was easy and reliable. As a bare minimum `nc localhost 5000` and doing nothing is an easy way to stop Sanic server from stopping until one of the timeouts expires.

**Comment by Tronic** [comment]
@ahopkins Changing GRACEFUL TIMEOUT in debug mode brings more problems than it fixes. Frequent cancellation of handlers that just need about a second to process their stuff, etc. Also any differences in behaviour between debug and production should be avoided.

The bug itself affects production as well, especially on busy sites where one minute of all requests failing on server restart might actually be relevant. While server restarts are rare in production, the *corner case* needs only one of the connected users to be in this state, and is detrimental if the server normally processes all requests quickly.
