### ISSUE TITLE
Required pytest version is broken on Python 3.10

### ISSUE THREAD

**Issue by prryplatypus** [sanic-org/sanic#2263]
**Describe the bug**
The current version of `pytest` required by Sanic (5.2.1) is incompatible with Python 3.10 and throws an exception when running tests.

**Expected behavior**
Tests run on Python 3.10.

**Additional context**
A fix was released with `pytest` version `6.2.4`. See pytest's related issue: https://github.com/pytest-dev/pytest/issues/8539.

**Comment by sjsadowski** [comment]
PEP 619 has the target date for 3.10 is 2021-10-04 (Today) so I imagine we should fix this in 21.9.X as well as for the LTS

**Comment by ahopkins** [comment]
Release is @ 17:00 UTC

After that, we will get #2257 running with whatever needed changes, and then a bump in supported versions as @sjsadowski mentioned.

**Comment by sjsadowski** [comment]
@ahopkins quick note the GH runner seems to be interpreting "3.10" as "3.1" per the test failure here: https://github.com/sanic-org/sanic/pull/2257/checks?check_run_id=3777968217

**Comment by ahopkins** [comment]
> @ahopkins quick note the GH runner seems to be interpreting "3.10" as "3.1" per the test failure here: https://github.com/sanic-org/sanic/pull/2257/checks?check_run_id=3777968217

I know. I saw that. I believe it should be using `310-rc`. But, did not dig into it further since the release is imminent and I imagine the regular release version is not far behind.
