### ISSUE TITLE
Releases removed from right side bar on GitHub

### ISSUE THREAD

**Issue by robd003** [sanic-org/sanic#2265]
For some reason the "Releases" section isn't showing up on the right side bar on GitHub. At the moment if you want to view releases you have to click on Tags and then select releases. Why was this removed?

Here's a quick link for those who can't find it: https://github.com/sanic-org/sanic/releases

**Comment by ahopkins** [comment]
I removed it because GH is showing 20.12 as the "latest" release. I'd rather show none than to confuse until we can get another commit and release.
