### ISSUE TITLE
A way to globally set `ignore_body` to False/True

### ISSUE THREAD

**Issue by autumnjolitz** [sanic-org/sanic#2266]
I'm in the process of upgrading our API to a recent Sanic from 19.x.y version. The clients are not just a browser but API-driven ones like `requests` et al. Which means helper routes like sending a `DELETE /path\r\n\r\n{"json": "body"}` exist. I'm finding I have to annotate **every single** `.delete` route with `, ignore_body=False`

Is there a way to set this globally?

**Comment by autumnjolitz** [comment]
I've used the following command to simplify annotating every. single. route:
```
awk '/\@/ && /.delete\(/ && ! /ignore_body=False/ {printf("+%s %s\n", FNR, FILENAME)}' api/*.py | xargs -o -L1 vi
```

**Comment by ahopkins** [comment]
You could do it in Middleware 

```python 
@app.on_request
async def drain(request):
    if request.method == "DELETE":
        await request.receive_body()
```
