### ISSUE TITLE
app.stop() does not run tasks to completion

### ISSUE THREAD

**Issue by Tronic** [sanic-org/sanic#2267]
Stopping the app instantly drops all existing tasks, meaning that try-finally sections, context manager exits etc. do not get executed. This is bad. Tasks should get cancelled and then run to completion prior to stopping the loop.

I suppose one should use `loop.run_until_completion()` if doing such manual management of asyncio loops. The modern way of course is to remove the explicit loop passing and handling entirely, like asyncio have done in the last few Python versions, but that with Sanic would be a huge undertaking. (deprecation and removal of loop arguments on public APIs would be a start though)

**Comment by ahopkins** [comment]
There has been discussion (on my phone will look later) about adding more task tracking and providing a similar graceful shutdown experience after connection task shutdown.
