### ISSUE TITLE
`websocket_handshake` invalid function signature

### ISSUE THREAD

**Issue by cnicodeme** [sanic-org/sanic#2272]
**Describe the bug**
The function `websocket_handshake` located in sanic.server.protocols.websocket_protocol has an invalid signature in Sanic 21.9.2 (at least)

**Code snippet**
Current code is:

```
    async def websocket_handshake(
        self, request, subprotocols=Optional[Sequence[str]]
    ):
```

**Expected behavior**
Code should be:

```
    async def websocket_handshake(
        self, request, subprotocols:Optional[Sequence[str]] = None
    ):
```

=> Typing should be set with ":", not "=" ;)

**Environment (please complete the following information):**
 - Version 21.9.2

**Comment by ahopkins** [comment]
@cnicodeme Can you add a PR for this, and I can get a patch released this weekend.

**Comment by cnicodeme** [comment]
Let me know if that works :)

**Comment by cnicodeme** [comment]
You are welcome! That was an easy one to fix ;)

(But I don't know why it refuses my PR, maybe some wrong code formatting)
