### ISSUE TITLE
Can no longer async stream fragmented message through 21.9 websockets

### ISSUE THREAD

**Issue by tylersalminen** [sanic-org/sanic#2281]
In the legacy Webscokets implementation you could async stream a fragmented response through the websocket using an AsyncIterator. This seems to not be supported anymore in the 21.9 sanic implementation of websockets as the websocket.send() now only accepts str or bytes. Iterables seem to have a not implemented placeholder in the source (sanic.server.websockets.impl.WebsocketImplProtocol.send()). Is this a feature that will be added in the future?

Example:
```python

websocket.send(async_response_stream_iterator())

async def async_response_stream_iterator():

    yield b"binary data fragment 1"
    yield b"binary data fragment 2"


```

**Comment by ahopkins** [comment]
Can you provide a sample snippet?

**Comment by ChihweiLHBird** [comment]
I think you can try:

```python
async for item in async_response_stream_iterator():
    await websocket.send(item)
```

**Comment by ahopkins** [comment]
@tylersalminen Thanks for the snippet. TBH, this was never an intended API. That it was working I suppose is more by accident than by an intentional decision. But, with that said I do think it is feasible to add support for this.

**Comment by ChihweiLHBird** [comment]
> @tylersalminen Thanks for the snippet. TBH, this was never an intended API. That it was working I suppose is more by accident than by an intentional decision. But, with that said I do think it is feasible to add support for this.

Maybe we can just wrap a for loop and an async for loop to handle iterator in our WebSocket API? Like:

```python
elif isinstance(message, Iterable):
    if isinstance(message, AsyncIterable):
        async for msg in message:
            self.send(msg)
    else:
        for msg in message:
            self.send(msg)
```

But it can also be done in the user defined websocket handler.

**Comment by ahopkins** [comment]
@ChihweiLHBird 

```python
>>> from typing import Iterable
>>> isinstance("abc", Iterable)
True
```

**Comment by ChihweiLHBird** [comment]
> @ChihweiLHBird
> 
> ```python
> >>> from typing import Iterable
> >>> isinstance("abc", Iterable)
> True
> ```

It looks that `str` should be taken care by a previous `if`

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/43905414/147644274-a3f28c5e-e197-475f-a0b4-2fb382f9195b.png">

**Comment by ChihweiLHBird** [comment]
But I think doing it in handler is not a bad idea, so we don't have to support this in `websocket.send()`……

**Comment by ahopkins** [comment]
Exactly. That is the question: should we support this or not. It was never an official feature. I of course hate adding breaking changes. But the real question is whether we should add the complexity to support this or not.

**Comment by ahopkins** [comment]
@ashleysommer Do you have a take on this?

**Comment by tylersalminen** [comment]
Perhaps I can add some clarification as to what I am trying to accomplish:

I do not want to send multiple _messages_ asynchronously, this can already be accomplished through the existing apis available to the developer. What I am trying to do is send a _single_ message that is fragmented over multiple, asynchronously available, fragments. This hypothetical api would be the analogue to your existing websocket.recv_streaming() api except it would be for _sending_ messages to client instead of receiving them. From the client's perspective the message would still  receive as a single message, just fragmented. 

Furthermore, It would be ideal if one could "multiplex" the fragments of multiple messages. I.e. lets say message 1 is split into 5 fragments (again these fragments are available asynchronously, you can think of them as loaded from an external database, each fragment being available at future unknown points in time), and only the first fragment is ready to send, fragment 2 - 5 have not been prepared / received / etc. yet. So the first fragment of message 1 is sent. Then, while the first fragment of message 1 is still being sent, the first fragment of a second message, message 2 (which is split into 3 fragments) is ready to send. So fragment 1 of message 2 is queued up to send. Here is an example illustrating how the fragments would ideally be sent to the client. 

message 1, fragment 1
message 2, fragment 1
message 1, fragment 2
message 1, fragment 3
message 1, fragment 4
message 2, fragment 2
message 2, fragment 3 (client has fully received message 2 at this point)
message 1, fragment 5 (client has fully received message 1 at this point)

As you can see what I desire is that a fragment of any particular message is sent to the client as soon as possible as there could realistically be non-trivial time between availability of fragments of a single message in which another message's fragment's could opportunistically be sent (i,e. would not want the api to lock / queue across messages but instead across fragments).

**Comment by ChihweiLHBird** [comment]
> 

Did you try the async for loop I suggested above? I think with it you can send multiple messages asynchronously with it. 

**Server**
```python
import asyncio, random
from sanic import Sanic

app = Sanic("TestApp")

async def async_response_stream_iterator(msg_id: str):
    for i in range(3):
        await asyncio.sleep(random.uniform(0, 0.5)) # Mock loading data
        yield f"message {msg_id}, fragment {i}"

@app.websocket("/")
async def hello_world(request, ws):
    msg_id = await ws.recv()
    async for item in async_response_stream_iterator(msg_id):
        await ws.send(item)
        print(f"Sent {item}")

app.run(host='localhost', port=8000, debug=True, workers=5)
```

**Client**

```python
import asyncio
import websockets

async def hello(msg_id: int):
    uri = "ws://localhost:8000"
    async with websockets.connect(uri) as websocket:
        await websocket.send(f"{msg_id}")
        for i in range(3):
            msg = await websocket.recv()
            print(msg)

async def multiple_calls():
    tasks = []
    for i in range(5):
        tasks.append(asyncio.create_task(hello(i)))
    for task in tasks:
        await task

asyncio.run(multiple_calls())
```


**Client Outputs**

```
message 2, fragment 0
message 3, fragment 0
message 4, fragment 0
message 1, fragment 0
message 2, fragment 1
message 1, fragment 1
message 0, fragment 0
message 4, fragment 1
message 3, fragment 1
message 3, fragment 2
message 2, fragment 2
message 1, fragment 2
message 0, fragment 1
message 4, fragment 2
message 0, fragment 2
```

**Comment by ashleysommer** [comment]
Sorry I'm late to the party on this one, I must've missed it in my inbox.

During the development of the new Websockets backend before the release Sanic 21.9, I spoke briefly to the the `websockets` developer @aaugustin about specifically this issue, that is, a  _single_ message, over multiple fragments as described by @tylersalminen . Short story, is that is very difficult to do using the new `websockets` sans-io interface, and no supported by the sans-io interface (as far as I am aware).

It is not as simple as an iterator generating multiple messages to send, that pattern is easily implemented at the handler level as shown by others in this thread.

The new Sanic Websockets backend has no inter-message state. It communicates data to send directly to the `websockets` sans-io api layer, which does its own state management. Its probably possible to manipulate the api to get fragement-level sends working, but as I said, I don't think that is a supported usage pattern.

**Comment by aaugustin** [comment]
Hello!

I can confirm that:

- this used to work in previous version of Sanic, as it got the feature transparently when I added it in websockets;
- AsyncIterator is interesting; Iterator isn't — benefits are very limited if you can't yield control between fragments;
- Sans-I/O prohibits any code tied to a concurrency model; AsyncIterator cannot be supported at the Sans-I/O layer.

There are two tricks to be aware of in this feature:

- you have to block other send() calls while you're sending an AsyncIterator, else you're going to break the protocol; websockets will raise an exception rather than let you do that;
- you have to ensure that all fragments have the same type.

If you wanted to support this, you would have to steal relevant bits from here:

https://github.com/aaugustin/websockets/blob/b6a254ed20d54806b245bb6088881078e95753af/src/websockets/legacy/protocol.py#L564-L722

and then replace `self.write_frame`, `self.fail_connection`, etc. by their equivalent in the Sans-I/O layer.

**Comment by ashleysommer** [comment]
Thanks @aaugustin 
Looks like I might be able to get partial support for this working using AsyncIterator, and blocking other sends. There however would not be any way of doing more than one fragmented message at the same time, as described by @tylersalminen.

**Comment by ahopkins** [comment]
Is this even a legitimate use case? If the goal is to not miss a ping then it seems like what should happen is that the message itself should be broken up to be deliverable under the ping interval.

**Comment by aaugustin** [comment]
I would have a hard time giving a good use case.

I have anecdotal evidence that sending fragmented messages is rare. It took several years I introduced compression in websockets until someone noticed that I misunderstood the spec and that browsers would reject fragmented, compressed messages generated by websockets. Compression was enabled by default. This shows that almost no one uses fragmentation.

"We don't support fragmentation, sorry" is a defensible position. I think the amount of time I spent supporting fragmentation in websockets is out of proportion of the usefulness of this "feature" in the real world.

**Comment by ahopkins** [comment]
@aaugustin That's fair enough.

In the rare case when this is needed, I think the answer will have to be that Sanic and websockets should be run separately:

```python
from websockets import serve

async def echo(websocket):
    async for message in websocket:
        await websocket.send(message)


@app.before_server_start
async def start_websockets(app: Sanic, _):
    app.ctx.ws = await serve(echo, "localhost", 8765)


@app.before_server_stop
async def stop_websockets(app: Sanic, _):
    app.ctx.ws.ws_server.close()
    await app.ctx.ws.ws_server.wait_closed()
```
