### ISSUE TITLE
Websockets Module Not Found Error

### ISSUE THREAD

**Issue by darkerego** [sanic-org/sanic#2343]
Library fails upon import with this traceback:

Traceback (most recent call last):
  File "/DistribScan/server.py", line 7, in <module>
    from sanic import Sanic, response
  File "/usr/local/lib/python3.9/dist-packages/sanic/__init__.py", line 2, in <module>
    from sanic.app import Sanic
  File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 77, in <module>
    from sanic.server.protocols.websocket_protocol import WebSocketProtocol
  File "/usr/local/lib/python3.9/dist-packages/sanic/server/protocols/websocket_protocol.py", line 3, in <module>
    from websockets.connection import CLOSED, CLOSING, OPEN
ModuleNotFoundError: No module named 'websockets.connection'

Testing on a few different systems.

**Comment by ChihweiLHBird** [comment]
```
>>> from sanic import Sanic
>>> from sanic.app import Sanic
>>> from sanic.server.protocols.websocket_protocol import WebSocketProtocol
>>> from websockets.connection import CLOSED, CLOSING, OPEN
```

works fine on my machine. Can you share a sample code snippet that causes the issue? Thanks!

**Comment by darkerego** [comment]
Sure. Did you build your Sanic with the latest code on here? This crashes on every install I've done;

from sanic import Sanic

**Comment by ChihweiLHBird** [comment]
I just did `pip install git+https://github.com/sanic-org/sanic` and then in Python `from sanic import Sanic` on Windows 11, seems fine. Did you try reinstall sanic?

**Comment by darkerego** [comment]
Yeah, several times but strange I ran on another system and it's okay. What version of websockets do you have installed?

**Comment by darkerego** [comment]
Oh wow. I am an idiot, I am so sorry. I had a directory called 'websockets' in the same folder as my script.

**Comment by ChihweiLHBird** [comment]
😂

**Comment by ahopkins** [comment]
I think we've all been there
