### ISSUE TITLE
LIGHTGBM pickle output not working with multiple SANIC workers (>1) but working with single worker.

### ISSUE THREAD

**Issue by pratikshach** [sanic-org/sanic#2359]
I am trying to load machine learning model output with Sanic. I have loaded the output in the main method(defined globally). It works fine when I set sanic worker as 1 but not not working with multiple sanic workers when defined globally. My code waits for indefinite time for model to generate desired result.

> **Its works** when I load model output inside the function (e.g. here in the method **modelrun**) even if sanic workers >= 1

> **It works** when I load model output globally(outside the function) but only if sanic workers = 1

> **It doesnot** work when I load model output globally(outside the function) if sanic workers > 1

# Versions used 
python 3.8
sanic==20.12.1
lightgbm==3.3.1
numpy==1.20.1
pandas==1.2.4
scikit-learn==1.0.2
scipy==1.6.2

# Code

```
import pickle
import sanic

# endpoint model run
@app.route("/get_data", methods=['POST'])
async def get_model_output(request):
    output = modelrun(df, lbg_model_smote_sel_vars)
    return output

if __name__ == '__main__':
    df = pd.DataFrame()
    p_file_path = "/Users/pratiksha/radar/Radar/utils/static_data/FModel_06Jan_Smote_Sel_Vars_48.dat"
    pickle_file = open(path, 'rb')
    lbg_model_smote_sel_vars = pickle.load(pickle_file)

    app.run(host=app_host, port=int(app_port), debug=True,
            auto_reload=True, workers=int(10))

# defined in other directory
def modelrun(df_f, lbg_model_smote_sel_vars):
    training_pred_smote = lbg_model_smote_sel_vars.predict_proba(df_f)
    return training_pred_smote
```

stack trace

```
2022-01-06 16:32:02,391 - sanic.root - INFO - Goin' Fast @ http://127.0.0.1:8000
2022-01-06 16:32:02,428 - sanic.root - INFO - Starting worker [6047]
2022-01-06 16:32:02,431 - sanic.root - INFO - Starting worker [6048]
2022-01-06 16:32:02,433 - sanic.root - INFO - Starting worker [6049]
2022-01-06 16:32:02,439 - sanic.root - INFO - Starting worker [6050]
2022-01-06 16:32:02,442 - sanic.root - INFO - Starting worker [6051]
2022-01-06 16:32:02,444 - sanic.root - INFO - Starting worker [6052]
2022-01-06 16:32:02,447 - sanic.root - INFO - Starting worker [6053]
2022-01-06 16:32:02,450 - sanic.root - INFO - Starting worker [6054]
2022-01-06 16:32:02,451 - sanic.root - INFO - Starting worker [6055]
2022-01-06 16:32:02,453 - sanic.root - INFO - Starting worker [6056]
```

**Comment by ahopkins** [comment]
When you have multiple workers, Sanic will start a main process that manages several subprocesses. These subprocesses will be the application server workers.

Since you are doing all of the loading inside `__main__`, the application workers never see that.

**Comment by pratikshach** [comment]
> 

How it works for other global varibales then? If i define it at import level it doesnot work.

**Comment by ahopkins** [comment]
I am not sure I see how this is a Sanic issue. I am not sure what you mean by "works fine". If you want something available per application you really should not be doing anything in the global scope.

```python
@app.get("/")
async def handler(request: Request):
    return json({"foo": request.app.ctx.dummy})


@app.main_process_start
async def dummy(app, _):
    app.ctx.dummy = 1
```

This might work in some cases. But I would almost *NEVER* recommend this.

Much safer and more reliable to do it in the worker process:
```python

@app.before_server_start
async def dummy(app, _):
    app.ctx.dummy = 1
```

**Comment by pratikshach** [comment]
Beacuse the code works if I define sanic workers=1 but not with multiple workers. So unable to debug the issue. I tried it with listener but didn't work.
PS- have updated code for better understanding.

**Comment by ahopkins** [comment]
That is because when you run with 1 worker you are not in a subprocess. This is why I am suggesting that you need to move the code to a listener if you want all workers to run it.

**Comment by pratikshach** [comment]
I ran below piece of code, didn't work. I think the problem is with preloading the pickle output in the workers. Please refer the stack trace.
```
@app.listener("before_server_start")
async def listener_1(app, loop):
    logger.info("loading in listener")
    models_vars = get_model_value(p_file_path)
    logger.info(models_vars)
    return models_vars
```
        
Stack Trace:
```
2022-01-07 12:48:09,158 - sanic.root - INFO - Goin' Fast @ http://127.0.0.1:8000
2022-01-07 12:48:09,183 - sanic.root - INFO - loading in listener
2022-01-07 12:48:09,191 - sanic.root - INFO - loading in listener
2022-01-07 12:48:09,188 - sanic.root - INFO - loading in listener
2022-01-07 12:48:09,194 - sanic.root - INFO - loading in listener
2022-01-07 12:48:09,198 - sanic.root - INFO - loading in listener
2022-01-07 12:48:09,196 - sanic.root - INFO - loading in listener
2022-01-07 12:48:09,202 - sanic.root - INFO - loading in listener
2022-01-07 12:48:09,203 - sanic.root - INFO - loading in listener
2022-01-07 12:48:09,207 - sanic.root - INFO - loading in listener

```

**Comment by ahopkins** [comment]
Yes. that is what I was trying to say. You need to run that in the process you want it available in. It will not sync automatically.

**Comment by pratikshach** [comment]
I have latency issues. I don't want to load pickle file everytime.

**Comment by SaidBySolo** [comment]
https://sanicframework.org/en/guide/basics/listeners.html

Check out the cycle here.

After loading the pickle, it seems to be solved by adding it to the context property.

**Comment by ahopkins** [comment]
As mentioned by @SaidBySolo, this is the supported pattern.

**Comment by pratikshach** [comment]
Thanks, @SaidBySolo. I upgraded the Sanic version and now it is working with the context property. 
Still didn't get one thing is that why the pickle was not loaded in the listener with a local variable. It is a generic python function. I did not get any errors in that process. Is there any Sanic process involved which was failing because of this and I was not getting any error for that?

**Comment by sysu18364109** [comment]
> Thanks, @SaidBySolo. I upgraded the Sanic version and now it is working with the context property. Still didn't get one thing is that why the pickle was not loaded in the listener with a local variable. It is a generic python function. I did not get any errors in that process. Is there any Sanic process involved which was failing because of this and I was not getting any error for that?

Hey, I have encounter the same problem, also discovered that loading global variables that defined in `__main__` into the workers doesn't work. In my case, I have tried to load a yolov4 model in `__main__` and use the same model object among these workers. But it failed, sanic workers were just blocking somewhere. If I load a new model to the context per worker in `before_server_start` , it works, but several times of GPU memory are consumed. So I wondered if global variables are not visible in multiple worker cases, and duplicate these variables/objects into the context is the only solution?

**Comment by sjsadowski** [comment]
@sysu18364109 because the workers do not have a shared context. You're consuming more memory for each individual worker, as expected, because the model is loaded in each worker.

If you want a shared worker context and want to use something prebuilt, take a look at https://github.com/ashleysommer/sanic-synchro-ctx

**Comment by sysu18364109** [comment]
> @sysu18364109 because the workers do not have a shared context. You're consuming more memory for each individual worker, as expected, because the model is loaded in each worker.
> 
> If you want a shared worker context and want to use something prebuilt, take a look at https://github.com/ashleysommer/sanic-synchro-ctx

 @sjsadowski 
Thanks for your reply! I have tried the link you posted here, but sadly it seems that a complex object (in my case it was a yolov4 model, a class inherited from class nn.Module) is not serializable, while list or other basic types do works. What I got in the debug info is like:
`Unserializable message: Traceback (most recent call last):
......
RuntimeError: Attempted to send CUDA tensor received from another process; this is not currently supported. Consider cloning before sending.`
The author also said that:

> I don't think you can pass an instantiated object between workers, unless that object can be pickeled. Python needs to covert the instantiated object into a pickle object in order to send it between workers, and some things simply cannot be picked.
So it is still not possible for me to share a model object among these workers :-( . Sorry for disturbing you again, is there any other solution that suits this case, or will Sanic be able to support object sharing in a further version?

**Comment by ahopkins** [comment]
This is not a Sanic issue, but a Python issue. Anything that you want to share between processes should be serialized first and then rehydrated into an object in each process. This would be the normal/recommended pattern. If you have specific questions and would like some more help on your specific issue, post some code on the Community forums and myself or someone else will be happy to take a look.

**Comment by ahopkins** [comment]
This issue has been mentioned on **Sanic Community Discussion**. There might be relevant details there:

https://community.sanicframework.org/t/share-a-model-object-among-multiple-workers/1010/1

**Comment by sysu18364109** [comment]
> This issue has been mentioned on **Sanic Community Discussion**. There might be relevant details there:
> 
> https://community.sanicframework.org/t/share-a-model-object-among-multiple-workers/1010/1

Ahh, actually I have posted this question just now LOL. Please take a look at it if you are convenient.
