### ISSUE TITLE
Update websockets dependency for security remediation

### ISSUE THREAD

**Issue by sjsadowski** [sanic-org/sanic#2367]
**Describe the bug**
Websockets 9.0.x has a security issue with remediation introduced in 9.1

**Additional context**
Closed by #2366

**Comment by ChihweiLHBird** [comment]
This issue was completed as we now have `websockets>=10.0` in the `setup.py` file in both main and LTS branches.
https://github.com/sanic-org/sanic/blob/d4041161c79f949766102ebc2023c136b8f2cb73/setup.py#L92
