### ISSUE TITLE
Wrong typing for app.listener decorator

### ISSUE THREAD

**Issue by aericson** [sanic-org/sanic#2375]
**Describe the bug**
Mypy accuses typing errors on the `@app.listener` decorator.

I'll try to put a PR later if I can manage to fix it 😄 

**Code snippet**
```python
from sanic import Sanic
from sanic.response import text
from asyncio import AbstractEventLoop

app = Sanic("MyHelloWorldApp")

@app.get("/")
async def hello_world(request):
    return text("Hello, world.")


@app.listener("before_server_start")
async def setup_db(app, loop: int):
    pass
```

```
mypy --pretty hello.py   
hello.py:12: error: Too few arguments
    @app.listener("before_server_start")
     ^
hello.py:12: error: Argument 1 has incompatible type "Callable[[Any, int], Coroutine[Any, Any, Any]]"; expected <nothing>
    @app.listener("before_server_start")
     ^
```

Both `app.before_server_start` decorator and `app. register_listener ` works fine.

**Expected behavior**
Should have the correct typing.

**Environment (please complete the following information):**
```
pip list
Package           Version
----------------- -------
aiofiles          0.8.0
httptools         0.3.0
multidict         5.2.0
mypy              0.931
mypy-extensions   0.4.3
pip               21.3.1
sanic             21.12.1
sanic-routing     0.7.2
setuptools        58.1.0
tomli             2.0.0
typing_extensions 4.0.1
ujson             5.1.0
uvloop            0.16.0
websockets        10.1
```
- Tested on python 3.9 and 3.10

**Additional context**

**Comment by Tronic** [comment]
Partially related: the loop argument should be deprecated. I suppose the listener registration should look at how many arguments the callable expects so that listeners don't need to take the loop argument anymore but that the old ones, that do, keep working with a deprecation warning.

**Comment by ahopkins** [comment]
@Tronic I agree :100: I made this exact change at one point. I cannot remember on what branch it was and it clearly was never merged. But yes, we should definitely do that.

**Comment by ahopkins** [comment]
FWIW this feature was added in the last release.

**Comment by sjsadowski** [comment]
Closing per @ahopkins comment
