### ISSUE TITLE
request.scheme not found https?

### ISSUE THREAD

**Issue by a224327780** [sanic-org/sanic#2385]
![image](https://user-images.githubusercontent.com/78008038/150634708-abb8e36a-b728-4162-9794-e5a7e1166fb0.png)

```
@app.get('/')
async def home(request: Request):
    return text(request.scheme)
```

- https rquest  return http?

**Comment by sjsadowski** [comment]
There's not enough detail here to identify what's going on. Please provide a larger set of code, including how you're running sanic (using cli, an ASGI handler, etc) and then finally how you're accessing it. From the image above it looks like you might be using ngrok or inlets.

**Comment by a224327780** [comment]
> There's not enough detail here to identify what's going on. Please provide a larger set of code, including how you're running sanic (using cli, an ASGI handler, etc) and then finally how you're accessing it. From the image above it looks like you might be using ngrok or inlets.

sanic main.app --host=0.0.0.0 --port=8080 --fast --access-logs

**Comment by sjsadowski** [comment]
Sanic is running in http mode on port 8080. So the scheme is correct. Are you accessing it through a proxy, or through a secure https tunnel like ngrok or inlets?

The reason I ask is https does not run on port 8080, and from the above I cannot see where you are specifying a port, so something is terminating the https request and forwarding it to Sanic.

**Comment by a224327780** [comment]
I deployed in render.com
### Dockerfile
```
FROM python:3.7-bullseye

COPY . /data/python

WORKDIR /data/python

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

CMD sanic main.app --host=0.0.0.0 --port=8080 --fast --access-logs
```
### main.py
```
@app.get('/')
async def home(request: Request):
    return text(request.scheme)
```
- request https://nq.onrender.com/ return http?

**Comment by ahopkins** [comment]
As @sjsadowski said, you are not encrypting your HTTP calls into Sanic. It is reporting correctly. Somewhere in front of Sanic is a proxy that is terminating the TLS connection and converting the request from HTTPS to HTTP. Therefore, what Sanic sees is indeed `http` as it is reporting. This is not necessarily a bad thing as long as that is happening inside of a private network. [It seems that your host is automatically setting up TLS for you](https://render.com/docs/tls).

I am closing this as it is not an issue, but please feel free to continue asking questions. It seems like you may be confused about how the proxy works.
