### ISSUE TITLE
distutils.strtobool deprecation 

### ISSUE THREAD

**Issue by sjsadowski** [sanic-org/sanic#2388]
**Describe the bug**
he distutils package is deprecated and slated for removal in Python 3.12. [PEP 632](https://www.python.org/dev/peps/pep-0632/)

**Code snippet**
[sanic/server/loop.py](https://github.com/sanic-org/sanic/blob/ac388d644b1e22156e228470fad8ea34932c080a/sanic/server/loop.py#L3)

**Expected behavior**
A lack of warnings about deprecation

**Environment (please complete the following information):**
 - OS: All
 - Version: All supported as of 2022/01/23 

**Additional context**
This is housekeeping to clean up a core python deprecation.

**Comment by sjsadowski** [comment]
Note: Even though this is an exceptionally minor fix, I don't feel like this should be backported to 20.12LTS. 20.12LTS will sunset long before 3.12 is past alpha (and possibly before 3.11.0 final hits, depending on if the timeline in [PEP 664](https://www.python.org/dev/peps/pep-0664/) is hit or not) and that makes it likely that 21.12LTS will be the only backport needed, if any.

**Comment by ahopkins** [comment]
No backport will be needed because 21.12 does not (an will not) purport to support 3.12. It is 3.7-3.10 and that will not change. We probably should add Python versions here: https://sanic.dev/en/org/policies.html#release-schedule.

**Comment by ChihweiLHBird** [comment]
I think we still need to fix this, right? Any update?

**Comment by ahopkins** [comment]
This is still something to do, just not something that we need to release back to the LTS.

**Comment by jacebrowning** [comment]
This is still an issue: https://github.com/sanic-org/sanic/blob/4726cf1910fe7735ac0944504b02fc4f3d89d5fd/sanic/server/loop.py#L4

**Comment by ahopkins** [comment]
Anyone want to take a crack at this in the next couple days to get into the LTS?
