### ISSUE TITLE
Unexpected behaviour when using routing with multiple variables 

### ISSUE THREAD

**Issue by ahankinson** [sanic-org/sanic#2391]
**Describe the bug**
Multiple path variables in a route are not correctly parsed. The route handler looks beyond the end of the path and matches on a more specific resource when it should not.

**Code snippet**
```python
from sanic import Sanic, response

app = Sanic("test-args")

@app.route("/test2/<first:str>/")
async def test2_firstarg_annotated(req, first:str):
    return response.text(f"test2 arg handler with a value of {first}.")

@app.route("/test2/<first:str>/fixed/")
async def test2_firstarg_fixed(req, first:str):
    return response.text(f"test2 arg handler with a value of {first} and fixed in-between value.")

@app.route("/test2/<first:str>/fixed/<second:str>/")
async def test2_firstarg_secondarg(req, first:str, second:str):
    return response.text(f"test2 arg handler with a value of {first} and a second argument of {second}.")

if __name__ == "__main__":
    app.run(debug=True, access_log=True)
```

**Expected behavior**

In the sample code, visiting `http://localhost:8000/test2/firstarg/` results in the correct response. However, visiting `http://localhost:8000/test2/firstarg/fixed/` results in the server skipping the specific handler designed for this route, `test2_firstarg_fixed` and instead uses the more specific `test2_firstarg_secondarg`. This hander should only be called if there was an additional parameter supplied, e.g., `http://localhost:8000/test2/firstarg/fixed/secondarg`.

The value for `second` in `test2_firstarg_secondarg` is then `None` in the failure case. 

I would expect that `test2_firstarg_secondarg` is only called when there is an additional second variable supplied in the path of the request.

**Environment (please complete the following information):**
 - OS: macOs Latest
 - Version: 21.12.1

**Additional context**
I am quite sure this is a regression, and that it used to work...

**Comment by ahopkins** [comment]
https://sanic.dev/en/guide/basics/routing.html#strict-slashes

```python
@app.route("/test2/<first:str>/fixed/", strict_slashes=True)
```

https://github.com/sanic-org/sanic/issues/2384#issuecomment-1017856366

---



> The value for `second` in `test2_firstarg_secondarg` is then `None` in the failure case.

It should not be `None`, the value should be an empty string `""`.

**Comment by ahankinson** [comment]
Thank you for your response. Yes, you are right -- it is an empty string.

I still think this is unexpected behaviour. If I have:

`@app.route("/test2/<first>/fixed/")`

And put as my URL:

`http://localhost:8000/test2/firstarg/fixed/`

that is, matching the slashes exactly in the request, then the handler is not selected and it goes to the second one. If I change it to add `strict_slashes` on the decorator, then it works as expected.

I would expect that `strict_slashes=True` would consider `http://localhost:8000/test2/firstarg/fixed/` and `http://localhost:8000/test2/firstarg/fixed` to be different paths, while `False` is to consider routes with and without trailing slashes to be the same.

I'm still not sure why the second handler is chosen. A route that is missing a complete path segment should cause a 404, rather than resolving into another route with an empty string value, shouldn't it?

In any case, the docs that you pointed to do not mention this behaviour anywhere that I could see. I did read them, but since I was matching the path exactly in my request, I did not think to check that this was a problem.

**Comment by ahopkins** [comment]
> I would expect that `strict_slashes=True` would consider `http://localhost:8000/test2/firstarg/fixed/` and `http://localhost:8000/test2/firstarg/fixed` to be different paths, while `False` is to consider routes with and without trailing slashes to be the same.

Well, this is the case. If you did not have the second route, you would find that to be the case. The problem is that `str` matches on anything that can be converted to a `str`, even an empty string. This is something that I am considering to change in the next version. FWIW, you could use `alpha` or a custom matching if `strict_slashes` is not the right approach for you. What I am trying to consider now is whether the default behavior for `str` to allow empty strings needs to change, or we should create a non-empty string type as well.

> In any case, the docs that you pointed to do not mention this behaviour anywhere that I could see. I did read them, but since I was matching the path exactly in my request, I did not think to check that this was a problem.

I will likely be adding some documentation on this soon. Thanks for the heads up and I am sorry for any confusion it caused you.

---

Here is an alternative solution for you:

```python
# First, we define our own parameter pattern check
def non_empty_str(value: str) -> str:
    if not value:
        raise ValueError
    return value

# Then, register it
app.router.register_pattern(
    "nonempty",
    non_empty_str,
    r"^[^/]+$",
)


# No change
@app.route("/test2/<first:str>/")
async def test2_firstarg_annotated(req, first: str):
    return response.text(f"test2 arg handler with a value of {first}.")

# No change
@app.route("/test2/<first:str>/fixed/")
async def test2_firstarg_fixed(req, first: str):
    return response.text(
        f"test2 arg handler with a value of {first} and fixed in-between value."
    )

# Change the second param from str to nonempty
@app.route("/test2/<first:str>/fixed/<second:nonempty>/")
async def test2_firstarg_secondarg(req, first: str, second: str):
    return response.text(
        f"test2 arg handler with a value of {first} and a second argument of {second}."
    )
```

Here are the results:

```
╭─sanic on  main [$⇣] via  v3.10.1 (sanic) 
╰─▶ curl localhost:9999/test2/foo localhost:9999/test2/foo/
test2 arg handler with a value of foo.
test2 arg handler with a value of foo.

╭─sanic on  main [$⇣] via  v3.10.1 (sanic) 
╰─▶ curl localhost:9999/test2/foo/fixed localhost:9999/test2/foo/fixed/
test2 arg handler with a value of foo and fixed in-between value.
test2 arg handler with a value of foo and fixed in-between value.

╭─sanic on  main [$⇣] via  v3.10.1 (sanic) 
╰─▶ curl localhost:9999/test2/qqq/fixed/bar localhost:9999/test2/qqq/fixed/bar/
test2 arg handler with a value of qqq and a second argument of bar.
test2 arg handler with a value of qqq and a second argument of bar.
```

**Comment by ahankinson** [comment]
Thank you very much! Your responsiveness is appreciated. Thank you also for pointing me to the ability to provide custom handlers!

The example I posted is made up, but the real-world use case for my routes were:

- `/resource/<identifier:str>/subresource/`
- `/resource/<identifier:str>/subresource/<subid:str>/`

That is, a path that would list all "subresources" and then a path to select a specific sub-resource. In this case, the handler for the specific sub-resource path (the second one) was always being selected, even if I put the path to the first in directly.

I also want `/resource/<identifier:str>/subresource/` and `/resource/<identifier:str>/subresource` to be equivalent (`strict_slashes=False`), so it seems that in the current setup I can't have both -- I can't have two paths equivalent without slashes, but then I can't also have correct sub-resource handling.
