### ISSUE TITLE
Add websocket closed

### ISSUE THREAD

**Issue by tuna2134** [sanic-org/sanic#2393]
**Is, your feature request related to a problem? Please describe.**
I want to check websocket closed.

**Describe the solution you'd like**
Check a websocket is closed.

**Additional context**
ws.closed

**Comment by sjsadowski** [comment]
Please clarify - you want to detect if the client has closed the connection?

**Comment by tuna2134** [comment]
yeah

**Comment by sjsadowski** [comment]
This is ultimately your responsibility (code-wise) to handle the websockets. If a client closes a websocket expectedly, it can certainly send a message, but the server must detect if the websocket is still open, so best practice would be to wrap your send function in a try/except block and use that to handle the client termination gracefully.

Sanic's websocket functionality is based on websockets 10.x at this time, read up on the exception it throws for interacting with closed connections here:
https://websockets.readthedocs.io/en/stable/reference/exceptions.html#websockets.exceptions.ConnectionClosed
