### ISSUE TITLE
URL parse needs better error

### ISSUE THREAD

**Issue by fredlllll** [sanic-org/sanic#2394]
a weird stacktrace popped into my log out of nowhere and i have no idea waht triggered it or what it means

paste of the code cause githubs "code" removes formatting https://pastebin.com/uFgw9hyk

**Comment by sjsadowski** [comment]
**Is your feature request related to a problem? Please describe.**
Problem: when httptools parses a url with an incomplete or invalid schema, the server returns a 500 error instead of a 400 BAD REQUEST

**Describe the solution you'd like**
properly return 400 BAD REQUEST
