### ISSUE TITLE
Blueprint serve directory for each host with same route

### ISSUE THREAD

**Issue by anbuhckr** [sanic-org/sanic#2399]
**Is your feature request related to a problem? Please describe.**
Problem: when registered blueprint static directory with different host only last blueprint route is registered
```python
from sanic import Sanic
from sanic.blueprints import Blueprint

app = Sanic(__name__)

bp1 = Blueprint('bp1', host='domain.com')
bp2 = Blueprint('bp2', host='api.domain.com')

bp1.static("/images", "./domain/images", host="domain.com")
bp2.static("/images", "./subdomain/images", host="api.domain.com")

app.blueprint(bp1)
app.blueprint(bp2)

app.run(host='0.0.0.0', port=8000, auto_reload=True)
```
**Describe the solution you'd like**
access: `http://domain.com/images/image.png` redirected to: `./domain/images/image.png`
access: `http://api.domain.com/images/image.png` redirected to: `./subdomain/images/image.png`

**Comment by ahopkins** [comment]
@anbuhckr @e-hamza
This will be resolved in next week's release. Thanks for bringing this up.
