### ISSUE TITLE
Error format detection cause syntax error

### ISSUE THREAD

**Issue by Notmeor** [sanic-org/sanic#2404]
Python 3.10.2 has come out for over a month(since Jan. 14, 2022), is there any shedule for sanic to support it?

**Comment by ahopkins** [comment]
![PyPI - Python Version](https://img.shields.io/pypi/pyversions/sanic?style=for-the-badge)

It does. Is there something specific you are referring to?

**Comment by Notmeor** [comment]
Sorry, I somehow missed that. But I just updated my python version to 3.10.2, and sanic to 21.12.1, and my api server fails to start.

Though there was some compatibility issue for sanic with python 3.10, but now it seems the latter might be the culprit.

Here is the minimal code:

```python
import functools

from sanic import Sanic
from sanic.response import json

app = Sanic("api")


def validate_request(validators):
    def decorator(func):
        @functools.wraps(func)
        async def wrapper(request):
            # ...some validation login here
            return await func(request)
        return wrapper
    return decorator


@app.route('/')
@validate_request([lambda x: 100 < int(x), lambda x: 0 < int(x)])  # x should be some request arg extracted from request
async def hi(request):
    return json({'hello': 'world'})


if __name__ == '__main__':
    app.run()
```

**Comment by ashleysommer** [comment]
The traceback shows exactly what the error is and where its coming from:

> ` @validate_request([lambda x: 100 < int(x), lambda x: 0 < int(x)])`
> `SyntaxError: invalid syntax`

The lambda has invalid syntax. If you haven't changed your code, then there might've been some changes to lambda parsing between python 3.9 and 3.10, but I haven't come across any issues personally.

Anyway, its not a Sanic bug. All of Sanic Test suite runs and passes on Python 3.10.

**Comment by Notmeor** [comment]
If you look closely, the error actually happens in the `_determine_error_format` call.

Say if I simply specify the `error_format`, the above code would not fail
```
import functools

from sanic import Sanic
from sanic.response import json

app = Sanic("api")


def validate_request(validators):
    def decorator(func):
        @functools.wraps(func)
        async def wrapper(request):
            # ...some validation login here
            return await func(request)
        return wrapper
    return decorator


@app.route('/', error_format='text')
@validate_request([lambda x: 100 < int(x), lambda x: 0 < int(x)])  # x should be some request arg extracted from request
async def hi(request):
    return json({'hello': 'world'})


if __name__ == '__main__':
    app.run()
```

**Comment by ahopkins** [comment]
I tested this behavior on Python 3.7, 3.8, 3.9, and 3.10. It is the same everywhere. Peculiar is that this does not cause a problem with a non-decorator.

```python
from inspect import getsource

async def hi(
    validators=[
        lambda x: 100 < int(x),
        lambda x: 0 < int(x),
    ]
):
    ...


print(getsource(hi))
```

Output:
```python
async def hi(
    validators=[
        lambda x: 100 < int(x),
        lambda x: 0 < int(x),
    ]
):
    ...
```

It seems to particularly be a problem with decorators. I am going to play with this some more and will get back.

**Comment by ahopkins** [comment]
So, this is super bizarre.

```python
from inspect import getsource


def bar(funcs):
    def decorator(func):
        return func

    return decorator


@bar([lambda x: x > 0, lambda x: False])
async def foo():
    ...


print(getsource(foo))
```

Output as expected:

```python
@bar([lambda x: x > 0, lambda x: False])
async def foo():
    ...
```

As soon as you add a call inside the lambda...

```python
from inspect import getsource


def bar(funcs):
    def decorator(func):
        return func

    return decorator


@bar([lambda x: int(x) > 0, lambda x: False])
async def foo():
    ...


print(getsource(foo))
```

Poof!

```python
@bar([lambda x: int(x) > 0, lambda x: False])
```

**Comment by ahopkins** [comment]
https://bugs.python.org/msg414149

**Comment by Notmeor** [comment]
See python/cpython#17374.

I guess currently `inspect.getsource` is kinda broken, especially when used in some core logic as in sanic.

**Comment by ahopkins** [comment]
Guess I should have looked deeper. There are multiple PRS for this already 😆
https://github.com/python/cpython/pull/31605

**Comment by ahopkins** [comment]
This is not a Sanic issue so I am closing it. Seeing as rhe issue has been lying around in cPython for so long without fix, I would not hold my breath long waiting for it. I'd suggest you try the pattern using assignment to a variable.
