### ISSUE TITLE
GHSA-7p79-6x2v-5h88: Clarification of vulnerable versions

### ISSUE THREAD

**Issue by shelbyc** [sanic-org/sanic#2406]
I'm a curator of the GitHub Advisory Database and saw the update to [GHSA-7p79-6x2v-5h88](https://github.com/sanic-org/sanic/security/advisories/GHSA-7p79-6x2v-5h88). I want to add the updates to the advisory on [our database](https://github.com/advisories/GHSA-7p79-6x2v-5h88) but am not clear about which versions are vulnerable.
The original description reads that "Anyone running Sanic server between 0.1.7 and 20.12 using Python 3.10" is vulnerable, but the recent addition to the description says that the issue "ONLY APPLIES TO Sanic v20.12 + Python 3.10". Are the versions between 0.1.7 and 20.12 vulnerable?

**Comment by ahopkins** [comment]
I fixed that. Thanks. v21 is not impacted. Only versions before, using python 3.10.

**Comment by shelbyc** [comment]
Thanks for the response, Adam. The fixed version on the advisory is 20.12.6 (so we assume that the fix is included in v21 then), but the affected versions are unclear and conflict within the advisory itself.
- "Anyone running Sanic server between 0.1.7 and 20.12 using Python 3.10" is vulnerable
- This "ONLY APPLIES TO Sanic v20.12 + Python 3.10"

Which of these vulnerable version range is correct?

**Comment by ahopkins** [comment]
The first. I made a clarification.

**Comment by shelbyc** [comment]
Thank you for the clarification!
