### ISSUE TITLE
Typo in docs example

### ISSUE THREAD

**Issue by knrdl** [sanic-org/sanic#2412]
**Describe the bug**
https://sanic.dev/en/guide/basics/routing.html#websockets-routes

**Code snippet**
`messgage = "Start"`
should be
`message = "Start"`
in both snippets

**Comment by ahopkins** [comment]
On the bottom of the page, there is a link to edit the page in GitHub. Can you please submit a PR? 🙏

**Comment by knrdl** [comment]
https://github.com/sanic-org/sanic-guide/pull/113
