### ISSUE TITLE
Request object no longer has the route attached in 22.3.0

### ISSUE THREAD

**Issue by basepi** [sanic-org/sanic#2423]
**Describe the bug**

`Request` object no longer has the `route` attached in 22.3.0

**Code snippet**

In the Elastic APM agent, [we use `Request.route.path` to populate the transaction name.](https://github.com/elastic/apm-agent-python/blob/aeb2d01c4527e73395949fe026b6f26a43da1154/elasticapm/contrib/sanic/__init__.py#L222-L224)

As of 22.3.0 it appears that the route has disappeared from requests, so the transaction name cardinality will explode due to using the URL instead of the route.

Is there a good way to get the route from the `Request` object in 22.3.0? I don't even see it listed in the [docs](https://sanic.readthedocs.io/en/stable/sanic/api/core.html#module-sanic.request)

cc: @beniwohli 

ref: https://github.com/elastic/apm-agent-python/issues/1515

**Comment by ahopkins** [comment]
> This might be something you want to add to your [release notes](https://github.com/sanic-org/sanic/releases/tag/v22.3.0) as it was a breaking change for us. Thanks!

Thanks! Absolutely! TBH, I thought it was :thinking: I know there has been deprecation warnings since last year sometime and I thought the change had been published. I will double check. I really appreciate the feedback and apologize for any confusion on that.
