### ISSUE TITLE
Use static type checking

### ISSUE THREAD

**Issue by f4at** [sanic-org/sanic#2430]
**Describe the bug**
There is wrong typing in Sanic, consider using a static type checker like Pylance (with type checking enabled).
Static type checkers are pretty helpful and can help prevent bugs.

**Comment by ahopkins** [comment]
We use `mypy` as a part of our CI. Is there a specific place that you are seeing a problem?

**Comment by alecov** [comment]
I suppose he could be referring to strict mode in mypy. For example:

https://github.com/sanic-org/sanic/blob/6eaab2a7e5be418385856371fdaebe4701f8c4fc/sanic/mixins/middleware.py#L66

Using `@app.on_request` under mypy strict mode will give ''Untyped decorator makes function untyped".

Another situation, this one unrelated to mypy:

https://github.com/sanic-org/sanic/blob/6eaab2a7e5be418385856371fdaebe4701f8c4fc/sanic/request/types.py#L642

Pylance cannot determine the type of `request.args`, so perhaps a type annotation here is in order.

**Comment by ahopkins** [comment]
A PR to add those would be welcome :sunglasses:
