### ISSUE TITLE
Use SANIC_NO_UJSON during runtime also

### ISSUE THREAD

**Issue by azimovMichael** [sanic-org/sanic#2436]
**Is your feature request related to a problem? Please describe.**
I would like to use Sanic without ujson (I want to use the standard json, for backward compatibility reasons).
My problem is that the only way to not install ujson is by installing sanic with the` --no-binary` option. I can't do that because I have a large microservices system that is based on regular requirements files, that are installed during build time with standart `pip install` command, and using pre-built wheel files is very important to us.

**Describe the solution you'd like**
I would like that any place that does this:
```
try:
    from ujson import loads as json_loads  # type: ignore
except ImportError:
    from json import loads as json_loads  # type: ignore
```

Will also add something like this:

```
try:
    if not strtobool(os.environ.get("SANIC_NO_UJSON", "no")):
          from ujson import loads as json_loads  # type: ignore
    else:
          from json import loads as json_loads  # type: ignore
except ImportError:
    from json import loads as json_loads  # type: ignore
```

For both json.dumps and json.loads.

If this idea sounds good, I can also do a PR to add this.

**Comment by ahopkins** [comment]
First, those environment variables are a pain. The least we can rely upon them the better. While your solution makes sense for sure, it brings up something else...

Second, something I have been wanting to introduce is a better method for handling `loads` that looks more similar to what we do for `dumps`.

```py
from sanic import Sanic

app = Sanic(..., dumps=dumps)
```

If we are going to tackle this, I would like to do some work on the API in general and not just bandage the imports.

**Comment by ahopkins** [comment]
I hope you do not mind, I have assigned this to you @azimovMichael. If this is more than you were intending to take on, LMK.

**Comment by azimovMichael** [comment]
NP. @ahopkins 
I like your idea of extending the API to support more than just the dumps.
Maybe we can add a `json_encoder_cls` param, and it can be any class that implements `dumps` & `loads` functions.
Or go with the current design and add a `loads` kwarg

**Comment by ahopkins** [comment]
I think we should just add `loads`. It provides more flexibility and doesn't lock-in specific naming.

IIRC, there may be some complexity in deciding where to set it as a global variable. Feel free to ping me here or on discord to discuss options further.

**Comment by azimovMichael** [comment]
@ahopkins So, I'm thinking about just doing basically the same as `dumps`.
Adding a static member `_loads` in `Request` and use it in `load_json`.

**Comment by ahopkins** [comment]
That makes sense, just double check if there is any other location we are using `loads` from.
