### ISSUE TITLE
AttributeError: 'method' object has no attribute '__blueprintname__'

### ISSUE THREAD

**Issue by zx8** [sanic-org/sanic#2440]
**Describe the bug**

I am trying to structure my code following best practices, keeping everything contained within a class to avoid any global objects. When I attempt to contain my blueprints within the class object, I get the error in the title.

**Code snippet**

Minimal reproduction of the issue:

```python
from sanic import Blueprint, Sanic


class Router(Sanic):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, name="Example", **kwargs)

        self._add_routes()

    def _add_routes(self):
        v1 = Blueprint("v1", version=1)
        v1.add_route(self._handle_v1_foo, "/foo")
        self.blueprint(v1)

        v2 = Blueprint("v2", version=2)
        v2.add_route(self._handle_v2_foo, "/foo")
        self.blueprint(v2)

    def _handle_v1_foo(self, request):
        pass

    def _handle_v2_foo(self, request):
        pass


app = Router()
```

**Expected behavior**

No error.

**Actual behavior**

```
Traceback (most recent call last):
  File "/private/tmp/tmp.ZKa5SvCjpA/main.py", line 26, in <module>
    app = Router()
  File "/private/tmp/tmp.ZKa5SvCjpA/main.py", line 8, in __init__
    self._add_routes()
  File "/private/tmp/tmp.ZKa5SvCjpA/main.py", line 13, in _add_routes
    self.blueprint(v1)
  File "/tmp/virtualenv/lib/python3.10/site-packages/sanic/app.py", line 527, in blueprint
    blueprint.register(self, options)
  File "/tmp/virtualenv/lib/python3.10/site-packages/sanic/blueprints.py", line 309, in register
    future.handler.__blueprintname__ = self.name
AttributeError: 'method' object has no attribute '__blueprintname__'
```

**Comment by sjsadowski** [comment]
blueprint returns a future which must be awaited. This is expected behavior.

make the appropriate changes in your class and then await self.blueprint(v1), etc.

**Comment by zx8** [comment]
@sjsadowski I'm not sure I follow. Can you provide an (ideally working) example of what you mean using the code snippet provided in the OP?

**Comment by sjsadowski** [comment]
```py
from sanic import Blueprint, Sanic


class Router(Sanic):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, name="Example", **kwargs)

        self._add_routes()

    async def _add_routes(self):
        v1 = Blueprint("v1", version=1)
        v1.add_route(self._handle_v1_foo, "/foo")
        await self.blueprint(v1)

        v2 = Blueprint("v2", version=2)
        v2.add_route(self._handle_v2_foo, "/foo")
        await self.blueprint(v2)

    async def _handle_v1_foo(self, request):
        pass

    async def _handle_v2_foo(self, request):
        pass


app = Router()
```

Note that this will throw exceptions because you're not returning from the routes. Also I'm not 100% sure what this best practice is derived from, but the above works for your use case.

**Comment by zx8** [comment]
Thanks a lot for this!

Unfortunately, it doesn't seem to work. I get the following error:

```
RuntimeWarning: coroutine 'Router._add_routes' was never awaited
  self._add_routes()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by sjsadowski** [comment]
This was a my bad and I didn't think all the way through before I started answering.

```py
class MySanic(Sanic):

    def __init__(self, name, *args, **kwargs):
        super().__init__(name, *args, **kwargs)

        self._add_blueprint()

    def _add_blueprint(self):
        v1 = Blueprint("v1", version=1)
        v1.add_route(self.handle_v1_foo, "/foo")
        self.caller(v1)

    def caller(self, bp):
        self.blueprint(bp)

    @staticmethod
    async def handle_v1_foo(request):
        return response.text("ok")
```

When a route is registered, it expects the first argument to be a request object. I think the error is wrong, and I got caught up on the futures statement in the stack trace. By declaring the function as a static method, you bypass that problem while still managing to structure your code the way you want.

**Comment by ahopkins** [comment]
@zx8 You can get access to the application instance from the `Request` object:

```python
request.app
```

And therefore...

```python
request.app.ctx
```

**Comment by zx8** [comment]
Fantastic. Case closed, thank you both!

**Comment by ahopkins** [comment]
As for the question... I would not call that a bug. You are using Sanic and Blueprints in a way that was not anticipated. Unfortunately instance methods (TMK) cannot have properties assigned to them the way that functions can. This is why you see that message. Albeit it is somewhat of a "hack" to assign properties to a function, it is part of the under-the-hood magic that enables proper naming of handlers. So it might be possible to allow for instance methods to be used like this, but it would require some changes.

**Comment by ahopkins** [comment]
Actually... TBH, the more I look at it, I think this is deprecated code anyway. We probably can remove that assignment completely since it is no longer in use or needed.
