### ISSUE TITLE
the 'name'  support Chinese

### ISSUE THREAD

**Issue by o-ut-man** [sanic-org/sanic#2446]
Python `coding=utf-8` can support Chinese
but something like `app = Sanic('名字')` will report `sanic.exceptions.SanicException: Sanic instance named '名字' uses an invalid format. Names must begin with a character and may only contain alphanumeric characters, _, or -.`
I hope the 'name'  can support Chinese

**Comment by o-ut-man** [comment]
我刚尝试Sanic框架，目前发现两处不支持中文
app = Sanic('名字')
蓝图 = Blueprint('名字')
可能是‘__name__’属性的问题


目前我在尝试中文对象名，所以希望命名也能支持中文
| |
z
|
|
***@***.***
|
On 5/4/2022 ***@***.***> wrote：

目前Sanic用中文名会报错吗？

**Comment by ahopkins** [comment]
The name of applications and blueprints are used to build a route name in the form: `<app>.<blueprint>.<route>`. They intentionally closely follow the requirements for variable names in Python, with the exception that we also allow hyphens (`-`).

**Comment by ChihweiLHBird** [comment]
> 我刚尝试Sanic框架，目前发现两处不支持中文
> app = Sanic('名字')
> 蓝图 = Blueprint('名字')
> 可能是‘__name__’属性的问题
> 
> 
> 目前我在尝试中文对象名，所以希望命名也能支持中文
> | |
> z
> |
> |
> ***@***.***
> |
> On 5/4/2022 ***@***.***> wrote：
> 
> 目前Sanic用中文名会报错吗？
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

如果我们选择支持中文名字的话，可能也要兼容别的语言，可能会导致更多的兼容性问题，比如@ahopkins 在上面提到的使用app名字构建route。所以目前我们不会选择支持Python变量名不允许的其他语言的字符，非常抱歉哈。感谢你对Sanic社区的支持！
