### ISSUE TITLE
`Async for` can be used to iterate over a websocket's incoming messages

### ISSUE THREAD

**Issue by bradlangel** [sanic-org/sanic#2464]
**Is your feature request related to a problem? Please describe.**

When creating a websocket server I'd like to use `async for` to iterate over the incoming messages from a connection. This is a feature that the [websockets lib](https://websockets.readthedocs.io/en/stable/) uses. Currently, if you try to use `async for` you get the following error: 

```console
TypeError: 'async for' requires an object with __aiter__ method, got WebsocketImplProtocol
```

**Describe the solution you'd like**

Ideally, I could run something like the following on a Sanic websocket route:

```python
@app.websocket("/")
async def feed(request, ws):
    async for msg in ws:
        print(f'received: {msg.data}')
        await ws.send(msg.data)
```

**Additional context**
[This was originally discussed on the sanic-support channel on the discord server](https://discord.com/channels/812221182594121728/813454547585990678/978393931903545344)

**Comment by ChihweiLHBird** [comment]
I will take a look and see what can be done. Thanks for creating the issue!

**Comment by hyansuper** [comment]
This feature was available in earlier version of sanic years ago, maybe earlier version uses websockets internally?
The `async for` look very pythonic and I like it too.
here's a simple workaround
```
class async_for_ws:
    def __init__(self, ws):
        self.ws = ws
    async def send(self, x):
        await self.ws.send(x)
    async def recv(self):
        return await self.ws.recv()
    def __aiter__(self):
        return self        
    async def __anext__(self):
        return await self.recv()

async for data async_for_ws(ws):
    ....

```

**Comment by Tronic** [comment]
You can do it without `__anext__` or any other extra boilerplate by simply adding this function to the websocket class:
```python
async def __aiter__(self):
    while True:
        yield await self.recv()
```

As a user workaround, I suppose one can monkey patch that on Sanic's websocket, but hopefully @ChihweiLHBird gets the patch done and merged in time for the upcoming Sanic 22.6 release.

**Comment by ChihweiLHBird** [comment]
> You can do it without `__anext__` or any other extra boilerplate by simply adding this function to the websocket class:
> 
> ```python
> async def __aiter__(self):
>     while True:
>         yield await self.recv()
> ```
> 
> As a user workaround, I suppose one can monkey patch that on Sanic's websocket, but hopefully @ChihweiLHBird gets the patch done and merged in time for the upcoming Sanic 22.6 release.

I think `__anext__` is worth because it makes the object supports `anext`. Consider this case:

```python
async def test_anext():
    while True:
        await anext(ws)
```

**Comment by ChihweiLHBird** [comment]
My question is, should we make the whole `ws` (`WebsocketImplProtocol`) object async iteratable? Or just make another `recv`-like method to return an async generator?

```python
async def recv_generator(self):
    while True:
        yield await self.recv()
```

Any opinion?

**Comment by hyansuper** [comment]
I’d like it to have same behavior as the websockets lib

**Comment by ahopkins** [comment]
> I’d like it to have same behavior as the websockets lib

:point_up:

**Comment by Tronic** [comment]
> My question is, should we make the whole `ws` (`WebsocketImplProtocol`) object async iterable? Or just make another `recv`-like method to return an async generator?

The whole purpose of `__aiter__` is to produce an iterable object. Making that function async lets Python do that built-in without needing us to implement an object for it, or supporting `__anext__` on the websocket object. Similarly as you cannot `next(a_list)` without first doing `iter(a_list)` and then iterating what that returns. `async for` automatically calls `__anext__` behind the scenes.

**Comment by Tronic** [comment]
Because this is Sanic, I ran a benchmark. The built-in async iterator is some nanoseconds faster per call but while barely measurable, the difference is utterly negligible to anything else that receiving from a WebSocket does. The benchmark code (written on ipython prompt and timed with `%timeit` is a bit too long to post here).

One thing to consider is what to do if the websocket is closed, should it exit the loop cleanly or just raise some exception? Probably the latter, which doesn't then need any extra work. The loop will then never exit normally.

**Comment by ChihweiLHBird** [comment]
> Because this is Sanic, I ran a benchmark. The built-in async iterator is some nanoseconds faster per call but while barely measurable, the difference is utterly negligible to anything else that receiving from a WebSocket does. The benchmark code (written on ipython prompt and timed with `%timeit`) is a bit too long to post here.
> 
> Also the situation reverses if only a few messages are to be received within the loop, as the built-in iterator still needs to be constructed, while returning `self` in `__aiter__` avoids this.
> 
> One thing to consider is what to do if the websocket is closed, should it exit the loop cleanly or just raise some exception? Probably the latter, which doesn't then need any extra work. The loop will then never exit normally.

Okay, I agree with you. Benchmark matters and I think the scenario of large number of messages is more common.

`ConnectionClosedOK` exception will be raised if it closed normally. So, I think we can catch this and return while leaving other exceptions to raise up.

**Comment by Tronic** [comment]
Code clarity should probably take precedence since there really is no speed difference either way :)

**Comment by ahopkins** [comment]
What's status here?
