### ISSUE TITLE
CSRF Token 

### ISSUE THREAD

**Issue by sneakybeaky18** [sanic-org/sanic#2469]
**Is your feature request related to a problem? Please describe.**
Hello everyone! How can i have csrf token in sanic? I've already see 2 packages for that, but they making errors and looks outdated

**Describe the solution you'd like**
I'd like to have CSRF protection like in Django, where you can just set csrf middleware for all views and as default context to render in templates, like that:  {% csrf_token %} or {{ csrf_token }}

**Additional context**
Do you have any ideas how i can make it in sanic at this moment? And also thanks for great framework and for you're time!

**Comment by sneakybeaky18** [comment]
And also an abstract question, do i even need CSRF token in modern frameworks when all browsers have cors protection via cors headers? May be i don't need it at all? Thanks in advance

**Comment by sneakybeaky18** [comment]
So i found this implementation of csrf in sanic: https://pypi.org/project/sanic_csrf/
But it is outdated, so i made my own update (because i can't find any repos and i cannot make are fork, sorry).
This my simple example of how you can include csrf in your sanic app in 2022: https://github.com/sneakybeaky18/sanic_csrf_token

**Comment by sneakybeaky18** [comment]
So i found this implementation of csrf in sanic: https://pypi.org/project/sanic_csrf/
But it is outdated, so i made my own update (because i can't find any repos and i cannot make are fork, sorry).
This my simple example of how you can include csrf in your sanic app in 2022: https://github.com/sneakybeaky18/sanic_csrf_token

**Comment by ahopkins** [comment]
To answer your question: yes. You still need CSRF protections.

**Comment by ahopkins** [comment]
You can check out some sample code from my book in this topic here: https://github.com/PacktPublishing/Python-Web-Development-with-Sanic/tree/main/Chapter07
