### ISSUE TITLE
I can't turn off sanic documentation 

### ISSUE THREAD

**Issue by sneakybeaky18** [sanic-org/sanic#2470]
**Describe the bug**
How can i turn off all auto documentation in sanic?

**Code snippet**
This crash the server, any other options about how to turn off auto documentation i not found
```
app.config.OAS_UI_REDOC = False
app.config.OAS_UI_SWAGGER = False
```
**Expected behavior**
After turnin those two options to off i want to disable auto documentation 

**Environment (please complete the following information):**
 - Version [e.g. 0.8.3]

**Comment by ahopkins** [comment]
```python
app.config.OAS = False
```
https://sanic.dev/en/plugins/sanic-ext/configuration.html#settings

```
oas

    Type: bool
    Default: True
    Description: Whether to enable OpenAPI specification generation
```
