### ISSUE TITLE
Blueprints in separate files

### ISSUE THREAD

**Issue by Smugaski** [sanic-org/sanic#2472]
**Is your feature request related to a problem? Please describe.**
Blueprints in separate files. 
It would help with making the code cleaner as blueprints could be separated into different files.
For example my main file is called `server.py` and currently all of my blueprints have to be located there, however it would be nice to have a feature where I can have blueprints in separate files and the main app in `server.py`.

**Comment by sjsadowski** [comment]
This already exists.

https://sanic.dev/en/guide/best-practices/blueprints.html

**Comment by Smugaski** [comment]
thanks didn't read that 🥶
