### ISSUE TITLE
Invalid HTTP request

### ISSUE THREAD

**Issue by beliboba** [sanic-org/sanic#2476]
`Jun 03 14:17:32 lpkqdqyyzu python3[10366]: INFO:     Application startup complete.
Jun 03 14:17:32 lpkqdqyyzu python3[10366]: INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
Jun 03 14:17:50 lpkqdqyyzu python3[10366]: WARNING:  Invalid HTTP request received.
Jun 03 14:17:50 lpkqdqyyzu python3[10366]: Traceback (most recent call last):
Jun 03 14:17:50 lpkqdqyyzu python3[10366]:   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 124, in data_received
Jun 03 14:17:50 lpkqdqyyzu python3[10366]:     self.parser.feed_data(data)
Jun 03 14:17:50 lpkqdqyyzu python3[10366]:   File "httptools/parser/parser.pyx", line 212, in httptools.parser.parser.HttpParser.feed_data
Jun 03 14:17:50 lpkqdqyyzu python3[10366]: httptools.parser.errors.HttpParserInvalidMethodError: Invalid method encountered
Jun 03 14:17:50 lpkqdqyyzu python3[10366]: WARNING:  Invalid HTTP request received.
Jun 03 14:17:50 lpkqdqyyzu python3[10366]: Traceback (most recent call last):
Jun 03 14:17:50 lpkqdqyyzu python3[10366]:   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 124, in data_received
Jun 03 14:17:50 lpkqdqyyzu python3[10366]:     self.parser.feed_data(data)
Jun 03 14:17:50 lpkqdqyyzu python3[10366]:   File "httptools/parser/parser.pyx", line 212, in httptools.parser.parser.HttpParser.feed_data
Jun 03 14:17:50 lpkqdqyyzu python3[10366]: httptools.parser.errors.HttpParserInvalidMethodError: Invalid method encountered`

**Comment by ahopkins** [comment]
I am not sure what to make of this. Is this a question? Closing. If this is a support issue, please follow one of the requested forms of [support](https://sanic.dev/en/help.html).
