### ISSUE TITLE
Sanic static directory fails when folder name ends with ".."

### ISSUE THREAD

**Issue by ekzhang** [sanic-org/sanic#2477]
**Describe the bug**

When serving a static file named `a../b.txt` with `app.static()`, the Sanic request handler gives a 400 status code instead of 200.

**Code snippet**

First file is called `main.py`.

```python
from sanic import Sanic

app = Sanic(name="sanic_test")

app.static('/static', './static_files')

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
```

Then, make the file in question:

```
mkdir -p static_files/a../
cat "hello world" > static_files/a../b.txt
```

And run the server with `python main.py`, followed by a GET request.

```sh-session
$ curl http://localhost:8000/static/a../b.txt
⚠️ 400 — Bad Request
====================
Invalid URL

```

**Expected behavior**

The `app.static()` handler should serve the `b.txt` file with a 200 response code.

**Environment (please complete the following information):**
 - OS: macOS and Linux
 - Version 22.3.0

**Comment by ChihweiLHBird** [comment]
This has been solved in the previous PRs. Feel free to reopen if there is still an issue.

Tested and is no longer reproducible.

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/43905414/200190383-9794c131-6f96-4c89-9b73-f05adce6a343.png">
