### ISSUE TITLE
"last-modified" inconformity  

### ISSUE THREAD

**Issue by zybxjx** [sanic-org/sanic#2497]
**Describe the bug**
response.py is "last-modified" , routes.py is "Last-Modified", cause cache lose efficacy。 

**Code snippet**

`
response.py:
    if last_modified:
        headers.setdefault(
            "last-modified", formatdate(last_modified, usegmt=True)
        )

routes.py:
           if use_modified_since:
                stats = await stat_async(file_path)
                modified_since = strftime(
                    "%a, %d %b %Y %H:%M:%S GMT", gmtime(stats.st_mtime)
                )
                if (
                    request.headers.getone("if-modified-since", None)
                    == modified_since
                ):
                    return HTTPResponse(status=304)
                headers["Last-Modified"] = modified_since
`

**Comment by zybxjx** [comment]
![20220712162151](https://user-images.githubusercontent.com/98636316/178444899-fec89cc0-3421-4ff9-b6fe-66b861af8177.png)

**Comment by ahopkins** [comment]
What version of Sanic are you using? Please provide code that shows what the `headers` object is, how you are setting them, etc.

**Comment by ahopkins** [comment]
To be clear, it is spec-compliant for HTTP headers to be duplicated. That is natural. I am _assuming_ your issue however is that you are using a regular `dict` and not a `Header` object, which would use case-insensitive strings. Closing this as it is not an issue. For further support, please head over to the forums or ping us on Discord.

**Comment by zybxjx** [comment]
22.6.0
