### ISSUE TITLE
Possible to reference app.ctx from a Blueprint instance?

### ISSUE THREAD

**Issue by vgoklani** [sanic-org/sanic#2519]
I've added a `redis_connection` to my `app.ctx` in the main file:

    app.ctx.redis_connection = aioredis.from_url(...)

and I'm able to reference it via a request object:

    request.app.ctx.redis_connection...

However, I also need to access the redis_connection in my blueprint, outside of the request object, which is located in a separate file.

    blueprint_instance = Blueprint("MyBlueprint", url_prefix="/blueprint_url")

I started looking at this: https://github.com/sanic-org/sanic/blob/main/sanic/blueprints.py#L110 but I'm not sure how it's referencing the global app.ctx.

I tried this:

    bluprint_instance.apps.ctx.redis_connection

and got this error:

    sanic.exceptions.SanicException: <Blueprint blueprint_instance> has not yet been registered to an app

How do I get the main app.ctx from the blueprint? Thanks!

**Comment by ahopkins** [comment]
Are you trying in the global scope? How are you trying to use it?

**Comment by vgoklani** [comment]
it's in the global scope for the blueprint file.

More specifically,

I've created a file: my_blueprint.py which defines a blueprint (as above)

in that file, I need to create an instance of something (call it `x` = X(redis_instance=...) that requires a redis_instance. I would like to pass in the redis_instance from app.ctx, so it can leverage the same redis connection pool. 

I would like `x` to live in the blueprint, but i'm not sure how to pass it the redis_instance.

**Comment by ahopkins** [comment]
This is the problem with the global scope. As the error states, the blueprint has not attached to anything yet. You are probably better off putting it inside of a listener. If you want it to live within the Blueprint that is okay:

```python
bp = Blueprint(...)

@bp.before_server_start
async def do_something(app: Sanic):
    ...
```

**Comment by vgoklani** [comment]
ha! I did not realize that the blueprints had access to the listeners!!!

Thank you, this is the correct the solution, and yes it's very elegant!

Thanks for maintaining this library, it's by far my favorite web-framework!

**Comment by ahopkins** [comment]
:blush:
