### ISSUE TITLE
`tests` folder is included in wheel file

### ISSUE THREAD

**Issue by huntzhan** [sanic-org/sanic#2529]
**Describe the bug**

The `tests` folder is included in wheel file and hence will be installed into the `site-packages`. This could break the user's dev environment (and did break our test toolkit) since importing `tests`actually imports `tests` of sanic.

**Code snippet**

![WeChatWorkScreenshot_b78c284b-bc10-498e-bf7f-d7683fcd4896](https://user-images.githubusercontent.com/5213906/185287465-672ccbdb-aea8-4a59-8705-2d15552b77e6.png)

**Expected behavior**

Remove the `tests` folder from wheel.

Passing value to `exclude` or `include` of `find_packages` should work:
https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

**Environment (please complete the following information):**

 - OS: Linux & macOS
 - Sanic Version: 22.6.2

**Additional context**

**Comment by ahopkins** [comment]
Thanks for bringing this up! Can you purpose a PR?

**Comment by huntzhan** [comment]
PR purposed.
