### ISSUE TITLE
Sanic enables writing of DeprecationWarning to the log

### ISSUE THREAD

**Issue by azimovMichael** [sanic-org/sanic#2538]
**Describe the bug**
Sanic changes the default DeprecationWarning behaviour to be written to the log.
The code line that cause it is in app.py line 104:
`filterwarnings("once", category=DeprecationWarning)`

This change makes all of the DeprecationWarning, *in every 3rd party library* we use, to be written to the log.

**Expected behavior**
I would expect that this will not happen in production 😅 

**Environment (please complete the following information):**

 - OS: ubuntu & macOS
 - Sanic Version: 22.6

**Comment by ahopkins** [comment]
Good point. At the very least that should probably be by config. Will think about how we can make that a nicer experience and still make sure we provide good warnings.

**Comment by azimovMichael** [comment]
Yeah, I guess an ENABLE_DEPRECATION_WARNINGS config var would be best. I can submit a PR if you like

**Comment by ahopkins** [comment]
If you have a chance to add this PR this week, LMK. Otherwise I will tackle this so we can get it into the upcoming release.

**Comment by azimovMichael** [comment]
Unfortunately I probably wont be able to get to this before the next release

בתאריך יום ד׳, 14 בספט׳ 2022 ב-14:31 מאת Adam Hopkins <
***@***.***>:

**Comment by ahopkins** [comment]
> Unfortunately I probably wont be able to get to this before the next release בתאריך יום ד׳, 14 בספט׳ 2022 ב-14:31 מאת Adam Hopkins < ***@***.***>:

No worries. I will add it. יום טוב

**Comment by ahopkins** [comment]
@azimovMichael #2546 should fix this:

1. It will only apply to `sanic` notices
2. Adds a config value to turn them off (see PR)

The one downside is it limits the ability to control notices that happen *before* the application is instantiated. This mainly would impact the CLI. But we are not doing this currently, so hopefully it will not matter. Or, we will cross that bridge if we come to it.

Thanks for this suggestion, it is a much nicer solution.
