### ISSUE TITLE
Templating Jinja cant find template

### ISSUE THREAD

**Issue by beliboba** [sanic-org/sanic#2541]
On every launch it throws error
`jinja2.exceptions.TemplateNotFound: index.html`

The index.html is present in templates/ dir which is in the same folder as python file. 
I even tried to put this in my code :
`app.extend(templating_path_to_templates='./templates/')`

everything works perfectly on windows in Pycharm but at the linux server it makes errors

**Comment by ahopkins** [comment]
This is a support issue not a bug. 

https://sanic.dev/en/help.html

**Comment by ahopkins** [comment]
I would guess from the limited info maybe you are trying to run from a deployed env? Inside a container maybe? Double check that the file actually does exist and is accessible. If it is, please look at the help and post support issue.

**Comment by beliboba** [comment]
Im running it in debug mode as is without any containers. And file exists and can be opened.

**Comment by ahopkins** [comment]
Okay, open up a support issue and please provide some snippets. If you in fact believe this is a bug with the package you should post in the Sanic Extensions repo and provide a minimal set of code that reproduces the issue.

Thanks :sunglasses:
