### ISSUE TITLE
[Docs] GunicornWorker is removed, but latest documentation still refers users to it

### ISSUE THREAD

**Issue by galbiati** [sanic-org/sanic#2552]
**Describe the bug**

This is mainly a documentation issue. The [current documentation](https://sanic.dev/en/guide/deployment/running.html#gunicorn) points users to `sanic.workers.GunicornWorker`, but [that was removed](https://github.com/sanic-org/sanic/blob/874718db946e553f79db85bd7f404e6c9335838d/docs/sanic/releases/22/22.3.md#version-2230) in version 22.3 in favor of `uvicorn.workers.UvicornWorker`

**Code snippet**

The current documentation says `gunicorn myapp:app --bind 0.0.0.0:1337 --worker-class sanic.worker.GunicornWorker
`

**Expected behavior**

The correct documentation would say `gunicorn myapp:app --bind 0.0.0.0:1337 --worker-class uvicorn.workers.UvicornWorker
`

**Environment (please complete the following information):**

 - OS: 
 - Sanic Version:

N/A - this is a documentation issue.

**Additional context**

It took me a while to find the correct way to use `gunicorn` with latest `sanic`. Updating docs should be easy and save the next person to encounter some time.

**Comment by ahopkins** [comment]
On the bottom of each page is an edit link. Would be very grateful if you could fix 😎

**Comment by galbiati** [comment]
[Sent a PR](
https://github.com/sanic-org/sanic-guide/compare/main...galbiati:sanic-guide:patch-1); thanks for the pointer 🤙
