### ISSUE TITLE
Colon in uri generate response 404

### ISSUE THREAD

**Issue by 4n1qz5skwv** [sanic-org/sanic#2553]
Sanic can't find the route if there's a colon in the uri.

**Code snippet**
```python
from sanic import Sanic, Request, HTTPResponse

app = Sanic('zzz')


@app.get(f'/abc/x:y')
async def main(_: Request):
    return HTTPResponse()


if __name__ == '__main__':
    app.run()

```

**Expected behavior**
`GET http://127.0.0.1:8000/abc/x:y  200 0`

**Actual behavior**
`GET http://127.0.0.1:8000/abc/x:y  404 733`

**Environment**
```
[2022-09-26 20:50:40 +0600] [13060] [INFO] Sanic v22.6.2
[2022-09-26 20:50:40 +0600] [13060] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2022-09-26 20:50:40 +0600] [13060] [INFO] mode: production, single worker
[2022-09-26 20:50:40 +0600] [13060] [INFO] server: sanic, HTTP/1.1
[2022-09-26 20:50:40 +0600] [13060] [INFO] python: 3.10.5
[2022-09-26 20:50:40 +0600] [13060] [INFO] platform: Windows-10-10.0.19044-SP0
[2022-09-26 20:50:40 +0600] [13060] [INFO] packages: sanic-routing==22.3.0
[2022-09-26 20:50:40 +0600] [13060] [INFO] Starting worker [13060]
```

**Additional context**
https://github.com/tiangolo/fastapi/issues/4892
https://github.com/encode/starlette/pull/1657

**Comment by sjsadowski** [comment]
Please open this in https://github.com/sanic-org/sanic-routing as well

**Comment by ahopkins** [comment]
@sjsadowski no need to do that, we can just move it between projects

**Comment by ahopkins** [comment]
For reference, this is not a path defined character, and is explicitly reserved in the spec. I'm not sure rhat it is something in need of changing, and I certainly would not call this a bug.

**Comment by ahopkins** [comment]
This works as expected if you pass the value as URL encoded.

![image](https://user-images.githubusercontent.com/166269/192707329-164932d9-ce44-48ee-a5f9-8674af12b2d2.png)

**Comment by prryplatypus** [comment]
fwiw same happens with other characters such as `@`

**Comment by ahopkins** [comment]
I guess the question then is what non-spec-compliant characters (if any) should we support?

**Comment by ahopkins** [comment]
I am going to put this aside for now unless someone can make a compelling argument for why we need to handle this. It is the first time I have heard this come up and I am hesitant to add in support for this edge case when a viable alternative exists.

For anyone that needs:

```python
from urllib.parse import quote

from sanic import Request, Sanic, json
from sanic.router import Router


class MyRouter(Router):
    def get(self, path, *args, **kwargs):
        return super().get(quote(path), *args, **kwargs)


app = Sanic("TestApp", router=MyRouter())


@app.route("/x:y")
async def handler(request: Request):
    return json({"foo": "bar"})
```

Or, perhaps a try/except is warranted:

```py
    def get(self, path, *args, **kwargs):
        try:
            return super().get(path, *args, **kwargs)
        except NotFound:
            return super().get(quote(path), *args, **kwargs)
```

**Comment by Tronic** [comment]
Closing as WONTFIX, given that it against specs and as @ahopkins noted a rare corner case with viable workarounds for those who need it anyway.
