### ISSUE TITLE
Support overwriting a route of blueprint from copy

### ISSUE THREAD

**Issue by Tpinion** [sanic-org/sanic#2554]
**Feture Description**
I want to overwrite the implement of route partially when they belong to different version blueprint, and it raises sanic_routing.exceptions.RouteExists.
**Sample Code**
```python
from sanic import Blueprint
from sanic.response import json
from sanic import Sanic

app = Sanic('test')

bpv1 = Blueprint('bpv1', version=1)

@bpv1.route('/hello')
async def root(request):
    return json('hello v1')

app.blueprint(bpv1)

bpv2 = bpv1.copy('bpv2', version=2)

@bpv2.route('/hello')
async def root(request):
    return json('hello v2')

app.blueprint(bpv2)
```
**Current Solution**
I get this solution from forum and i was encouraged to post new a feature request based on it~
```python
bpv2 = bpv1.copy("bpv2", version=2)

bpv2._future_routes = {
    route for route in bpv2._future_routes if route.uri != "/hello"
}


@bpv2.route("/hello")
async def root2(request):
    return json("hello v2")
```

**Web Link**
https://community.sanicframework.org/t/how-to-overwrite-a-route-when-using-blueprint-copy/1067

**Comment by ahopkins** [comment]
Thanks for adding this. As I mentioned in that thread, I think my preferred solution to this would be to set a flag on the `Blueprint` instance that would allow a route to overwrite a duplicate. This should be `False` all the time and probably only turned on through the `copy` API:

```python
new_bp = old_bp.copy(allow_overwrite=True)
```

We would probably need to change `Blueprint.route` to handle this.

Another option might be to bring back `remove_route`. @Garito might roll his eyes at the suggestion. As a bit of background, there used to be `app.remove_route`. It was [deprecated](https://github.com/sanic-org/sanic/commit/d4ef151cc45e3a338f2e2ae56e29d75096231024) in 2019, and [removed](https://github.com/sanic-org/sanic/pull/1818/files) in 2020. Lots of discussion on [GitHub](https://github.com/sanic-org/sanic/issues/1195) and [the Forums](https://community.sanicframework.org/t/removing-routes-necessary-functionality/29). Pinging also @sjsadowski and @vltr who were vocal in the conversation.

IIRC the reason it was removed was the conflict is was causing people with servers while running and syncing across processes. We potentially could bring it back with the following condition:

1. It fails if server is running (much easier to determine that today than it was in 2019)
2. It also has a `force` flag if someone needs to do it (let the dev add protection from shooting themselves in their own feet)

In favor of this idea: it is actually much easier now to also share context among workers. It is much more likely that someone could cover this issue.

---

I am up for other suggestions, but it strikes me that the underlying principle might be best served with the narrow `allow_overwrite` option. However, `remove_route` does not seem as outlandish to me now as it did to me a couple years ago. :thinking:

**Comment by ChihweiLHBird** [comment]
@ahopkins Why don't we allow overwriting routes globally even for a non-copied blueprint?

**Comment by ahopkins** [comment]
correct

**Comment by ChihweiLHBird** [comment]
@ahopkins I am interested in working on this and explore the way to allowing overwriting. Is there anyone else working on it?

**Comment by ahopkins** [comment]
nope
