### ISSUE TITLE
Failure to find registered application

### ISSUE THREAD

**Issue by LiraNuna** [sanic-org/sanic#2559]
**Describe the bug**
Since version 22.9.0 and I believe https://github.com/sanic-org/sanic/pull/2499, I get errors for "app not found" during startup:

```
    return cls._app_registry[name]
KeyError: 'api-server'

...

sanic.exceptions.SanicException: Sanic app name "api-server" not found.
```

**Code snippet**

```python
from sanic import HTTPResponse
from sanic import Request
from sanic import Sanic
from sanic import response


class MySanicSubclas(Sanic):
    def __init__(self) -> None:
        super().__init__(name='sanic')

        self.register_endpoints()

    def register_endpoints(self) -> None:
        """This endpoint registers endpoints/blueprints etc, currently registers a single route to make sanic happy"""

        self.get('/')(self.dummy_route)

    async def dummy_route(self, request: Request) -> HTTPResponse:
        return response.html('Hello world')


if __name__ == '__main__':
    app = MySanicSubclas()
    app.run(
        motd=False,
        # legacy=True,  # <- will fix the issue, but will be deprecated after 23.3
        dev=True,
    )

```

**Expected behavior**
No exception is thrown.

**Environment (please complete the following information):**

 - OS: Linux
 - Sanic Version: 22.9.0

**Additional context**
I **believe** this is because I do NOT have a global `app` object like usual. Instead, I subclass `Sanic` and add my own start up code, then instantiate the server separately in a main entry point and therefor your new launcher cannot find a "registered" instance. I'm aware of the existance of `legacy=True` but it will be deprecated in version v23.3.

In addition, this behavior is not going to be supported once https://peps.python.org/pep-0690/ is going to be a permanent part of python as your registration behavior relies on code execution during import.

**Comment by ahopkins** [comment]
Move the app instantiation outside the "if" block

**Comment by ahopkins** [comment]
PEP 690 should not be impactful. The code inside that block only executes on the main process and is therefore blind to all other subprocesses.

**Comment by LiraNuna** [comment]
The example I've shown is a very primitive example of what is actually running in my code. In reality, I dynamically instantiate the server out of several possible servers. Sure, in that example it's possible to do this, but in my actual application it is not.

**Comment by LiraNuna** [comment]
May I suggest some sort of a hook to attempt to retrieve a server by name that defaults to the registry as it stands right now?

**Comment by ahopkins** [comment]
There sort of is one. Albeit, not really exposed right now. There is an object called `AppLoader` that is injected into every subprocesses that does just this. One of its options is to pass it a factory. It was my intention to continue smoothing over the pattern before the LTS, and perhaps one thing to do is publicly expose it.

It works with factories now, but only from the CLI.

**Comment by ahopkins** [comment]
@LiraNuna Will this pattern work for you right now?

```python
from sanic import Blueprint, Request, Sanic, json
from sanic.worker.loader import AppLoader

bp = Blueprint("foo")


@bp.get("/")
async def handler(request: Request):
    return json({"foo": "bar"})


def create_app():
    app = Sanic.get_app("DynamicApp", force_create=True)
    app.blueprint(bp)
    return app


if __name__ == "__main__":
    loader = AppLoader(factory=create_app)
    loader.load().prepare(port=9999, auto_reload=True)
    Sanic.serve(app_loader=loader)
```

**Comment by LiraNuna** [comment]
It would work if the `factory` method could take an app name to create. As I mentioned, I run multiple instances of `Sanic` and need to be able to dynamically choose which one to run. I hope this doesn't complicate things.

**Comment by ahopkins** [comment]
I have no idea what you mean by dynamic choice if you cannot encapsulate your logic in a factory. Can you provide some code snippet so i can understand?

**Comment by ahopkins** [comment]
> It would work if the factory method could take an app name to create. 

It's just a callable. Pass it whatever you want.

**Comment by LiraNuna** [comment]
You're right, I wasn't taking `functools.partial` as an option. Does the factory method have to be publicly available? What are the limitations of this approach? 

I'll work on a mini-example to illustrate what I'm doing to better help you understand.

**Comment by LiraNuna** [comment]
Here's a relatively minimal example showing what I mean by "dynamic creation of a server", I hope this will help you understand where I'm coming from. We have this system but in a much more mature way and not just limited to sanic servers.

```python
from argparse import ArgumentParser

from sanic import HTTPResponse
from sanic import Request
from sanic import Sanic
from sanic import response


class CustomSanicBase(Sanic):
    def __init__(self) -> None:
        super().__init__(name=self.get_name())

        self.register_endpoints()

    def register_endpoints(self) -> None:
        """This endpoint registers endpoints/blueprints etc, currently registers a single route to make sanic happy"""

        self.get('/')(self.dummy_route)

    async def dummy_route(self, request: Request) -> HTTPResponse:
        return response.html('Hello world')

    @classmethod
    def get_name(cls) -> str:
        raise NotImplementedError


class SubclassA(CustomSanicBase):
    @classmethod
    def get_name(cls) -> str:
        return 'a'


class SubclassB(CustomSanicBase):
    @classmethod
    def get_name(cls) -> str:
        return 'b'


class SubclassC(CustomSanicBase):
    @classmethod
    def get_name(cls) -> str:
        return 'c'


if __name__ == '__main__':
    subclasses_by_name = {
        subclass.get_name(): subclass
        for subclass in CustomSanicBase.__subclasses__()
    }

    arg_parser = ArgumentParser()
    arg_parser.add_argument('--server', type=str, help='The server to run', choices=subclasses_by_name.keys())

    arguments = arg_parser.parse_args()

    app_class = subclasses_by_name[arguments.server]
    app = app_class()
    app.run(
        motd=False,
        legacy=True,  # <- will fix the issue, but will be deprecated after 23.3
        dev=True,
    )
```

**Comment by ahopkins** [comment]
> Does the factory method have to be publicly available? 

If by public you mean it needs to be outside of the `__name__/__main__` block, then yes.

> What are the limitations of this approach?

This is really not that much different then what happens if you were to call:

```
$ sanic path.to.server:create_app --factory
```

The underlying approach is supported and intended, albeit not advertised as it is def a more hands-on approach.

>  I hope this will help you understand where I'm coming from. 

Excellent. Will take a look tomorrow with a fresh set of :eyes:

**Comment by ahopkins** [comment]
@LiraNuna How about this?

```python
from argparse import ArgumentParser
from functools import partial
from typing import Type

from sanic import HTTPResponse, Request, Sanic, response
from sanic.worker.loader import AppLoader


class CustomSanicBase(Sanic):
    def __init__(self, name) -> None:
        super().__init__(name=self.get_name())

        self.register_endpoints()
        self.register_listeners()

    def register_endpoints(self) -> None:
        """This endpoint registers endpoints/blueprints etc, currently registers a single route to make sanic happy"""

        self.get("/")(self.dummy_route)

    def register_listeners(self) -> None:
        @self.before_server_start
        def display(app: CustomSanicBase):
            print("SERVING:", app.get_name())

    async def dummy_route(self, request: Request) -> HTTPResponse:
        return response.html("Hello world")

    @classmethod
    def get_name(cls) -> str:
        raise NotImplementedError


class SubclassA(CustomSanicBase):
    @classmethod
    def get_name(cls) -> str:
        return "a"


class SubclassB(CustomSanicBase):
    @classmethod
    def get_name(cls) -> str:
        return "b"


class SubclassC(CustomSanicBase):
    @classmethod
    def get_name(cls) -> str:
        return "c"


def create_app(app_class: Type[CustomSanicBase], app_name: str):
    app = app_class.get_app(app_name, force_create=True)
    return app


if __name__ == "__main__":
    subclasses_by_name = {
        subclass.get_name(): subclass
        for subclass in CustomSanicBase.__subclasses__()
    }

    arg_parser = ArgumentParser()
    arg_parser.add_argument(
        "--server",
        type=str,
        help="The server to run",
        choices=subclasses_by_name.keys(),
    )

    arguments = arg_parser.parse_args()

    app_class = subclasses_by_name[arguments.server]
    loader = AppLoader(
        factory=partial(create_app, app_class, arguments.server)
    )
    loader.load().prepare(motd=False, dev=True, port=9999)
    Sanic.serve(app_loader=loader)
```

**Comment by LiraNuna** [comment]
There's some weird pickling going on somewhere, I ended up with this as a factory:

```python
    @classmethod
    def instance_factory(cls, server_name: str) -> HttpServer:
        if server_name in cls._app_registry:
            return cls._app_registry[server_name]

        available_servers = ... # gets all available servers
        return available_servers[server_name]
```

Something ended up registering the server twice, but this approach seems to work. Thanks for directing me toward the `AppLoader` class and friends.
