### ISSUE TITLE
Auto reloader consumes full CPU core

### ISSUE THREAD

**Issue by eirikrye** [sanic-org/sanic#2566]
**Describe the bug**

Enabling the auto reloader (`auto_reload=True` or `--auto-reload`) will consume a full CPU core, because it is looping over all files in all loaded modules and `stat`-ing every file. 100% usage on a single core is observed on macOS and Linux.

The problematic loop is here:

https://github.com/sanic-org/sanic/blob/f891995b487f01ff1207afcd241ae359725a8e3c/sanic/worker/reloader.py#L46-L64

**Code snippet**

Run the following minimal example with `python3 test.py` or `sanic test:app --auto-reload` and watch CPU usage

```python
from sanic import Sanic, text

app = Sanic("test")


@app.route("/")
def hello_world(request):
    return text("hello, world")


if __name__ == "__main__":
    app.run(auto_reload=True)
```

**Expected behavior**

The reloader should not consume a full CPU core, but should watch the file system for changes more intelligently, using platform-specific methods (inotify, FSEvents, kqueue, etc). See the [watchdog](https://github.com/gorakhargosh/watchdog/) project for inspiration. Maybe `watchdog` could be included as an optional dependency and used if available?

For instance, [another popular framework has implemented two reloader loops](https://github.com/pallets/werkzeug/blob/2.2.2/src/werkzeug/_reloader.py) and will select the `watchdog` loop if the package is available.

Alternatively, simply add a short sleep step to the reloader loop. I think a one second delay in reloading is acceptable.

**Environment (please complete the following information):**
 - OS: macOS 12.6, Ubuntu Linux 22.04 (likely also Windows, but not tested)
 - Sanic Version: 22.9.0

**Comment by eirikrye** [comment]
I noticed the `Reloader` class already had an `interval` property which is unused. I made a pull request #2567 to actually make use of this interval to sleep in the main loop.

**Comment by ahopkins** [comment]
This issue has been mentioned on **Sanic Community Discussion**. There might be relevant details there:

https://community.sanicframework.org/t/on-intel-mac-the-sanic-dev-mode-uses-99-cpu/1077/2
