### ISSUE TITLE
Sentry integration and background tasks

### ISSUE THREAD

**Issue by cnicodeme** [sanic-org/sanic#2576]
**Describe the bug**
Looking at the Sentry integration, a hub is created on request ('http.lifecycle.request' => `_hub_enter`) and removed at exit ('http.lifecycle.response' => `_hub_exit`).

If I understand this correctly, it means that if an exception occurs outside of the request, no Hub will be define and the exception won't be caught by Sentry.

This can happen when running a long background_task from a request handler that has already returned a response.

**Environment (please complete the following information):**

 - Sanic Version: 22.9.0
- Sentry SDK : 1.9.9

**Comment by cnicodeme** [comment]
(Maybe I should open this ticket at Sentry instead of Sanic? Just let me know)

**Comment by sjsadowski** [comment]
@cnicodeme please open the issue with Sentry, while we may contribute there this is not specifically a sanic issue. I also know they may defer to only supporting our LTS (.12) releases.

**Comment by cnicodeme** [comment]
Ok, will do!
