### ISSUE TITLE
In multiworker mode better error message if no apps

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic#2579]
If a developer does not define their app so that a worker process can access it, they will receive a `KeyError` when Sanic tries to access it from the registry.

For example, that would happen if an app only was instantiated on the main process:

```python
if __name__ == "__main__":
    app = Sanic(...)
    app.run()
```

The solution to this is usually either to move the instantiation outside that block, or to use an [`AppLoader`](https://sanic.dev/en/guide/deployment/app-loader.html).

We should provide a better error message from within a worker process if an app cannot be found in a registry.

**Comment by scardozos** [comment]
I want to take it🙂

**Comment by prryplatypus** [comment]
All yours 😛
