### ISSUE TITLE
A signal handler cannot be a method on an object

### ISSUE THREAD

**Issue by todddialpad** [sanic-org/sanic#2581]
**Describe the bug**

If I try and register a method on an object as a signal handler, an exception is thrown because it is not possible to set an attribute on a bound method
```
    self.add_signal(self.after_routing, 'http.routing.after')
  File "sanic/lib/python3.7/site-packages/sanic/mixins/signals.py", line 77, in add_signal
    handler
  File "sanic/lib/python3.7/site-packages/sanic/mixins/signals.py", line 57, in decorator
    self._apply_signal(future_signal)
  File "sanic/lib/python3.7/site-packages/sanic/app.py", line 420, in _apply_signal
    return self.signal_router.add(*signal)
  File "sanic/lib/python3.7/site-packages/sanic/signals.py", line 222, in add
    handler.__requirements__ = condition  # type: ignore
AttributeError: 'method' object has no attribute '__requirements__'
```

**Code snippet**

```python
import sanic

class MyApp(sanic.Sanic):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.add_signal(self.after_routing, 'http.routing.after')

  def after_routing(self, request, route, kwargs, handler):
    pass

app = MyApp(name='method_signal_handler')
```

**Expected behavior**

I would expect the bound method to be registered, and then called when the signal is dispatched.

**Environment (please complete the following information):**

 - OS: MacOS
 - Sanic Version: 22.9

**Additional context**

**Comment by Tronic** [comment]
Added code tags for readability.

**Comment by ChihweiLHBird** [comment]
<img width="548" alt="image" src="https://user-images.githubusercontent.com/43905414/204127830-dbe8af96-fbfa-43b9-9412-724e4711c1a6.png">

I looked into it and found this was because `method` object doesn't support being injected arbitrary variables. I would like to purpose saving the conditions and triggers in `dict` instead of the handler (`function`) object. One part that confused me is that `__trigger__` saved in the `function` object seems never used.

**Comment by ahopkins** [comment]
Yes, that is correct. IIRC, there is not a great way to pass this info. I'd have to look. Happy to hear a proposal.

**Comment by ChihweiLHBird** [comment]
> Yes, that is correct. IIRC, there is not a great way to pass this info. I'd have to look. Happy to hear a proposal.

How do you think about the draft? https://github.com/sanic-org/sanic/pull/2608
