### ISSUE TITLE
sanic is slower than flask

### ISSUE THREAD

**Issue by hurun** [sanic-org/sanic#2599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

i had a framework speed test between sanic and flask.
env is the same, the code is similar and easy, sanic is slower than flask.  
Also i use other parameter and other task, the result always slower.

python: 3.7
system: wsl ubuntu 18
sanic version: 22.9.1
flask version: 2.2.2

and use apache tools to test, the result is

ab -n 200 -c 20  ab -n 200 -c 20 http://127.0.0.1:5001/sleep_with_flask

              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       0
Processing:    51   53   3.9     52      68
Waiting:       51   53   3.5     51      67
Total:         51   53   3.9     52      68

Percentage of the requests served within a certain time (ms)
  50%     52
  66%     52
  75%     54
  80%     56
  90%     59
  95%     63
  98%     67
  99%     68
 100%     68 (longest request)

#############

ab -n 200 -c 20  ab -n 200 -c 20 http://127.0.0.1:5001/sleep_with_sanic
Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   0.4      0       1
Processing:   153 1018 116.7   1019    1887
Waiting:       53  916 129.8    918    1022
Total:        153 1019 116.6   1020    1887
ERROR: The median and mean for the initial connection time are more than twice the standard
       deviation apart. These results are NOT reliable.

Percentage of the requests served within a certain time (ms)
  50%   1020
  66%   1021
  75%   1021
  80%   1022
  90%   1071
  95%   1072
  98%   1073
  99%   1784
 100%   1887 (longest request)

### Code snippet

the sanic test code is 
###########################start
import time
from sanic import Sanic
from sanic.response import text
app = Sanic("MyHelloWorldApp")

@app.route("/sleep_with_sanic", methods=["GET"])
async def sleep(request):
    time.sleep(0.05)
    print("sleep")
    return text("sleep")

if __name__ == "__main__":
    app.run(port=5000, host="0.0.0.0", debug=False, access_log=False, workers=1)
############################################################end

the flask test code is 
###########################################################start
from flask import Flask
import time

app = Flask(__name__)

@app.route("/sleep_with_flask")
def sleep():
    time.sleep(0.05)
    print("sleep")
    return "sleep"

if __name__ == '__main__':
    app.run(port=5001, host="0.0.0.0", debug=False)
#######################################################end

### Expected Behavior

i expected the result is that sanic faster than flask, in single work or multiply works.
if i use async and await with aiohttp packages,  sanic speed almost like flask with the same code.

### How do you run Sanic?

Sanic CLI

### Operating System

wsl unbuntu18

### Sanic Version

22.9.1

**Comment by ahopkins** [comment]
First, I suggest taking a look [at this doc](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) about formatting code blocks. It will make this post much easier to read.

Second, to address your concern...

Your testing procedure is invalid. You are not testing the framework per se, but the underlying servers with your test. The problem is that Sanic server's concurrency model is based upon [asyncio](https://docs.python.org/3/library/asyncio.html), and werkzeug's is [threading](https://docs.python.org/3/library/threading.html). When you use `time.sleep` you are introducing a blocking sync operation, and is [an incorrect use of Sanic](https://sanic.dev/en/guide/basics/handlers.html#a-word-about-async). Perhaps you may want to brush up on asyncio before working with an async framework.

A [more accurate test between Sanic and Flask](https://web-frameworks-benchmark.netlify.app/result?f=flask,sanic) shows very different results:

![image](https://user-images.githubusercontent.com/166269/201019143-08695f17-2f74-4652-a73b-c141900bd2ed.png)

**Comment by hurun** [comment]
okay, sorry about my bad question written.

The reason for using time.sleep is to ensure that the task is time-consuming fair and is convenient for developers to reproduce.
The real task is the ner parsing task that requests the remote service, but this part of the code cannot be provided.

the true code is like that
```
import requests

@app.route("/syn", methods=["GET"])
async def hello(request):
    resutl = requests.get(
        url,
        params=params,
        headers=headers,
        method="POST",
    )
    # using text('syn'), only for test
    return text("syn")
```

the result is sanic slower than flask.

but if i use the code like this
```
import aiohttp
import requests
async def aio_request(url, params, headers, timeout):
    async with aiohttp.ClientSession() as session:
        async with session.post(url, data=params, headers=headers, timeout=timeout) as resp:
            return json.loads(await resp.text())

async def async_get_data_by_requests(url, params=None, headers=None, timeout=5, method="POST"):
    resp = await aio_request(url, params, headers=headers, timeout=timeout)
        

@app.get("/")
async def hello_world(request):
    result = await async_get_data_by_requests(
        url,
        params=params,
        headers=headers,
        method="POST",
    )
    # using text('syn'), only for test
    return text("syn")
```
the result is sanic faster than flask

**Comment by Tronic** [comment]
You cannot (should not) use blocking sync calls in async frameworks like Sanic. Namely this means that you need to replace `time.sleep` with `asyncio.sleep` and not use **requests** but instead something like **httpx** where you always `await` for operations that may take time.
