### ISSUE TITLE
Touchup Failure

### ISSUE THREAD

**Issue by rmorshea** [sanic-org/sanic#2643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running Sanic as an ASGI application in a test suite where apps are repeatedly started and shutdown, Sanic's touchup logic fails with a `KeyError`.

```python
Traceback (most recent call last):
  File "/home/ryan/Repositories/idom-team/idom/venv/lib/python3.10/site-packages/sanic/asgi.py", line 89, in __call__
    await self.startup()
  File "/home/ryan/Repositories/idom-team/idom/venv/lib/python3.10/site-packages/sanic/asgi.py", line 60, in startup
    await self.asgi_app.sanic_app._startup()
  File "/home/ryan/Repositories/idom-team/idom/venv/lib/python3.10/site-packages/sanic/app.py", line 1572, in _startup
    TouchUp.run(self)
  File "/home/ryan/Repositories/idom-team/idom/venv/lib/python3.10/site-packages/sanic/touchup/service.py", line 24, in run
    modified = BaseScheme.build(method, module_globals, app)
  File "/home/ryan/Repositories/idom-team/idom/venv/lib/python3.10/site-packages/sanic/touchup/schemes/base.py", line 38, in build
    return exec_locals[method.__name__]
KeyError: 'read'
```

Here are some notable facts:

1. This problem does not exist in the last version (v22.9.1).
2. The exact `KeyError` is random, sometimes its `read`, but other times it could be something completely different.
3. The first usages of Sanic works fine. It's the next usages that fails in this way.
4. The server is being run with `uvicorn`.

### Code snippet

I haven't had time to create a truly isolated example. However, if you install the following:

```bash
pip install "idom[sanic,testing]==0.42.0" "uvicorn[standard]==0.20.0"
```

You can reproduce the error I'm seeing with the following code under `sanic==22.12.0`:

```python
from asyncio import run
from idom.testing import BackendFixture
from idom.backend import sanic as sanic_backend

async def main():
    async with BackendFixture(implementation=sanic_backend):
        ...

    async with BackendFixture(implementation=sanic_backend):
        ...

run(main())
```

As mentioned above, running this same code under `sanic==22.9.1` works just fine.

### Expected Behavior

I should be able to start and stop Sanic servers multiple times without error.

### How do you run Sanic?

ASGI

### Operating System

Linux (Ubuntu)

### Sanic Version

22.12.0

**Comment by ahopkins** [comment]
So, I think there is something going on with `idom`. I am not sure what that is, or what it is doing. However, there was NO change in v22.12 that changed how the `touchup` module works.

The only thing that I can guess is that there was a change to report errors on lifespan startup that had previously been ignored. This is likely why you did not see the issue on v22.9 since it was not being reported via ASGI.

**Comment by ahopkins** [comment]
Wait, is the problem in calling it multiple times?

**Comment by ahopkins** [comment]
I think what you are missing is the inherent conversion to `test_mode`.

```python
async def main():
    Sanic.test_mode = True
    ...
```

**Comment by ahopkins** [comment]
This is not a bug. If idom has a test runner, then it should really be setting `test_mode` under the hood.

**Comment by rmorshea** [comment]
I'll try that out and see if it fixes things.
