### ISSUE TITLE
Sanic 22.12.0 disables python logging

### ISSUE THREAD

**Issue by jschewebbn** [sanic-org/sanic#2654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using sanic 22.9.1 I see the output of my python logging calls, however using 22.12.0 I no longer see the output of my logging calls.

### Code snippet

```python
#!/usr/bin/env python3

from sanic import Sanic
from sanic import response as res
import logging
import json

app = Sanic(__name__)

def get_logger():
    return logging.getLogger(__name__)

def setup_logging(
    default_path='logging.json',
    default_level=logging.INFO,
    env_key='LOG_CFG'
):
    """
    Setup logging configuration
    """
    try:
        path = Path(default_path)
        value = os.getenv(env_key, None)
        if value:
            path = Path(value)
        if path.exists():
            with open(path, 'r') as f:
                config = json.load(f)
            logging.config.dictConfig(config)
        else:
            logging.basicConfig(level=default_level)

    except:
        print(f"Error configuring logging, using default configuration with level {default_level}")
        logging.basicConfig(level=default_level)


@app.route("/")
async def test(req):
    get_logger().info("Here is a message")
    return res.text("I\'m a teapot", status=418)


if __name__ == '__main__':
    setup_logging()
    app.run(host="0.0.0.0", port=8000)    
```

### Expected Behavior

When executing `curl http://localhost:8000/` I expect to see "INFO:__main__:Here is a message" output from my sanic process.

### How do you run Sanic?

As a script (`app.run` or `Sanic.serve`)

### Operating System

Linux

### Sanic Version

22.12.0

**Comment by ahopkins** [comment]
You are calling setup logging in your if block. That only runs in the main process, not the worker processes.

**Comment by jschewebbn** [comment]
Related to this, is it possible to get information from the if block to the worker processes? I tried assigning a value to app.ctx.foo in the if block, however the worker processes don't see "foo".
