### ISSUE TITLE
Use custom logging functions or support dynamic logging directories

### ISSUE THREAD

**Issue by xianyongjian080402** [sanic-org/sanic#2679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

tittle（Chinese）：使用自定义的日志函数，或支持动态设置日志保存目录

Unable to get logs to be written to a file by date

（Chinese）
无法让日志按照日期写入文件

### Describe the solution you'd like

I want to store logs by date in a specific directory
There are two ways to solve this
1. Use my custom logging function
2. sanic provides an interface for setting diary writing files

（Chinese）
我想把日志按照日期存储在特定的目录下
目前有2种解决方式
1. 使用我自定义的日志函数
2. sanic提供日记写入文件设置接口

**Comment by ahopkins** [comment]
You can set your own logging config by passing it as a dict to your app instance.

https://sanic.dev/en/guide/best-practices/logging.html#configuration

**Comment by xianyongjian080402** [comment]
I know, but … Do you have specific examples? 🤔

**Comment by ahopkins** [comment]
It uses the python standard lib definition pattern. Any python logging tutorial that explains how to do dict config should be helpful. Linked on the page is the stdlib tutorial which has lots of info.
