### ISSUE TITLE
Type of the variable "file_path" is PosixPath but  mimetypes.guess_type() need a string or byte-like object.

### ISSUE THREAD

**Issue by xSandie** [sanic-org/sanic#2683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the File sanic/mixins/route.py, the type of the variable "file_path"(line:836) is PosixPath but  mimetypes.guess_type() need a string or byte-like object.

In python 3.7.2, the Signature of the function guess_type is given below
```python
def guess_type(url: str,
               strict: bool = ...) -> Tuple[Optional[str], Optional[str]]
```

### Code snippet

File "sanic/mixins/routes.py", line 874, in _static_request_handler
    or guess_type(file_path)[0] 

```python
            if "content-type" not in headers:
                content_type = (
                    content_type
                    or guess_type(file_path)[0]
                    or DEFAULT_HTTP_CONTENT_TYPE
                )
```

### Expected Behavior

In the File sanic/mixins/route.py, the type of the variable "file_path"(line:836)  should be a str or byte-like object.
I added a line of code to forcefully fix it.

```python
file_path = str(file_path)
```

### How do you run Sanic?

As a script (`app.run` or `Sanic.serve`)

### Operating System

Macos Darwin-20.6.0-x86_64-i386-64bit

### Sanic Version

Sanic v22.12.0

### Additional context

packages: sanic-routing==22.8.0
python: 3.7.2
mode: production, single worker

**Comment by Tronic** [comment]
Thanks for your report. Looks like the function actually needs `str` path with forward slash separators, and we could always do the conversion to keep compatibility with Python 3.7 and to handle path separators correctly. Could you make a PR for this?

The `guess_mime` function only takes forward slashes and handles pathlib.Paths incorrectly even on Windows Python 3.11. This actually is a bug in Python, it would seem.

It is a good habit to always convert with `path.as_posix()` unless you specifically need Windows path separators, which are what you get on Windows if you cast it to str, and what this function accidentally does internally if given pathlib.Paths (via os.fspath, on new Python versions at least).

**Comment by xSandie** [comment]
> Thanks for your report. Looks like the function actually needs `str` path with forward slash separators, and we could always do the conversion to keep compatibility with Python 3.7 and to handle path separators correctly. Could you make a PR for this?
> 
> The `guess_mime` function only takes forward slashes and handles pathlib.Paths incorrectly even on Windows Python 3.11. This actually is a bug in Python, it would seem.
> 
> It is a good habit to always convert with `path.as_posix()` unless you specifically need Windows path separators, which are what you get on Windows if you cast it to str, and what this function accidentally does internally if given pathlib.Paths (via os.fspath, on new Python versions at least).
> 
> Test cases on Python 3.11:
> 
> * `/.mp3` maps to None (.mp3 is not a valid filename with extension)
> * `\.mp3` maps to audio/mpeg (it thinks the backslash is the file's name)
> * `pathlib.PurePath('/.mp3')` on Windows maps to audio/mpeg, on other systems maps to None

It only occurs in python3.7 when I upgrade my project to python3.9, it doesn't exist. I think you can Ignore this bug.

**Comment by ahopkins** [comment]
Python 3.7 support will be dropped soon.

**Comment by Tronic** [comment]
I believe this still happened in 3.11 as per my investigation above. Unless Sanic now uses `.as_posix()` somewhere it didn't before. Would need to look at this closer before dismissing as fixed.
