### ISSUE TITLE
Getting first element of an array in request.form.get('arr_name')

### ISSUE THREAD

**Issue by LucasGrasso** [sanic-org/sanic#2698]
I was getting the first element of a array(named 'search_strings'). 
Passing search_strings = ['V','F','X'] and req.form.get('search_strings') would only retrieve 'V'.

```python
print(req.form) #outputs {'search_strings': ['V', 'F', 'X']}
print(req.form.get("search_strings")) #outputs V
```

Had to use 

```python
json.loads(str(req.form).replace("'", '"'))[
        "search_strings"
    ]
```

Being passed as:
![image](https://user-images.githubusercontent.com/66641667/221484387-d1c669f3-376a-4d3c-98e3-e6158d16356d.png)

_Originally posted by @LucasGrasso in https://github.com/sanic-org/sanic/issues/288#issuecomment-1445742071_

**Comment by ahopkins** [comment]
Oy... that's an ugly hack. I would use `getlist`

>  The request.form object is one of a few types that is a dictionary with each value being a list. This is because HTTP allows a single key to be reused to send multiple values.
> 
> Most of the time you will want to use the .get() method to access the first element and not a list. If you do want a list of all items, you can use .getlist().

[source](https://sanic.dev/en/guide/basics/request.html#form)
