### ISSUE TITLE
Follow-Up: Sanic generated code makes coverage throw "couldn't parse" warnings

### ISSUE THREAD

**Issue by rbm-radius** [sanic-org/sanic#2702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Running `coverage run; coverage xml` on a Sanic app causes warnings about unparseable code that seem related to code generated by Sanic.

As an example:

warning: "No source for code: _run_response_middleware (couldnt-parse)

### Code snippet

A full example is provided here:

https://github.com/rogthefrog/sanic-coverage-example

### Expected Behavior

Warnings should not be issued against code that doesn't exist.

### How do you run Sanic?

Sanic CLI

### Operating System

MacOS Monterey 12.4

### Sanic Version

22.12.0

### Additional context

This is a follow-up to https://github.com/sanic-org/sanic/issues/2345 per request from @ahopkins 

Thank you.

**Comment by ahopkins** [comment]
Thanks for putting together the example. Makes it much easier to help you. :heart: 

I would suggest adding this:

```python
from os import environ

if "COVERAGE_RUN" in environ:
    app.config.TOUCHUP = False
```

I confirmed with your test repo that it works.
