### ISSUE TITLE
`Autodiscover` Really good?

### ISSUE THREAD

**Issue by JiehuiSun** [sanic-org/sanic#2755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

If I use autodiscovery, I would find the routing very messy, yes, that's just my idea. Recursion should not be used.

### Describe the solution you'd like

I think we can refer to the structure of django.

---
- main.py
  - module1
    - __init__.py
    - urls.py/routes.py
    - ...
---

This is my own opinion
[My structure](https://github.com/JiehuiSun/sanic_base/tree/master/account)

[Autodiscovery](https://github.com/JiehuiSun/sanic_base/blob/master/application.py#L28) function `config_blueprint`

_I am a beginner in Python and even more novice in Sanic, but these are my personal opinions_

**Comment by ahopkins** [comment]
This issue has been mentioned on **Sanic Community Discussion**. There might be relevant details there:

https://community.sanicframework.org/t/test-client-in-production-for-batch-endpoint/1202/5

**Comment by JiehuiSun** [comment]
您好，邮件已收到。

**Comment by ahopkins** [comment]
This is certainly something you can do if you want. It is unlikely to be something in the core project as it is precisely the type of opinionated concept Sanic tries to avoid. There are many ways you can attach handlers as routes. If this works for you I encourage you to pursue it and even make your own extension for it.
