### ISSUE TITLE
Add ability to intercept the websocket handshake

### ISSUE THREAD

**Issue by marinator86** [sanic-org/sanic#2762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Thank you for this nice project!

In my websocket server, I need to initialize certain resources before a websocket connection handshake can be finished, i.e. I need to connect to a redis server. In a websocket-framework I previously used I could call an accept() method to finish the handshake from the server side manually. This made it easy for me to initialize those resources, and once everything was ready, I accepted the connection.

### Describe the solution you'd like

Add a websocket.accept() method.

**Comment by ahopkins** [comment]
I think the best way to achieve this would be to isolate that websocket endpoint into its own Blueprint, and then add a `on_request` middleware attached to only that blueprint.

**Comment by marinator86** [comment]
thank you, I wasn't aware about that
