### ISSUE TITLE
Infinite task using `loop.create_task` in `main_process_start` is hanging.

### ISSUE THREAD

**Issue by lxdlam** [sanic-org/sanic#2782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've using Sanic with discord.py to start both a discord bot and a Sanic server. I'm initializing the discord bot in a function like:

```python
@app.main_process_start
async def start(app: Sanic, loop: AbstractEventLoop) -> None:
    loop.create_task(bot.start(CLIENT_TOKEN))
```

The `bot.start` call is a async function which is expected to enter a infinite loop. When I start my server through `sanic main:app`, the discord server will never go live, and after sending Ctrl-C, it seems the coroutine is stucked at making connection and prints a error message `Fatal error on transport TCPTransport`.

If I change the decorator into `@app.before_server_start`, it works with no issue, but I want to make only one global instance of the client, instead of making one each worker. Also, I think the behaviour is weird since I have digged into the code and seen nothing special.

### How do you run Sanic?

Sanic CLI

### Operating System

Fedora 38 - Linux 6.3

### Sanic Version

v23.3.0

**Comment by sjsadowski** [comment]
Can you please share the link to your discord bot's code so we can understand what it's trying to do on startup?

**Comment by Tronic** [comment]
The main process will only run that task for a single round (until its first `await`), it would seem. I think the main process does not continuously run its event loop, only the server processes do. As a workaround, you could spawn a thread or process for your bot from `main_process_start`, and use `asyncio.run` in there if your code needs `await`.

**Comment by Tronic** [comment]
I believe the main process doesn't run in async mode. This test case shows that the task is only executed for one round (until the `await`), thus this prints "Running..." only once. If used in server process, it prints the message each second.

```python
import asyncio
from sanic import Sanic

app = Sanic("sanic_server")

async def worker():
    while True:
        print("Running...")
        await asyncio.sleep(1)

@app.main_process_start
async def start(app, loop) -> None:
    loop.create_task(worker())

@app.route("/")
async def test(request):
    ...
```

As a workaround, spawn a thread or a process from `main_server_start` and join/shutdown it in `main_server_stop`. If you need `await`, use `asyncio.run` within your thread/process for your very own event loop. The main process is not quite designed to run extra tasks by itself.

**Comment by lxdlam** [comment]
I see the reason and the workaround is acceptable. Thanks.

**Comment by ahopkins** [comment]
I would not suggest running it in the main process. You should probably run it in its own process.

https://sanic.dev/en/guide/deployment/manager.html#running-custom-processes
