### ISSUE TITLE
 Validation with Dataclasses| About Optional[str] and None

### ISSUE THREAD

**Issue by scriptkitz** [sanic-org/sanic#2794]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

```python
from typing import Optional

@dataclass
class VClass:
    name: Optional[str] = None
    num: Optional[int] = None

@app.route("/")
@validate(form=VClass)
def test(req, body):
    print(body.name, type(body.name))
    print(body.num, type(body.num))

```

curl http://localhost/

-----------RESULT---------------
None <class 'str'>
None <class 'NoneType'>

---------------------------------

**The value of body.name is the string "None" , not a NoneType. 
Is this a bug?**

### How do you run Sanic?

As a script (`app.run` or `Sanic.serve`)

### Operating System

Windows

### Sanic Version

v23.3.0

**Comment by ChihweiLHBird** [comment]
I confirm this issue is reproduceable. If no one else had started working on this, I will look into it.

**Comment by ChihweiLHBird** [comment]
@sanic-org/sanic-release-managers 
Can we transfer this issue to [sanic-ext repo](https://github.com/sanic-org/sanic-ext)?
