### ISSUE TITLE
RuntimeError: context has already been set. When I use both Sanic and loguru

### ISSUE THREAD

**Issue by ChrisYP** [sanic-org/sanic#2819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

python version:3.8
Name: sanic
Version: 23.6.0
Name: loguru
Version: 0.7.1

```
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set 
```

### Code snippet

```python
from sanic import Sanic, text
from loguru import logger

app = Sanic(__name__)


@app.get('/')
async def run_shell(request):
    return text('Hello world!')


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=6666, debug=True, access_log=True, workers=2)
```

### How do you run Sanic?

As a script (`app.run` or `Sanic.serve`)

### Operating System

MacOS

### Sanic Version

23.6.0

**Comment by ahopkins** [comment]
Sounds like this is an issue with loguru. I have never heard of it, but a real quick look at their docs seems to suggest that they are trying to hijack the subprocess: https://loguru.readthedocs.io/en/stable/resources/recipes.html#compatibility-with-multiprocessing-using-enqueue-argument

Sanic does indeed us `spawn`. [More info](https://sanic.dev/en/guide/deployment/manager.html)

**Comment by Heerozh** [comment]
Using `multiprocessing.Queue()` in the main process will result this error too.

**Comment by dongrixinyu** [comment]
> Using `multiprocessing.Queue()` in the main process will result this error too.
> 
> Because it will call `BaseContext.get_context()`, causing the global context to be set
> 
> Also in Python 3.12.4，if you use `logging.config.dictConfig`, with:
> 
>   handlers:
>     log_queue: 
>       class: logging.handlers.QueueHandler
>       queue: any queue doesn't matter
> This error will also be triggered.
> 
> Because`proxy_queue = MM().Queue()` in [config.py#L792](https://github.com/python/cpython/blob/8e8a4baf652f6e1cee7acde9d78c4b6154539748/Lib/logging/config.py#L792) will set the global context too.
> 
> Previously, I used tqdm to display some preprocessing progress, which also caused this error.
> 
> There are too many situations that may trigger this error

how do you fix or avoid this bug?

**Comment by jschewebbn** [comment]
So how can one use sanic and loguru or the QueueHandler in the default logging package?
