### ISSUE TITLE
remove tracerite from the standard install

### ISSUE THREAD

**Issue by TimurDela** [sanic-org/sanic#2833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Tracerite raises many deprecation warnings, I am not developing in a Notebook environment and I feel that I should not have to install tracerite in order to use sanic.
These deprecation warnings make the development experience with Sanic much less pleasant (for instance my unit tests reports get filled with those warnings).

Would it be possible to remove tracerite from the sanic dependencies?

### How do you run Sanic?

As a module

### Operating System

MacOS

### Sanic Version

23.6.0

**Comment by sjsadowski** [comment]
Recategorized appropriately to a deprecation, as deprecation warnings are not bugs.

**For discussion:** @sanic-org/core-devs should tracerite be moved to sanic-ext as a dependency rather than part of sanic itself?

**Comment by prryplatypus** [comment]
I believe it's a dependency here because we use it for custom error pages. @Tronic and @ahopkins might know more about it.

**Comment by Tronic** [comment]
The problematic module that Tracerite depends on may need to be removed. Tracerite is now an integral part of Sanic exception handling. Closing this in favor of keeping discussion to https://github.com/sanic-org/tracerite/issues/8
