### ISSUE TITLE
Introduce ruff execution on the examples and scripts folder

### ISSUE THREAD

**Issue by iAndriy** [sanic-org/sanic#2867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Recently we've introduced the ruff formatter as the substitution to the black.
Ruff tool points to sanic folder and at the same time we can leverage this tool to ensure that example and scripts folder are complaint with flake rules and their formatting is consisted with the sanic package.

### Describe the solution you'd like

Run ruff fix for the example and scripts folder and extend make command/ruff configuration to take into account folders mentioned above.

**Comment by ahopkins** [comment]
😎 Thanks.

**Comment by iAndriy** [comment]
> 😎 Thanks.

You welcome @ahopkins
