### ISSUE TITLE
(websockets 12.0) DeprecationWarning: websockets.connection was renamed to websockets.protocol and Connection was renamed to Protocol

### ISSUE THREAD

**Issue by Gerhut** [sanic-org/sanic#2873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The DeprecationWarning is thrown here:

https://github.com/sanic-org/sanic/blob/82bf46bea3b55e6b1371107cccda280add8e70eb/sanic/server/protocols/websocket_protocol.py#L4-L9

With websockets 12 the try block would run successfully with the warning while the catch block does not have chance to be run.

### Expected Behavior

The catch block is being run instead.

### How do you run Sanic?

Sanic CLI

### Operating System

MacOS

### Sanic Version

Sanic 23.6.0; Routing 23.6.0

**Comment by Corwinpro** [comment]
Thanks for raising this! I think I am seeing the same issue, it appears that `sanic` is not putting constraint on `websockets` version from above, which should be <=11. With that in place, this can be resolved automatically (no need to handle different cases IMO).

**Comment by ChihweiLHBird** [comment]
Although it triggers a deprecation warning, the `try...except...` block will work when the classes are actually removed in `websockets` package in the future. Checking version of a package requires an additional dependency `packaging`, which we wouldn't like to add, thus I think we can just ignore the warning.

**Comment by Tronic** [comment]
> Although it triggers a deprecation warning, the `try...except...` block will work when the classes are actually removed in `websockets` package in the future. Checking version of a package requires an additional dependency `packaging`, which we wouldn't like to add, thus I think we can just ignore the warning.

Can't you `try` the new API, which will give ImportError or such but no deprecation warnings, and `except` fallback to old API?

**Comment by ChihweiLHBird** [comment]
@Tronic You are right, lol. I will try that way.

**Comment by eric-spitler** [comment]
I realize the changes in #2919 resolve the chance of an `ImportError`, but I believe the spirit of this issue is that the `DeprecationWarning` get resolved. With the changes here, it tries the old import, then "falls back" to the correct new implementation.
https://github.com/sanic-org/sanic/blob/a575f5c8858248680653c5a5b9565be4dcc56f9a/sanic/server/websockets/impl.py#L19-L24

As @Tronic said, it would be better to attempt the new import, then fall back to the old way if someone has an older version of `websockets` installed. Thereby resolving the `DeprecationWarning`.
```python
try:  # websockets >= 11.0
    from websockets.protocol import Event, State  # type: ignore
    from websockets.server import ServerProtocol  # type: ignore
except ImportError:  # websockets < 11.0
    from websockets.connection import Event, State  # type: ignore
    from websockets.server import ServerConnection as ServerProtocol
```
