### ISSUE TITLE
Multiplexer and Manager out of sync on number of expected arguments

### ISSUE THREAD

**Issue by ahopkins** [sanic-org/sanic#2894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The manager is expecting the wrong number of arguments. Therefore app.m.manage is not working as intended.

```
[ERROR] Monitor received an invalid message: ('foobar', <function foo at 0x7fd1c8ce34c0>, {}, False, None, False, True, 1)
```

### How do you run Sanic?

Sanic CLI

### Operating System

Linux

### Sanic Version

23.12.0

**Comment by Tronic** [comment]
Closing as it appears to have been fixed by the merged PR.
