### ISSUE TITLE
Start-up exception

### ISSUE THREAD

**Issue by jsonvot** [sanic-org/sanic#2908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1、DeprecationWarning
![image](https://github.com/sanic-org/sanic/assets/23091750/2c8effc0-558e-4bf9-adb0-88f93b6f2524)
2、IndexError
Use the following CLI to start
```sanic main:app --host 0.0.0.0 --port 9001 --workers 2 --dev```
![image](https://github.com/sanic-org/sanic/assets/23091750/d3841a3e-a5a3-43b3-9d6c-1cc1d43fce8a)

### How do you run Sanic?

Sanic CLI

### Operating System

Linux

### Sanic Version

23.12.1

**Comment by Huy-Ngo** [comment]
first issue is #2898, second issue is #2889
