### ISSUE TITLE
The RESTful API has redundant path parameters

### ISSUE THREAD

**Issue by jsonvot** [sanic-org/sanic#2910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The RESTful API of the post method should not have the last path argument appear
<img width="1433" alt="image" src="https://github.com/sanic-org/sanic/assets/23091750/f8a34aec-9f9b-4e85-b2e7-4c6aecfdda4c">

### Code snippet

```python
from sanic import Sanic
from sanic.blueprints import Blueprint
from sanic.request import Request
from sanic.response import json
from sanic.views import HTTPMethodView

app = Sanic(__name__)
app.config.update({
    'OAS_UI_DEFAULT': 'swagger'
})


class UserView(HTTPMethodView):
    middleware = []

    async def get(self, request: Request):
        return json({'code': 200})

    async def post(self, request: Request):
        return json({'code': 200})

    async def put(self, request: Request):
        return json({'code': 200})

    async def delete(self, request: Request):
        return json({'code': 200})


user_bp = Blueprint('user_bp')
user_bp.add_route(UserView.as_view(), '/api/user/<user_id:int>')

app.blueprint(user_bp)
```

### How do you run Sanic?

Sanic CLI

### Operating System

Linux

### Sanic Version

23.12.1

**Comment by aldem** [comment]
Just out of curiosity - why it is redundant?

`POST` method  may have a path argument when we want to explicitly name a resource or to assign a specific id, in some cases it could be even mandatory.
