### ISSUE TITLE
Blueprint.group and decorator

### ISSUE THREAD

**Issue by cnsino** [sanic-org/sanic#2952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Does sanic support adding decorators to the entire blueprint group?
```
from .content import content
from .info import info
...

api = Blueprint.group(content, info, ... , url_prefix="/api")
```
```
def protected(wrapped):
    def decorator(f):
        @wraps(f)
        async def decorated_function(request, *args, **kwargs):
            is_authenticated = check_token(request)

            if is_authenticated:
                response = await f(request, *args, **kwargs)
                return response
            else:
                return text("You are unauthorized.", 401)

        return decorated_function

    return decorator(wrapped)
```

### Describe the solution you'd like

Expect for example
```
from .content import content
from .info import info
...

api = Blueprint.group(content, info, ... , url_prefix="/api")
# api.add_decorator(protected)

```

**Comment by imnotjames** [comment]
You can apply middleware to the group, would that get you close to what you're looking for?

**Comment by cnsino** [comment]
Are there any relevant examples?

**Comment by imnotjames** [comment]
> Are there any relevant examples?

Yup, in the docs

https://sanic.dev/en/guide/best-practices/blueprints.html#middleware
