### ISSUE TITLE
sanic 23 `FORWARDED_SECRET` value with `-` or `_` behavior weired

### ISSUE THREAD

**Issue by yurenchen000** [sanic-org/sanic#2953]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

|                                         | app.config.FORWARDED_SECRET='chen-secret' | FORWARDED_SECRET='chen_secret' |
|-----------------------------------------|-------------------------------------------|---------------------------------|
| curl -H 'forwarded: secret=chen-secret' | fail                                      | work                            |
| curl -H 'forwarded: secret=chen_secret' | work                                      | fail                            |

it behavior weired

### Code snippet

https://sanic.dev/en/guide/advanced/proxy-headers.html#forwarded-header

```py
# test fwd
from sanic import Sanic
from sanic.response import json

# sanic app
app = Sanic(__name__)

## tested on sanic 23.12.1, 23.3.0

### FORWARDED_SECRET behavior weird
# app.config.FORWARDED_SECRET = 'chen-secret' 	## WARN: need client 'chen_secret'
app.config.FORWARDED_SECRET = 'chen_secret' 	## WARN: need client 'chen-secret

### REAL_IP_HEADER behavior as expected
app.config.REAL_IP_HEADER = 'chen-realip'
# app.config.REAL_IP_HEADER = 'chen_realip'
app.config.PROXIES_COUNT = 1

print('--config_fwd_secret:', app.config.FORWARDED_SECRET)

@app.route("/fwd")
async def forwarded(request):
    return json(
        {
            "remote_addr": request.remote_addr,
            "scheme": request.scheme,
            "server_name": request.server_name,
            "server_port": request.server_port,
            "forwarded": request.forwarded,
            "config_fwd_secret": app.config.FORWARDED_SECRET,
        }
    )

'''
test1:
  curl -s localhost:8080/fwd -H 'forwarded: secret=chen-secret' -H 'chen-realip: 123.45.6.7'
test2:
  curl -s localhost:8080/fwd -H 'forwarded: secret=chen_secret' -H 'chen-realip: 123.45.6.7'
'''
```

### Expected Behavior

maybe, client and server use same value?

```console
$ curl -s localhost:8080/fwd -H 'forwarded: secret=chen_secret' -H 'chen-realip: 123.45.6.7' | jq
{
  "remote_addr": "123.45.6.7",
  "scheme": "http",
  "server_name": "localhost",
  "server_port": 8080,
  "forwarded": {
    "for": "123.45.6.7"
  },
  "config_fwd_secret": "chen_secret"
}

$ curl -s localhost:8080/fwd -H 'forwarded: secret=chen-secret' -H 'chen-realip: 123.45.6.7' | jq
{
  "remote_addr": "123.45.6.7",
  "scheme": "http",
  "server_name": "localhost",
  "server_port": 8080,
  "forwarded": {
    "for": "123.45.6.7"
  },
  "config_fwd_secret": "chen-secret"
}
```
### How do you run Sanic?

Sanic CLI

### Operating System

Linux

### Sanic Version

23.12.1, 23.3.0

### Additional context

//test result:

run server
```console
$ ~/.local/bin/sanic test_fwd --port 8080
```

client test
```console
$ curl -s localhost:8080/fwd -H 'forwarded: secret=chen_secret' -H 'chen-realip: 123.45.6.7' | jq
{
  "remote_addr": "",
  "scheme": "http",
  "server_name": "localhost",
  "server_port": 8080,
  "forwarded": {
    "secret": "chen_secret"
  },
  "config_fwd_secret": "chen_secret"
}

$ curl -s localhost:8080/fwd -H 'forwarded: secret=chen-secret' -H 'chen-realip: 123.45.6.7' | jq
{
  "remote_addr": "123.45.6.7",
  "scheme": "http",
  "server_name": "localhost",
  "server_port": 8080,
  "forwarded": {
    "for": "123.45.6.7"
  },
  "config_fwd_secret": "chen_secret"
}
```

**Comment by ChihweiLHBird** [comment]
I am not familiar with the reverse proxy feature, but isn't this what you wanted: `curl localhost:8000/fwd -H 'forwarded: secret=chen-secret;for=1.2.3.4' -H 'chen-realip: 123.45.6.7' | jq` when you need `for` to be `1.2.3.4`?

Sanic `main` branch response:
```json
{
  "remote_addr": "1.2.3.4",
  "scheme": "http",
  "server_name": "localhost",
  "server_port": 8000,
  "forwarded": {
    "secret": "chen-secret",
    "for": "1.2.3.4"
  },
  "config_fwd_secret": "chen-secret"
}
```

I think the real IP would only be the value of `for` if there is not a `for` in `Forwarded` header with the correct secret.

Again, this is my first time to learn about the proxy header feature, correct me if I was wrong. Thanks!

**Comment by yurenchen000** [comment]
> I am not familiar with the reverse proxy feature, but isn't this what you wanted: `curl localhost:8000/fwd -H 'forwarded: secret=chen-secret;for=1.2.3.4' -H 'chen-realip: 123.45.6.7' | jq` when you need `for` to be `1.2.3.4`?
> 
> Sanic `main` branch response:
> 
> ```json
> {
>   "remote_addr": "1.2.3.4",
>   "scheme": "http",
>   "server_name": "localhost",
>   "server_port": 8000,
>   "forwarded": {
>     "secret": "chen-secret",
>     "for": "1.2.3.4"
>   },
>   "config_fwd_secret": "chen-secret"
> }
> ```
> 
> I think the real IP would only be the value of `for` if there is not a `for` in `Forwarded` header with the correct secret.
> 
> Again, this is my first time to learn about the proxy header feature, correct me if I was wrong. Thanks!

in short,
when i set `app.config.FORWARDED_SECRET = 'chen_secret' ` in sanic

only client request with `-H 'forwarded: secret=chen-secret` works. is it wierd? should't it be `chen_secret`(which same with sanic setting)?

vice versa if set `app.config.FORWARDED_SECRET = 'chen-secret' ` in sanic.
the `-` and `_` misplaced.

**Comment by ChihweiLHBird** [comment]
Hi @yurenchen000, not sure what response value you are expecting, but in my experiment, if `app.config.FORWARDED_SECRET` is set to `chen-secret`, calling it with `forwarded: secret=chen_secret` or `forwarded: secret=invalid` header would return a same response, which differs from the call with the correct secret `chen-secret`.

```
$ curl -s localhost:8000/fwd -H 'forwarded: secret=chen-secret' -H 'chen-realip: 123.45.6.7' | 
jq
{
  "remote_addr": "",
  "scheme": "http",
  "server_name": "localhost",
  "server_port": 8000,
  "forwarded": {
    "secret": "chen-secret"
  },
  "config_fwd_secret": "chen-secret"
}
$ curl -s localhost:8000/fwd -H 'forwarded: secret=chen_secret' -H 'chen-realip: 123.45.6.7' | 
jq
{
  "remote_addr": "123.45.6.7",
  "scheme": "http",
  "server_name": "localhost",
  "server_port": 8000,
  "forwarded": {
    "for": "123.45.6.7"
  },
  "config_fwd_secret": "chen-secret"
}
$ curl -s localhost:8000/fwd -H 'forwarded: secret=invalid' -H 'chen-realip: 123.45.6.7' | jq
{
  "remote_addr": "123.45.6.7",
  "scheme": "http",
  "server_name": "localhost",
  "server_port": 8000,
  "forwarded": {
    "for": "123.45.6.7"
  },
  "config_fwd_secret": "chen-secret"
}
```

**Comment by yurenchen000** [comment]
@ChihweiLHBird 
Sorry it took so long to reply.
After your reply,
I noticed there only **valid** (same with server conf) and **invalid** (not same with server conf) secrets.

then,
 Only request with **invalid** secret (sanic) can get the fwd real ip?
 That's weird, isn't it?

 (Should only the request with correct secret  can pass the fwd ip)?

**Comment by ChihweiLHBird** [comment]
Hi @yurenchen000, according to the [docs](https://sanic.dev/en/guide/advanced/proxy-headers.html#example-1):

> Without configured FORWARDED_SECRET, x-headers should be respected

The `x-headers` in this case is `REAL_IP_HEADER` you configured, so it will only be effective if `FORWARDED_SECRET` is not configured or not received.

And if you would like to use the secret, you can place the remote IP in the `Forwarded` header, like:

```
curl localhost:8000/fwd -H 'forwarded: secret=chen-secret;for=123.45.6.7' | jq

{
  "remote_addr": "123.45.6.7",
  "scheme": "http",
  "server_name": "localhost",
  "server_port": 8000,
  "forwarded": {
    "secret": "chen-secret",
    "for": "123.45.6.7"
  },
  "config_fwd_secret": "chen-secret"
}
```

In the [example 3 of the doc](https://sanic.dev/en/guide/advanced/proxy-headers.html#example-3), it shows the expected behavior when `Forwarded` header and the secret are not included, `X-headers` (in your case is `chen-realip`) is respected.

**Comment by yurenchen000** [comment]
@ChihweiLHBird thanks for you reply.
i had check that examples in doc before i create this issue.
but i didn't really get it.

then what the secret used for?
 it means just telling sanic, **drop** the fwd related headers (or named x-headers) ?

**Comment by ChihweiLHBird** [comment]
Hi @yurenchen000, the secret would become effective when you have a `for` key in the `Forwarded` header. The IP in `for` will become remote address in Sonic.

```
'Forwarded: secret=chen-secret;for=123.45.6.7'
```

**Comment by yurenchen000** [comment]
thanks, seems the logic is:

if `seceret` match:
 &nbsp; use `for` address
else:
 &nbsp; use `REAL_IP_HEADER` custom header 
  &nbsp; or `X-Real-IP` or ..
