### ISSUE TITLE
Official integration with Tortoise ORM occurring sync operations and errors 

### ISSUE THREAD

**Issue by dinosaurtirex** [sanic-org/sanic#2957]
### Proposal

# Without integration 

![1](https://github.com/sanic-org/sanic/assets/58666088/5c0d83fc-52a1-404f-b62f-e5d3d0b43a7f)
![2](https://github.com/sanic-org/sanic/assets/58666088/9df48ef3-60fa-49a1-bbf4-472b572b4818)

# With integration 

![3](https://github.com/sanic-org/sanic/assets/58666088/9664a0d4-aa46-4b6d-97d6-19268ba8aa1c)
![4](https://github.com/sanic-org/sanic/assets/58666088/1885c564-3fa9-4f82-81ec-e052f5fde135)

Is it any way to avoid this?

I am sorry to make this issue to sanic, it is probably problem of Tortoise ORM itself, but it still offical example in documentation with this code. Do someone know how to avoid this? 

<img width="1032" alt="image" src="https://github.com/sanic-org/sanic/assets/58666088/eceedc6e-a3a4-467a-ad6f-39c628160219">

### Is this a breaking change?

- [ ] Yes

**Comment by dinosaurtirex** [comment]
I guess any "long" task, no matter sync it or async, occurred this error on start, including import initialization and etc, so it's not the problem, didn't it?

**Comment by ahopkins** [comment]
This seems more like a [support request](https://sanic.dev/en/help.html). Also, I cannot see your error because it is a small image, and when I try to open it, GH says it is a private image or something.
