### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by f754699** [sanic-org/sanic#2985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug
```
 File "F:\pythonproject\sanicResolve2\.venv\Lib\site-packages\sanic\mixins\startup.py", line 1180, in serve
    while cls._get_process_states(worker_state):
                                  ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'worker_state' where it is not associated with a value
```
### Code snippet
```python
from sanic import Sanic, text, json

app = Sanic("fuwu")

if __name__ == '__main__':
    app.run(host="0,0,0,0", port=8000, )
```

### Expected Behavior

启动就报错，

### How do you run Sanic?

as a model

### Operating System

Windows

### Sanic Version

sanic = {extras = ["ext"], version = "^24.6.0"}

**Comment by ChihweiLHBird** [comment]
Seems to be a Windows specific issue. I would recommend trying it on a Linux or Unix system machine while we are looking into the issue.

目前Sanic在Windows上确实存在这个问题，在此问题被修复前，建议使用Linux或Unix系统尝试。

**Comment by pygeek** [comment]
This is still a bug, however. `mixins.startup.serve` should still exit gracefully.
