### ISSUE TITLE
dynamic update blueprint

### ISSUE THREAD

**Issue by amoxuk** [sanic-org/sanic#2991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

some package in my folder, I want add new package in the folder at sanic running.

> @app.get('xx')
> async def reload(rq):
> for folder in os.listdir('somefolder'):
>   pkg = importlib.import_module(folder)
>   _lib.append(pkg.app)
> bp = Bleprint.group(*_lib,url_prefix='/someurl')
> app.router.reset()
> app.blueprint(bp)

reload success but use the url throw error.
Nonetype  object is not callable in sanic router

### How do you run Sanic?

As a script (`app.run` or `Sanic.serve`)

### Operating System

Linux

### Sanic Version

22.12.0

**Comment by amoxuk** [comment]
add app.finalize()  to solve this pronlem.

But here is a new problem.

After reload, I can request the blueprint url many times if I refresh the browser quickly, but it returns 404 after the sanic logs 'KeepAlive Timeout,Closing cojnextion.'. 

It looks like I reload a temp variable of 'app'. 

How to reload the gloable app?

**Comment by ahopkins** [comment]
This is very much not advised. We have had this debate in the past about dynamically generated URLs, and while it is possible, I would not suggest it. What is the use case for this?

**Comment by ahopkins** [comment]
Take a look at [app.amend](https://sanic.dev/api/sanic.app.html#sanic-app-sanic-amend)
