### ISSUE TITLE
Incorrect address returned when listening to IPv6

### ISSUE THREAD

**Issue by moyanj** [sanic-org/sanic#2994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I set the `host` to  `::` , the returned IP address (both  `request.client_ip` and  `request.ip` ) is incorrect when accessing via IPv4.
Just like this: `::ffff:127.0.0.1`

### Code snippet

```python
from sanic import Sanic, response
from sanic.request import Request
app = Sanic("MyApp")

@app.route("/")
async def test(request: Request):
    return response.text(request.ip)
   
if __name__ == "__main__":
    app.run(host="::", port=8080, debug=True)
```

### Expected Behavior

Returns the correct IPv4 address

### How do you run Sanic?

As a script (`app.run` or `Sanic.serve`)

### Operating System

Linux

### Sanic Version

24.6.0

**Comment by ahopkins** [comment]
This is not incorrect, and is in fact what [RFC 5952](https://datatracker.ietf.org/doc/html/rfc5952#section-5) and [RFC 4291](https://www.rfc-editor.org/rfc/rfc4291#section-2.2) represent.
