### ISSUE TITLE
sanic response.json() serialize problem

### ISSUE THREAD

**Issue by Hotant-Bu** [sanic-org/sanic#2995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the response.json() function cannot serialize fields of type datetime

### Code snippet

TypeError: Object of type datetime is not JSON serializable

### How do you run Sanic?

As a script (`app.run` or `Sanic.serve`)

### Operating System

Windows

### Sanic Version

24.6.0

**Comment by SaidBySolo** [comment]
Numbers, strings, arrays, Boolean, null, and json objects can be used as json values. 

It is up to the user to convert the datetime format appropriately. 

Try converting it to a number or string.

**Comment by SaidBySolo** [comment]
If you want to serialize datetime only on that route, it can be done like this:

```py
def datetime_to_json_formatting(o):
    if isinstance(o, (date, datetime)):
        return o.strftime('%Y%m%d %H%M%S')

@app.get("/example")
async def example(request):
    body = {'time': datetime.now(), 'body': 'string'}
    return response.json(body, default=datetime_to_json_formatting)
```

To serialize globally, implement a dump function that serializes the datetime and pass it as an argument to your Sanic app.
```py
def datetime_to_json_formatting(o):
    if isinstance(o, (date, datetime)):
        return o.strftime('%Y%m%d %H%M%S')

custom_dumps = functools.partial(ujson.dumps, default=datetime_to_json_formatting)

app = Sanic("app", dumps=custom_dumps)

…
```

**Comment by Hotant-Bu** [comment]
ok, I see,Thanks





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ryu ***@***.***&gt;; 
发送时间: 2024年9月2日(星期一) 上午6:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sanic-org/sanic] sanic response.json() serialize problem (Issue #2995)














 
If you want to serialize datetime only on that route, it can be done like this:
 def datetime_to_json_formatting(o):     if isinstance(o, (date, datetime)):         return o.strftime('%Y%m%d %H%M%S') @app.get("/example") async def example(request):     body = {'time': datetime.now(), 'body': 'string'}     return response.json(body, default=datetime_to_json_formatting)
 
To serialize globally, implement a dump function that serializes the datetime and pass it as an argument to your Sanic app.
 def datetime_to_json_formatting(o):     if isinstance(o, (date, datetime)):         return o.strftime('%Y%m%d %H%M%S') custom_dumps = functools.partial(ujson.dumps, default=datetime_to_json_formatting) app = Sanic("app", dumps=custom_dumps) …
