### ISSUE TITLE
Add Python 3.13 to CI Tests

### ISSUE THREAD

**Issue by robd003** [sanic-org/sanic#2996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Can we be proactive and make sure that Sanic will be compatible with Python 3.13 when it's released in early October?

MagicStack just released v0.21.0beta1 which has support for Python 3.13

**Comment by ahopkins** [comment]
Of course. The big question is of course uvloop.

**Comment by Tishka17** [comment]
As I see, httptools doesn't currentyl compile on 3.13 and response on ticket https://github.com/MagicStack/httptools/issues/104

Should we get rid of this dependency?

**Comment by robd003** [comment]
hhtptools 0.6.2 was just released with compatibility for Python 3.13

**Comment by robd003** [comment]
@ahopkins uvloop just released a version compatible with Python 3.13!

https://github.com/MagicStack/uvloop/releases/tag/v0.21.0

Do you know when we could get Sanic LTS tested against Python 3.13?
