### ISSUE TITLE
Is there a plan for compatibility with Python 3.13 no GIL?

### ISSUE THREAD

**Issue by yuWorm** [sanic-org/sanic#2999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Python 3.13 introduces free threading. Although it will certainly take a long time to reach a usable state, I still want to know if Sanic has any plans to be compatible with no GIL.

**Comment by immerautumn** [comment]
I'm curious how this would look for users of the library; would those of us who are wrapping calls be on the hook for race conditions; the signs point to YES, and in some instances, that could mean deeply subtle bugs.


The idea of shipping a new container image FROM python:3.13 and pressing start may not be a thing with true concurrency. I have loved this library for a long time now, and can confidently say we have used it as stopgaps in multiple production issues, as well as low throughput backends with a quick turnaround. It's handled hundreds of millions of calls for us across really big names, and it's fast for python 3.5~3.11

I'm a plus one on the step it up crowd.

**Comment by Tronic** [comment]
Sanic itself doesn't use threads and thus I'd assume it to not be affected, except that as GIL-free it would run slower. However, aiofiles, asyncio/uvloop and other possibly things internally use threading that could pose issues. Did you give it a try, what happened?

**Comment by ahopkins** [comment]
I have played around with this a while back, and yes, it is still not stable. And yes, as mentioned it doesn't impact performance because we do not use threads. With that said, I have played with some alternative ideas that may be impacted by this down the road, but it is all very experimental as this stage.
