### ISSUE TITLE
Sockets

### ISSUE THREAD

**Issue by beliboba** [sanic-org/sanic#3001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Are sockets still in sanic? Only mention i found is [here](https://sanic.readthedocs.io/en/18.12.0/sanic/sockets.html)

### Describe the solution you'd like

sockets.

### Additional context

meow

**Comment by Tronic** [comment]
The documentation at readthedocs is outdated. You will find current documentation at sanic.dev

UNIX sockets can be used by `sanic --unix` or `app.run(unix="sanic.sock")`, so you don't need to handle sockets directly anymore.

There's no separate documentation page on it, but it is mentioned in
https://sanic.dev/en/guide/running/running.md#running-sanic
https://sanic.dev/en/guide/deployment/caddy.html#advanced-configuration

**Comment by beliboba** [comment]
i wanted to make webserver on sockets (udp/tcp) not http
