### ISSUE TITLE
Why hasn’t it been updated for 3 months? Have you given up?

### ISSUE THREAD

**Issue by pendy99** [sanic-org/sanic#3002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

I like this framework very much, but why hasn’t it been updated in more than 3 months?

**Comment by GoodReese** [comment]
oh no...

**Comment by ahopkins** [comment]
Nope. Definitely not. Lots of PRs coming soon and new release at the end of the year. This goes for sanic-ext and sanic-testing too.
