### ISSUE TITLE
Routing Fails when request not declared as param

### ISSUE THREAD

**Issue by Goldziher** [sanic-org/sanic#3012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```python
async def handle_generate_draft_request(application_id: UUID) -> HTTPResponse:
```

If i do not declare a `request` parameter in the route handler, the server throws 500.

This works:

```python
async def handle_generate_draft_request(request: Request, application_id: UUID) -> HTTPResponse:
```

As does this:

```python
async def handle_generate_draft_request(_, application_id: UUID) -> HTTPResponse:
```

- note, i have no use for the request object in this particular case. Hence I omitted it. 

### Code snippet

async def handle_generate_draft_request(application_id: UUID) -> HTTPResponse:
    pass

### Expected Behavior

I am able to not declare the request object. Inspection should suffice to determine this. 

### How do you run Sanic?

Sanic CLI

### Operating System

Linux

### Sanic Version

latest

**Comment by ahopkins** [comment]
> a handler is any callable that takes at least a [sanic.request.Request](https://sanic.dev/api/sanic.request.html) instance as an argument ...
[Source](https://sanic.dev/en/guide/basics/handlers.html)

This is current expected behavior.
